'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function release(){return require('../../dist/games/ai-battle-royale/src/release/validation.js')}
const SHA='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';

test('Battle Royale Phase 6 bundle is deterministic, software-complete and truthfully blocked at R4',()=>{const{createBattleValidationBundle}=release();const a=createBattleValidationBundle(SHA),b=createBattleValidationBundle(SHA);assert.deepEqual(a,b);assert.equal(a.softwareVerdict,'PASS');assert.equal(a.readiness.verdict,'BLOCKED');assert.equal(a.readiness.highestTruthfulReadiness,'R4');assert.equal(a.readiness.productionReady,false);assert.equal(a.integrity.invariantFailures,0);assert.equal(a.integrity.illegalActions,0);assert.equal(a.integrity.replayDivergences,0);assert.equal(a.integrity.duplicateEffects,0);assert.equal(a.integrity.unauthorizedControls,0);assert.equal(a.integrity.privateExposures,0);assert.equal(a.campaign.totalInvariantFailures,0);assert.equal(a.campaign.totalDuplicateApplications,0);assert.equal(a.campaign.deterministicRerunReady,true);assert.equal(a.chaos.status,'pass');assert.equal(a.drills.implementationStatus,'pass');assert.equal(a.capacity.performancePass,true);assert.equal(a.capacity.productionReferenceSatisfied,false);assert.match(a.bundleChecksum,/^[0-9a-f]{8}$/)});

test('synthetic or CI evidence cannot promote Battle Royale to R5',()=>{const{createBattleValidationBundle}=release();const bundle=createBattleValidationBundle(SHA);assert.equal(bundle.endurance.status,'blocked');assert.equal(bundle.providers.status,'blocked');assert.equal(bundle.safety.status,'blocked');assert.equal(bundle.drills.productionStatus,'blocked');assert.notEqual(bundle.canary.status,'eligible');for(const blocker of['production-reference-capacity','provider-validation','safety-attestations','production-drills','seven-day-canary','independent-review'])assert.ok(bundle.readiness.blockers.includes(blocker),blocker);assert.equal(bundle.readiness.productionReady,false)});

test('Battle Royale candidate source must be an exact Git commit SHA',()=>{const{createBattleValidationBundle}=release();assert.throws(()=>createBattleValidationBundle('main'),error=>error.code==='INVALID_CANDIDATE_SHA');assert.throws(()=>createBattleValidationBundle('abc123'),error=>error.code==='INVALID_CANDIDATE_SHA')});

test('Battle Royale integrity or open P0/P1 findings produce FAIL rather than external BLOCKED',()=>{const{createBattleValidationBundle}=release();const bundle=createBattleValidationBundle(SHA,{integrity:{invariantFailures:1,illegalActions:1,replayDivergences:1,duplicateEffects:1,privateExposures:1,openP0:1,openP1:1}});assert.equal(bundle.readiness.verdict,'FAIL');assert.equal(bundle.readiness.productionReady,false);assert.ok(bundle.readiness.failures.length>0);assert.equal(bundle.softwareVerdict,'FAIL')});
