'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function load(){return require('../../dist/games/ai-maze-escape/src/release/validation.js')}
const SHA='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
test('Maze Phase 6 bundle is deterministic, software-complete, and truthfully blocked at R4',()=>{const{createMazeValidationBundle}=load();const a=createMazeValidationBundle(SHA),b=createMazeValidationBundle(SHA);assert.deepEqual(a,b);assert.equal(a.softwareVerdict,'PASS');assert.equal(a.readiness.verdict,'BLOCKED');assert.equal(a.readiness.highestTruthfulReadiness,'R4');assert.equal(a.readiness.productionReady,false);assert.equal(a.integrity.hiddenInformationViolations,0);assert.equal(a.integrity.unsolvableContent,0);assert.equal(a.integrity.replayDivergences,0);assert.equal(a.integrity.duplicateEffects,0);assert.equal(a.campaign.totalInvariantFailures,0);assert.equal(a.campaign.totalDuplicateApplications,0);assert.equal(a.chaos.status,'pass');assert.equal(a.drills.implementationStatus,'pass');assert.equal(a.capacity.performancePass,true);assert.equal(a.capacity.productionReferenceSatisfied,false);assert.match(a.bundleChecksum,/^[0-9a-f]{8}$/)});
test('synthetic provider, endurance, drills and canary evidence cannot accidentally promote to R5',()=>{const{createMazeValidationBundle}=load(),bundle=createMazeValidationBundle(SHA);assert.equal(bundle.endurance.status,'blocked');assert.equal(bundle.providers.status,'blocked');assert.equal(bundle.safety.status,'blocked');assert.equal(bundle.drills.productionStatus,'blocked');assert.equal(bundle.canary.status,'blocked');assert.ok(bundle.readiness.blockers.includes('production-reference-capacity'));assert.ok(bundle.readiness.blockers.includes('provider-validation'));assert.ok(bundle.readiness.blockers.includes('safety-attestations'));assert.ok(bundle.readiness.blockers.includes('production-drills'));assert.ok(bundle.readiness.blockers.includes('seven-day-canary'));assert.ok(bundle.readiness.blockers.includes('independent-review'))});
test('candidate source must be an exact Git commit SHA',()=>{const{createMazeValidationBundle}=load();assert.throws(()=>createMazeValidationBundle('main'),error=>error.code==='INVALID_CANDIDATE_SHA');assert.throws(()=>createMazeValidationBundle('abc123'),error=>error.code==='INVALID_CANDIDATE_SHA')});
test('integrity overrides produce FAIL rather than an externally BLOCKED verdict',()=>{const{createMazeValidationBundle}=load(),bundle=createMazeValidationBundle(SHA,{integrity:{hiddenInformationViolations:1,unsolvableContent:1,replayDivergences:1,duplicateEffects:1,openP0:1}});assert.equal(bundle.readiness.verdict,'FAIL');assert.equal(bundle.readiness.productionReady,false);assert.ok(bundle.readiness.failures.length>0);assert.equal(bundle.softwareVerdict,'FAIL')});
