'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
function validation(){return require('../../dist/games/ai-city-traffic/src/release/validation.js')}
function score(){return require('../../dist/games/ai-city-traffic/src/release/score.js')}
const SHA_A='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',SHA_B='bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
test('Phase 6 exports deterministic release, readiness, score, and drill contracts',()=>{const release=validation();for(const name of ['createTrafficReleaseManifest','createTrafficValidationBundle','MANDATORY_TRAFFIC_DRILLS'])assert.ok(release[name],name);assert.equal(typeof score().scoreTrafficReadiness,'function')});
test('software-complete candidate is truthfully R4 and blocked from R5 by real-world evidence',()=>{const{createTrafficValidationBundle}=validation(),a=createTrafficValidationBundle(SHA_A),b=createTrafficValidationBundle(SHA_A);assert.deepEqual(a,b);assert.equal(a.softwareVerdict,'PASS');assert.equal(a.readiness.verdict,'BLOCKED');assert.equal(a.readiness.highestTruthfulReadiness,'R4');assert.equal(a.readiness.productionReady,false);assert.equal(a.traceability.status,'complete');assert.equal(a.campaign.deterministicRerunReady,true);assert.equal(a.campaign.totalInvariantFailures,0);assert.equal(a.campaign.totalDuplicateApplications,0);assert.equal(a.campaign.technicalOutcomes,0);assert.equal(a.chaos.ok,true);assert.equal(a.capacity.performancePass,true);assert.equal(a.capacity.productionReferenceSatisfied,false);assert.equal(a.integrity.collisions,0);assert.equal(a.integrity.replayDivergences,0);assert.equal(a.integrity.privateExposures,0);assert.match(a.bundleChecksum,/^[0-9a-f]{8}$/)});
test('synthetic or self-attested evidence cannot accidentally promote the candidate',()=>{const bundle=validation().createTrafficValidationBundle(SHA_A);for(const blocker of ['production-reference-capacity','real-72-hour-endurance','provider-validation','safety-attestations','production-drills','seven-day-canary','independent-review'])assert.ok(bundle.readiness.blockers.includes(blocker),blocker);assert.equal(bundle.endurance.status,'blocked');assert.equal(bundle.providers.status,'blocked');assert.equal(bundle.safety.status,'blocked');assert.equal(bundle.drills.productionStatus,'blocked');assert.equal(bundle.canary.status,'blocked');assert.equal(bundle.independentReview.status,'missing')});
test('release artifacts and requirement evidence are bound to the exact candidate SHA',()=>{const{createTrafficReleaseManifest,createTrafficValidationBundle}=validation(),first=createTrafficReleaseManifest(SHA_A),second=createTrafficReleaseManifest(SHA_B);assert.notEqual(first.checksum,second.checksum);assert.notDeepEqual(first.artifacts.map(item=>item.digest),second.artifacts.map(item=>item.digest));assert.ok(first.artifacts.every(item=>item.kind==='software-evidence'&&/^checksum:[a-f0-9]{8}$/.test(item.digest)));const bundle=createTrafficValidationBundle(SHA_A);assert.ok(bundle.evidence.every(item=>item.candidateChecksum===bundle.manifest.checksum&&item.sourceSha===SHA_A))});
test('candidate source must be a full Git commit SHA and integrity failures fail closed',()=>{const{createTrafficValidationBundle}=validation();assert.throws(()=>createTrafficValidationBundle('main'),error=>error.code==='INVALID_CANDIDATE_SHA');assert.throws(()=>createTrafficValidationBundle('abc123'),error=>error.code==='INVALID_CANDIDATE_SHA');const failed=createTrafficValidationBundle(SHA_A,{integrity:{collisions:1,replayDivergences:1,duplicateEffects:1,privateExposures:1,openP0:1}});assert.equal(failed.softwareVerdict,'FAIL');assert.equal(failed.readiness.verdict,'FAIL');assert.equal(failed.readiness.productionReady,false);assert.ok(failed.readiness.failures.length>=5)});
test('readiness score identifies a strong production candidate without overstating production readiness',()=>{const bundle=validation().createTrafficValidationBundle(SHA_A),report=score().scoreTrafficReadiness(bundle);assert.ok(report.score>=75&&report.score<=89,JSON.stringify(report));assert.equal(report.grade,'Production Candidate');assert.equal(report.verdict,'BLOCKED');assert.equal(report.highestTruthfulReadiness,'R4');assert.equal(report.productionReady,false);assert.match(report.scoreChecksum,/^[a-f0-9]{8}$/)});
test('operations runbook and phase gates cover every mandatory drill and truthful R5 boundary',()=>{const{MANDATORY_TRAFFIC_DRILLS}=validation(),root=path.resolve(__dirname,'../..'),runbook=path.join(root,'docs/operations/ai-city-traffic-runbook.md'),phaseDir=path.join(root,'games/ai-city-traffic/phases');assert.equal(fs.existsSync(runbook),true,runbook);const content=fs.readFileSync(runbook,'utf8');for(const id of MANDATORY_TRAFFIC_DRILLS)assert.ok(content.includes(`\`${id}\``),id);for(const phrase of ['safe scene','verified restore','rollback','independent witness','72-hour','seven-day canary'])assert.match(content,new RegExp(phrase,'i'));for(let phase=1;phase<=6;phase++)assert.equal(fs.existsSync(path.join(phaseDir,`PHASE_${phase}.md`)),true,`Phase ${phase}`)});
test('CI and candidate script generate traffic evidence and scan authoritative nondeterminism',()=>{const root=path.resolve(__dirname,'../..'),workflow=fs.readFileSync(path.join(root,'.github/workflows/ci.yml'),'utf8'),script=fs.readFileSync(path.join(root,'scripts/run-city-traffic-validation.cjs'),'utf8');for(const phrase of ['Traffic stream host self-test','Traffic Phase 5 chaos evidence','Traffic Phase 6 release validation evidence','games/ai-city-traffic/src/runtime','games/ai-city-traffic/src/rules','ai-city-traffic-phase6-validation'])assert.ok(workflow.includes(phrase),phrase);assert.match(script,/CANDIDATE_SOURCE_SHA/);assert.match(script,/softwareVerdict/);assert.match(script,/readiness/);assert.match(script,/process\.exitCode=1/)});
test('stream host persists verified snapshots atomically and bounds restore crash loops',()=>{const os=require('node:os'),storePath=path.resolve(__dirname,'../../scripts/lib/traffic-snapshot-store.cjs');assert.equal(fs.existsSync(storePath),true,storePath);const{TrafficSnapshotFileStore}=require(storePath),directory=fs.mkdtempSync(path.join(os.tmpdir(),'traffic-store-')),file=path.join(directory,'traffic.snapshot.json'),store=new TrafficSnapshotFileStore(file),runtime=require('../../dist/games/ai-city-traffic/src/index.js').TrafficRuntime.create({width:4,height:4,runTicks:600},'durable-store');for(let i=0;i<40;i++)runtime.step();store.write(runtime.snapshot());assert.equal(fs.existsSync(file),true);assert.equal(fs.existsSync(`${file}.tmp`),false);const restored=require('../../dist/games/ai-city-traffic/src/index.js').TrafficRuntime.restore(store.load());assert.equal(restored.checksum(),runtime.checksum());const mode=fs.statSync(file).mode&0o777;assert.equal(mode&0o077,0);fs.writeFileSync(file,'{"corrupt":true}',{mode:0o600});assert.throws(()=>require('../../dist/games/ai-city-traffic/src/index.js').TrafficRuntime.restore(store.load()));const quarantined=store.quarantine('invalid snapshot');assert.equal(fs.existsSync(quarantined),true);assert.equal(fs.existsSync(file),false);const source=fs.readFileSync(path.resolve(__dirname,'../../scripts/serve-city-traffic-stream.cjs'),'utf8');assert.match(source,/TrafficSnapshotFileStore/);assert.match(source,/recoveryAttempts/);assert.match(source,/TRAFFIC_SNAPSHOT_PATH/)});
