'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function load(){return require('../../dist/games/ai-zombie-survival/src/release/validation.js')}
const SHA='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
test('Zombie Phase 6 bundle is deterministic, software-complete, and truthfully blocked at R4',()=>{const{createZombieValidationBundle}=load();const a=createZombieValidationBundle(SHA),b=createZombieValidationBundle(SHA);assert.deepEqual(a,b);assert.equal(a.softwareVerdict,'PASS');assert.equal(a.readiness.verdict,'BLOCKED');assert.equal(a.readiness.highestTruthfulReadiness,'R4');assert.equal(a.readiness.productionReady,false);assert.equal(a.integrity.hiddenInformationViolations,0);assert.equal(a.integrity.replayDivergences,0);assert.equal(a.integrity.duplicateEffects,0);assert.equal(a.campaign.totalInvariantFailures,0);assert.equal(a.campaign.totalDuplicateApplications,0);assert.equal(a.chaos.passed,true);assert.equal(a.drills.implementationStatus,'pass');assert.equal(a.capacity.performancePass,true);assert.equal(a.capacity.productionReferenceSatisfied,false);assert.match(a.bundleChecksum,/^[0-9a-f]{8}$/)});
test('synthetic or missing external evidence cannot accidentally promote Zombie to R5',()=>{const{createZombieValidationBundle}=load(),bundle=createZombieValidationBundle(SHA);assert.equal(bundle.endurance.status,'blocked');assert.equal(bundle.providers.status,'blocked');assert.equal(bundle.safety.status,'blocked');assert.equal(bundle.drills.productionStatus,'blocked');assert.equal(bundle.canary.status,'blocked');for(const blocker of ['production-reference-capacity','provider-validation','safety-attestations','production-drills','seven-day-canary','independent-review'])assert.ok(bundle.readiness.blockers.includes(blocker),blocker)});
test('Zombie candidate source must be an exact Git commit SHA',()=>{const{createZombieValidationBundle}=load();assert.throws(()=>createZombieValidationBundle('main'),error=>error.code==='INVALID_CANDIDATE_SHA');assert.throws(()=>createZombieValidationBundle('abc123'),error=>error.code==='INVALID_CANDIDATE_SHA')});
test('Zombie integrity failures produce FAIL rather than an externally BLOCKED verdict',()=>{const{createZombieValidationBundle}=load(),bundle=createZombieValidationBundle(SHA,{integrity:{hiddenInformationViolations:1,replayDivergences:1,duplicateEffects:1,openP0:1}});assert.equal(bundle.readiness.verdict,'FAIL');assert.equal(bundle.readiness.productionReady,false);assert.ok(bundle.readiness.failures.length>0);assert.equal(bundle.softwareVerdict,'FAIL')});
