import{checksum}from'../../../../packages/replay/src/index';import{NamedRng}from'../../../../packages/seeded-rng/src/index';
import{parseTowerConfig,type TowerConfig}from'../config/schema';import{platformAtTick}from'../generation/chunks';import{solveTowerRoute}from'../generation/solver';import{createInitialTowerState,type TowerPolicyMode}from'../index';import{applyTowerAction,makeTowerTerminal}from'../rules/step';import type{TowerAction,TowerEvent,TowerPlatform,TowerState}from'../state/types';
export interface TowerRuntimeOptions{policy?:TowerPolicyMode}
function zeroAction():TowerAction{return{move:0,jump:false,dash:false,attack:false,ability:false}}
function signMove(value:number):TowerAction['move']{return Math.abs(value)<4000?0:value>0?1:-1}
function currentPlatform(state:TowerState,id:string|undefined){if(!id)return undefined;const raw=state.chunks.flatMap(c=>c.platforms).find(p=>p.id===id);return raw?platformAtTick(raw,state.tick):undefined}
function launchPoint(current:TowerPlatform,target:TowerPlatform,state:TowerState){const p=state.player,safeLeft=current.x+p.halfWidth+6000,safeRight=current.x+current.width-p.halfWidth-6000,targetCenter=target.x+target.width/2;if(target.x<=current.x+current.width&&target.x+target.width>=current.x)return Math.max(safeLeft,Math.min(safeRight,targetCenter));return targetCenter<current.x?safeLeft:safeRight}
function oracleAction(state:TowerState):TowerAction{
  const chunk=state.chunks.find(c=>c.floor===state.floor)??state.chunks[state.chunks.length-1],route=solveTowerRoute(chunk,state.config),p=state.player;if(!route)return zeroAction();
  let targetId=state.ai.targetPlatformId;
  if(p.grounded&&p.groundedPlatformId){const index=route.indexOf(p.groundedPlatformId);targetId=route[index+1];state.ai.targetPlatformId=targetId}
  if(!targetId){const support=route[0];if(!p.grounded){state.ai.targetPlatformId=support;return zeroAction()}targetId=route[1];state.ai.targetPlatformId=targetId}
  const target=currentPlatform(state,targetId);if(!target)return zeroAction();const targetCenter=target.x+target.width/2;
  if(!p.grounded){const move=signMove(targetCenter-p.position.x),dash=Math.abs(targetCenter-p.position.x)>165000&&p.dashCooldown===0&&p.stamina>=20&&p.velocity.y>0;return{move,jump:false,dash,attack:false,ability:false}}
  const support=currentPlatform(state,p.groundedPlatformId);if(!support)return zeroAction();const launchX=launchPoint(support,target,state),delta=launchX-p.position.x,move=signMove(delta);if(Math.abs(delta)>12000)return{move,jump:false,dash:false,attack:false,ability:false};const toward=signMove(targetCenter-p.position.x);return{move:toward,jump:true,dash:false,attack:false,ability:false}
}
export class TowerRuntime{
  public events:TowerEvent[]=[];public state:TowerState;public rng:NamedRng;private seq:number;
  private constructor(public config:TowerConfig,public seed:string,public readonly policy:TowerPolicyMode,state?:TowerState,rng?:NamedRng,nextEventSeq=0,events:TowerEvent[]=[]){this.seq=nextEventSeq;this.rng=rng??NamedRng.fromSeed(seed);this.state=state??createInitialTowerState(config,seed,`tower-run-${checksum({seed,floor:config.launchFloor})}`,this.rng);this.events=events.map(e=>structuredClone(e));if(!state)this.emit('initialized',{seed,policy})}
  static create(config:Partial<TowerConfig>,seed:string,options:TowerRuntimeOptions={}){return new TowerRuntime(parseTowerConfig(config),seed,options.policy??'autonomous')}
  static restore(config:TowerConfig,seed:string,policy:TowerPolicyMode,state:TowerState,rng:NamedRng,nextEventSeq=0,events:TowerEvent[]=[]){return new TowerRuntime(config,seed,policy,state,rng,nextEventSeq,events)}
  private emit(type:string,data?:Record<string,unknown>,tick=this.state.tick){this.events.push({seq:this.seq++,tick,type,data})}
  private chooseAction(){this.state.ai.decisions++;if(this.policy==='idle-test'){this.state.ai.mode='idle-test';this.state.ai.intent='Holding position for lifecycle verification';return zeroAction()}const action=oracleAction(this.state);this.state.ai.mode=this.policy==='oracle-test'?'oracle-test':'climbing';this.state.ai.intent=action.jump?'Committing to the validated next platform':action.dash?'Dashing across the validated gap':action.move?'Aligning with the validated launch point':'Waiting for ground contact';this.state.ai.confidence=.95;return action}
  step(action?:Partial<TowerAction>){if(this.state.lifecycle==='result'){this.state=structuredClone(this.state);this.state.lifecycle='intermission';this.state.intermissionRemaining=this.config.intermissionTicks;this.emit('intermission');return this.state}if(this.state.lifecycle==='intermission'){this.state=structuredClone(this.state);this.state.intermissionRemaining--;if(this.state.intermissionRemaining<=0)this.restart(`${this.seed}:restart:${this.state.tick}`);return this.state}const selected=action??this.chooseAction(),out=applyTowerAction(this.state,selected,this.rng);this.state=out.state;if(!out.accepted){this.state.stats.invalidActions++;this.emit('action-rejected',{reason:out.reason??'unknown'})}for(const e of out.events)this.emit(e.type,e.data,e.tick);if(!this.state.result&&this.state.tick>=this.config.maxTicks){this.state=makeTowerTerminal(this.state,'timer-expired');this.emit('game-terminal',{reason:'timer-expired'})}else if(!this.state.result&&this.state.tick-this.state.meaningfulEventTick>=this.config.noProgressTicks){this.state=makeTowerTerminal(this.state,'stagnation');this.emit('game-terminal',{reason:'stagnation'})}this.state.ai.recentHeights.push(this.state.height);if(this.state.ai.recentHeights.length>64)this.state.ai.recentHeights.shift();this.emit('ai-intent',{mode:this.state.ai.mode,intent:this.state.ai.intent});return this.state}
  restart(seed=this.seed){const restarts=this.state.stats.restarts+1;this.seed=seed;this.rng=NamedRng.fromSeed(seed);this.state=createInitialTowerState(this.config,seed,`tower-run-${checksum({seed,floor:this.config.launchFloor})}`,this.rng);this.state.stats.restarts=restarts;this.emit('restart',{seed});return this.state}
  drainEvents(limit=10000){if(!Number.isInteger(limit)||limit<0)throw new RangeError('limit');return this.events.splice(0,Math.min(limit,this.events.length))}
  getNextEventSequence(){return this.seq}
}
