import type{TowerEvent}from'../state/types';import{TowerAudioDirector,type TowerAudioFrame}from'./audio';import{TowerCameraDirector,type TowerCameraFrame}from'./camera';import{computeTowerLayout,type TowerLayout}from'./layout';import type{TowerRenderSnapshot}from'./snapshot';
export interface TowerOutputProbe{frameAgeMs:number;blackRatio:number;frozenFrames:number;audioAgeMs:number;intendedSilence:boolean;scene:string}
export interface TowerOutputHealth{status:'healthy'|'degraded'|'unsafe';reasons:string[];action:'none'|'observe'|'safe-scene'}
export function classifyTowerOutputHealth(probe:TowerOutputProbe):TowerOutputHealth{const reasons:string[]=[];if(probe.frameAgeMs>1500)reasons.push('stale-frame');if(probe.frozenFrames>=4)reasons.push('frozen-output');if(probe.blackRatio>=.95)reasons.push('black-output');if(!probe.intendedSilence&&probe.audioAgeMs>5000)reasons.push('silent-output');const unsafe=probe.frameAgeMs>5000||(probe.blackRatio>=.95&&probe.frozenFrames>=30)||reasons.length>=3;return unsafe?{status:'unsafe',reasons,action:'safe-scene'}:reasons.length?{status:'degraded',reasons,action:'observe'}:{status:'healthy',reasons:[],action:'none'}}
export interface TowerPresentationFrame{scene:'normal'|'danger'|'upgrade'|'guardian'|'result'|'intermission'|'recovery';tick:number;layout:TowerLayout;camera:TowerCameraFrame;audio:TowerAudioFrame;snapshot:Readonly<TowerRenderSnapshot>|null;replayAvailable:number;failureReason:string}
export class TowerPresentationController{
  private latest:Readonly<TowerRenderSnapshot>|null=null;private replay:Readonly<TowerRenderSnapshot>[]=[];private failed=false;private failureReason='';private readonly replayCapacity:number;private readonly maxEntities:number;private readonly audio:TowerAudioDirector;private readonly camera=new TowerCameraDirector();private audioFrame:TowerAudioFrame={muted:false,voices:[],captions:[],musicState:'calm'};
  constructor(options:{replayCapacity?:number;maxEntities?:number;muted?:boolean}={}){this.replayCapacity=options.replayCapacity??300;this.maxEntities=options.maxEntities??1024;this.audio=new TowerAudioDirector({muted:options.muted,maxVoices:6})}
  accept(snapshot:Readonly<TowerRenderSnapshot>,events:TowerEvent[]){const count=snapshot.platforms.length+snapshot.hazards.length+snapshot.enemies.length+snapshot.projectiles.length+snapshot.pickups.length;if(count>this.maxEntities)return{accepted:false,reason:'entity-capacity'};if(this.latest){if(snapshot.runToken===this.latest.runToken&&snapshot.revision<this.latest.revision)return{accepted:false,reason:'stale-revision'};if(snapshot.runToken===this.latest.runToken&&snapshot.revision===this.latest.revision){if(snapshot.publicChecksum!==this.latest.publicChecksum)return{accepted:false,reason:'divergent-revision'};this.audioFrame=this.audio.consume(events,{danger:snapshot.dangerPermille,guardian:snapshot.enemies.some(e=>e.active&&e.kind==='guardian'),result:!!snapshot.result});return{accepted:true,reason:'duplicate'}}if(snapshot.runToken!==this.latest.runToken&&snapshot.tick!==0)return{accepted:false,reason:'invalid-run-boundary'}}this.latest=snapshot;this.replay.push(snapshot);if(this.replay.length>this.replayCapacity)this.replay.splice(0,this.replay.length-this.replayCapacity);this.audioFrame=this.audio.consume(events,{danger:snapshot.dangerPermille,guardian:snapshot.enemies.some(e=>e.active&&e.kind==='guardian'),result:!!snapshot.result});return{accepted:true,reason:'current'}}
  failOutput(reason:string){this.failed=true;this.failureReason=reason}
  rebuildFromLatest(){const recovered=!!this.latest;if(recovered){this.failed=false;this.failureReason=''}return{recovered}}
  replayWindow(limit=120){return this.replay.slice(-Math.max(0,Math.min(limit,this.replayCapacity)))}
  frame(width=1920,height=1080,options:{reducedMotion?:boolean;cleanFeed?:boolean;muted?:boolean}={}):TowerPresentationFrame{if(options.muted!==undefined)this.audio.setMuted(options.muted);const snapshot=this.latest,guardian=!!snapshot?.enemies.some(e=>e.active&&e.kind==='guardian'),scene=this.failed?'recovery':snapshot?.lifecycle==='result'?'result':snapshot?.lifecycle==='intermission'?'intermission':snapshot?.upgradeOffers.length?'upgrade':guardian?'guardian':snapshot?.dangerPermille&&snapshot.dangerPermille>=800?'danger':'normal',layout=computeTowerLayout(width,height,{cleanFeed:options.cleanFeed}),camera=snapshot?this.camera.frame(snapshot,{width:layout.stage.width,height:layout.stage.height},{reducedMotion:!!options.reducedMotion}):{centerX:0,centerY:0,zoom:1,impulse:0,lookAheadY:0};return{scene,tick:snapshot?.tick??0,layout,camera,audio:this.audioFrame,snapshot,replayAvailable:this.replay.length,failureReason:this.failureReason}}
  diagnostic(){return{failed:this.failed,failureReason:this.failureReason,tick:this.latest?.tick??0,runToken:this.latest?.runToken??'',acceptedReplay:this.replay.length,latestChecksum:this.latest?.publicChecksum??'',captions:this.audioFrame.captions.length}}
}
