'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{ZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/runtime/run');
const{createZombieSnapshot,restoreZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/replay/snapshot');
const{checksum}=require('../../dist/packages/replay/src/index');
function compact(){return{width:24,height:16,dayTicks:4,nightTicks:5,resultTicks:2,maxDays:2,maxZombies:64,initialSurvivors:4}}
const snapshotMaterial=s=>({schemaVersion:s.schemaVersion,gameId:s.gameId,deterministicVersion:s.deterministicVersion,seed:s.seed,tick:s.tick,payload:s.payload,rng:s.rng,nextEventSequence:s.nextEventSequence,events:s.events});
test('identical inputs produce identical state, events and checksums',()=>{const a=ZombieRuntime.create(compact(),'determinism'),b=ZombieRuntime.create(compact(),'determinism');for(let i=0;i<30;i++){a.step();b.step();assert.equal(a.stateChecksum(),b.stateChecksum())}assert.deepEqual(a.events,b.events);assert.equal(checksum(a.state),checksum(b.state))});
test('runtime advances preparation, horde, result, intermission and automatic restart',()=>{const runtime=ZombieRuntime.create({...compact(),maxDays:1},'lifecycle'),seen=new Set([runtime.state.lifecycle]);for(let i=0;i<40;i++){runtime.step();seen.add(runtime.state.lifecycle)}assert.ok(seen.has('preparation'));assert.ok(seen.has('horde'));assert.ok(seen.has('result'));assert.ok(seen.has('intermission'));assert.ok(runtime.events.some(event=>event.type==='run-restarted'))});
test('terminal result is immutable until lifecycle moves to intermission',()=>{const runtime=ZombieRuntime.create({...compact(),maxDays:1},'terminal');while(runtime.state.lifecycle!=='result')runtime.step();const result=structuredClone(runtime.state.result),checksumAtResult=runtime.stateChecksum();runtime.step();assert.deepEqual(runtime.state.result,result);assert.notEqual(runtime.state.lifecycle,'active');assert.notEqual(runtime.stateChecksum(),checksumAtResult)});
test('snapshot restore equals uninterrupted continuation including RNG and event sequence',()=>{const uninterrupted=ZombieRuntime.create(compact(),'restore');for(let i=0;i<7;i++)uninterrupted.step();const snapshot=createZombieSnapshot(uninterrupted),restored=restoreZombieRuntime(snapshot);for(let i=0;i<20;i++){uninterrupted.step();restored.step();assert.equal(restored.stateChecksum(),uninterrupted.stateChecksum())}assert.deepEqual(restored.rng.snapshot(),uninterrupted.rng.snapshot());assert.equal(restored.getNextEventSequence(),uninterrupted.getNextEventSequence())});
test('restore rejects corrupt payload, unsupported versions and invariant violations',()=>{const runtime=ZombieRuntime.create(compact(),'corruption'),snapshot=createZombieSnapshot(runtime);assert.throws(()=>restoreZombieRuntime({...snapshot,checksum:'00000000'}),/checksum/);assert.throws(()=>restoreZombieRuntime({...snapshot,schemaVersion:99}),/schemaVersion/);const duplicate=structuredClone(snapshot);duplicate.payload.survivors[1].id=duplicate.payload.survivors[0].id;duplicate.checksum=checksum(snapshotMaterial(duplicate));assert.throws(()=>restoreZombieRuntime(duplicate),/duplicate survivor/)});
test('snapshot checksum and restore reject event or envelope tampering and discontinuity',()=>{const runtime=ZombieRuntime.create(compact(),'event-integrity');for(let i=0;i<5;i++)runtime.step();const snapshot=createZombieSnapshot(runtime);const changedEvent=structuredClone(snapshot);changedEvent.events[0].type='forged';assert.throws(()=>restoreZombieRuntime(changedEvent),/checksum/);const changedTick=structuredClone(snapshot);changedTick.tick++;assert.throws(()=>restoreZombieRuntime(changedTick),/checksum/);const discontinuous=structuredClone(snapshot);discontinuous.events.at(-1).seq+=3;discontinuous.checksum=checksum(snapshotMaterial(discontinuous));assert.throws(()=>restoreZombieRuntime(discontinuous),/event sequence/)});
test('cosmetic random draws cannot perturb authoritative outcomes',()=>{const a=ZombieRuntime.create(compact(),'streams'),b=ZombieRuntime.create(compact(),'streams');for(let i=0;i<20;i++){for(let draw=0;draw<10;draw++)b.rng.nextInt('cosmetic-authority-free',1000);a.step();b.step();assert.equal(a.stateChecksum(),b.stateChecksum())}});
