'use strict';
const fs=require('node:fs'),path=require('node:path');
const {test,expect}=require('@playwright/test');
const artifacts=path.resolve(__dirname,'../../artifacts/tower-phase3');
test.use({launchOptions:{args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}});
test.beforeAll(()=>fs.mkdirSync(artifacts,{recursive:true}));
test('actual 3-axis autonomous world moves through depth and height',async({page})=>{
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.setViewportSize({width:1600,height:900});
  await page.goto('http://127.0.0.1:4176/tower/volumetric',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.__TOWER_VOLUMETRIC_STATE__?.status==='live',null,{timeout:30000});
  const first=await page.evaluate(()=>({...window.__TOWER_VOLUMETRIC_STATE__}));
  expect(first.dimensionality).toBe(3);
  expect(first.autonomous).toBe(true);
  await page.waitForTimeout(5000);
  const second=await page.evaluate(()=>({...window.__TOWER_VOLUMETRIC_STATE__}));
  expect(second.tick).toBeGreaterThan(first.tick+60);
  expect(second.platforms).toBeGreaterThanOrEqual(15);
  expect(Math.abs(second.z-first.z)).toBeGreaterThan(.3);
  expect(second.score).toBeGreaterThanOrEqual(first.score);
  expect(second.guardianKills).toBeGreaterThanOrEqual(first.guardianKills);
  expect(second.health).toBeGreaterThan(0);
  expect(Number.isFinite(second.y)).toBe(true);
  await page.screenshot({path:path.join(artifacts,'gauntlet-volumetric-3axis.png'),fullPage:true});
  fs.writeFileSync(path.join(artifacts,'volumetric-3axis-diagnostics.json'),JSON.stringify({first,second,errors},null,2));
  expect(errors).toEqual([]);
});
