'use strict';
const{test,expect}=require('@playwright/test');const fs=require('node:fs');
const URL='http://127.0.0.1:4175/traffic';
test.beforeAll(()=>fs.mkdirSync('artifacts/traffic-phase3',{recursive:true}));

test('traffic stream communicates objective, flow, danger, and AI intent at 1080p',async({page})=>{const errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});await page.setViewportSize({width:1920,height:1080});await page.goto(URL,{waitUntil:'networkidle'});await expect(page.locator('#system-status')).toContainText(/live|complete|loading/i);await expect(page.locator('#mobility-score')).not.toHaveText('');await expect(page.locator('#ai-intent')).not.toHaveText('');await expect(page.locator('#congestion')).toContainText('%');await expect(page.locator('#city-canvas')).toBeVisible();const dimensions=await page.locator('#city-canvas').evaluate(canvas=>({width:canvas.width,height:canvas.height}));expect(dimensions.width).toBeGreaterThan(1200);expect(dimensions.height).toBeGreaterThan(700);expect(errors).toEqual([]);await page.screenshot({path:'artifacts/traffic-phase3/desktop-1080p.png',fullPage:true})});

test('traffic stream remains readable without horizontal overflow on a phone viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(URL,{waitUntil:'networkidle'});await expect(page.locator('#mobility-score')).toBeVisible();await expect(page.locator('#ai-intent')).toBeVisible();await expect(page.locator('#caption')).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);const scoreSize=await page.locator('#mobility-score').evaluate(node=>parseFloat(getComputedStyle(node).fontSize));expect(scoreSize).toBeGreaterThanOrEqual(34);await page.screenshot({path:'artifacts/traffic-phase3/mobile-390x844.png',fullPage:true})});

test('traffic stream supports reduced motion and privacy-safe public state',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`${URL}?reducedMotion=1`,{waitUntil:'networkidle'});const animation=await page.locator('.live-pill span').evaluate(node=>getComputedStyle(node).animationName);expect(animation).toBe('none');const state=await page.evaluate(async()=>await(await fetch('/traffic/state?w=390&h=844&reducedMotion=1')).json());const text=JSON.stringify(state);for(const forbidden of ['seed','runId','viewerRef','rateWindows','pendingDemand'])expect(text).not.toContain(forbidden);expect(state.layout).toBe('mobile');expect(state.options.reducedMotion).toBe(true);expect(state.snapshot.accessibility.colorIndependent).toBe(true)});
