import{NamedRng}from'../../../../packages/seeded-rng/src/index';import type{TowerAction,TowerEnemy,TowerEvent,TowerProjectile,TowerState}from'../state/types';
function overlap(a:{position:{x:number;y:number};halfWidth:number;halfHeight:number},b:{position:{x:number;y:number};halfWidth:number;halfHeight:number},padding=0){return Math.abs(a.position.x-b.position.x)<a.halfWidth+b.halfWidth+padding&&Math.abs(a.position.y-b.position.y)<a.halfHeight+b.halfHeight+padding}
function damagePlayer(state:TowerState,amount:number,source:string,events:Omit<TowerEvent,'seq'>[]){const p=state.player;if(p.invulnerableTicks>0)return;if(p.shieldCharges>0){p.shieldCharges--;p.invulnerableTicks=10;events.push({tick:state.tick,type:'shield-block',data:{source,remaining:p.shieldCharges}});return}p.health=Math.max(0,p.health-amount);p.invulnerableTicks=20;p.state='hurt';state.stats.damageTaken+=amount;events.push({tick:state.tick,type:'player-damage',data:{source,amount,health:p.health}})}
function defeat(state:TowerState,enemy:TowerEnemy,events:Omit<TowerEvent,'seq'>[]){if(!enemy.active)return;enemy.active=false;state.stats.enemiesDefeated++;if(enemy.kind==='guardian')state.stats.guardiansDefeated++;const points=Math.floor((enemy.kind==='guardian'?100:20)*state.build.scoreMultiplierPermille/1000);state.player.score+=points;state.meaningfulEventTick=state.tick;events.push({tick:state.tick,type:'enemy-defeated',data:{id:enemy.id,kind:enemy.kind,points}})}
function spawnProjectile(state:TowerState,owner:'player'|'enemy',sourceId:string,position:{x:number;y:number},facing:-1|1,damage:number,events:Omit<TowerEvent,'seq'>[]){if(state.projectiles.filter(p=>p.active).length>=state.config.maxProjectiles)return;const id=`${sourceId}:projectile:${state.tick}:${state.stats.projectilesFired}`;state.projectiles.push({id,owner,floor:state.floor,position:{...position},velocity:{x:facing*state.config.projectileSpeed,y:0},halfWidth:5000,halfHeight:3500,damage,ttl:80,active:true,hitIds:[]});state.stats.projectilesFired++;events.push({tick:state.tick,type:'projectile-fired',data:{id,owner,sourceId}})}
export function stepTowerCombat(input:TowerState,action:TowerAction,rng:NamedRng){const state=structuredClone(input),events:Omit<TowerEvent,'seq'>[]=[];const p=state.player;if(p.attackCooldown>0)p.attackCooldown--;if(p.abilityCooldown>0)p.abilityCooldown--;
  if(action.attack&&p.attackCooldown===0){p.attackCooldown=state.config.attackCooldownTicks;const reach=state.config.attackReach+state.build.attackReachBonus,candidates=state.enemies.filter(e=>e.active&&e.floor===state.floor&&Math.abs(e.position.y-p.position.y)<=p.halfHeight+e.halfHeight+10000&&((p.facing>0&&e.position.x>=p.position.x)||(p.facing<0&&e.position.x<=p.position.x))&&Math.abs(e.position.x-p.position.x)<=reach).sort((a,b)=>Math.abs(a.position.x-p.position.x)-Math.abs(b.position.x-p.position.x)||a.id.localeCompare(b.id));const enemy=candidates[0];if(enemy){const amount=Math.max(1,state.build.attackDamage);enemy.health-=amount;state.stats.damageDealt+=amount;events.push({tick:state.tick,type:'melee-hit',data:{id:enemy.id,amount,health:enemy.health}});if(enemy.health<=0)defeat(state,enemy,events)}else events.push({tick:state.tick,type:'melee-miss'})}
  if(action.ability&&p.abilityCooldown===0&&state.build.upgradeIds.includes('pulse-shot')){p.abilityCooldown=24;spawnProjectile(state,'player',p.id,p.position,p.facing,state.build.attackDamage,events)}
  for(const enemy of state.enemies.sort((a,b)=>a.id.localeCompare(b.id))){if(!enemy.active||enemy.floor!==state.floor)continue;if(enemy.cooldown>0)enemy.cooldown--;const speed=enemy.kind==='guardian'?1800:enemy.kind==='sentinel'?1200:700;enemy.position.x+=enemy.facing*speed;if(enemy.position.x<=enemy.patrolMinX){enemy.position.x=enemy.patrolMinX;enemy.facing=1}else if(enemy.position.x>=enemy.patrolMaxX){enemy.position.x=enemy.patrolMaxX;enemy.facing=-1}const dx=p.position.x-enemy.position.x;if(enemy.kind!=='sentinel'&&Math.abs(dx)<220000){enemy.facing=dx>=0?1:-1;if(enemy.telegraphUntilTick===0&&enemy.cooldown===0){enemy.telegraphUntilTick=state.tick+8;events.push({tick:state.tick,type:'enemy-telegraph',data:{id:enemy.id}})}else if(enemy.telegraphUntilTick>0&&state.tick>=enemy.telegraphUntilTick){spawnProjectile(state,'enemy',enemy.id,enemy.position,enemy.facing,enemy.damage,events);enemy.telegraphUntilTick=0;enemy.cooldown=enemy.kind==='guardian'?28:42+rng.nextInt(`tower:enemy:fire:${enemy.id}:${state.tick}`,12)}}if(overlap(p,enemy))damagePlayer(state,enemy.damage,enemy.id,events)}
  for(const projectile of state.projectiles.sort((a,b)=>a.id.localeCompare(b.id))){if(!projectile.active)continue;projectile.position.x+=projectile.velocity.x;projectile.position.y+=projectile.velocity.y;projectile.ttl--;if(projectile.ttl<=0||projectile.position.x<-20000||projectile.position.x>state.config.worldWidth+20000){projectile.active=false;continue}if(projectile.owner==='enemy'){if(!projectile.hitIds.includes(p.id)&&overlap(p,projectile)){projectile.hitIds.push(p.id);projectile.active=false;damagePlayer(state,projectile.damage,projectile.id,events)}}else{const enemy=state.enemies.filter(e=>e.active&&!projectile.hitIds.includes(e.id)&&e.floor===state.floor&&overlap(e,projectile)).sort((a,b)=>a.id.localeCompare(b.id))[0];if(enemy){projectile.hitIds.push(enemy.id);projectile.active=false;enemy.health-=projectile.damage;state.stats.damageDealt+=projectile.damage;events.push({tick:state.tick,type:'projectile-hit',data:{id:enemy.id,amount:projectile.damage}});if(enemy.health<=0)defeat(state,enemy,events)}}}
  const radius=state.build.pickupRadius;for(const pickup of state.pickups.sort((a,b)=>a.id.localeCompare(b.id))){if(pickup.collected||pickup.floor!==state.floor)continue;if(Math.abs(pickup.position.x-p.position.x)<=p.halfWidth+8000+radius&&Math.abs(pickup.position.y-p.position.y)<=p.halfHeight+8000+radius){pickup.collected=true;state.stats.pickupsCollected++;if(pickup.kind==='health')p.health=Math.min(p.maxHealth,p.health+pickup.value);else if(pickup.kind==='stamina')p.stamina=Math.min(p.maxStamina,p.stamina+pickup.value);else p.score+=Math.floor(pickup.value*state.build.scoreMultiplierPermille/1000);events.push({tick:state.tick,type:'pickup-collected',data:{id:pickup.id,kind:pickup.kind,value:pickup.value}})}}
  state.projectiles=state.projectiles.filter(x=>x.active).slice(-state.config.maxProjectiles);return{state,events}}
