import type{GameLifecycle,TrafficConfig,TrafficRunResult}from '../../../../packages/game-contracts/src/index';
export type TrafficAxis='ns'|'ew';
export type TrafficDirection='north'|'east'|'south'|'west';
export type VehicleKind='car'|'bus'|'emergency';
export interface TrafficSignal{axis:TrafficAxis;changedAtTick:number;decisionCount:number;reason:string}
export interface TrafficIntersection{id:string;x:number;y:number;incoming:string[];outgoing:string[];signal:TrafficSignal}
export interface TrafficLane{id:string;from:string;to:string;axis:TrafficAxis;direction:TrafficDirection;length:number;roadClass:'local'|'arterial'|'ring';baseCost:number;blockedUntilTick:number}
export interface TrafficCity{schemaVersion:1;width:number;height:number;profile:string;intersections:TrafficIntersection[];lanes:TrafficLane[];gateways:string[];features:{arterialRow:number;arterialColumn:number;ringEnabled:boolean}}
export interface TrafficVehicle{id:string;kind:VehicleKind;origin:string;destination:string;route:string[];laneIndex:number;cell:number;spawnedTick:number;waitTicks:number;travelTicks:number;replans:number;lastRerouteTick:number}
export interface PendingDemand{id:string;origin:string;destination:string;kind:VehicleKind;createdTick:number;attempts:number}
export type TrafficWave='calm'|'rush'|'surge'|'incident'|'recovery';
export interface TrafficAiState{mode:'fixed-cycle'|'adaptive'|'fallback';goal:string;intent:string;reason:string;confidence:'low'|'medium'|'high';decisions:number;routeExpansions:number;fallbackCount:number;lastDecisionTick:number}
export interface TrafficMetrics{spawned:number;completedTrips:number;droppedDemand:number;collisions:number;totalWaitTicks:number;totalTravelTicks:number;maxActive:number;maxQueue:number;gridlockTicks:number;mobilityScore:number;meaningfulEvents:number;peakGridlockTicks:number;busesCompleted:number;emergencyCompleted:number}
export interface TrafficIncident{id:string;laneId:string;startedTick:number;clearsAtTick:number;reason:'collision-cleanup'|'roadworks'|'signal-fault';active:boolean}
export interface TrafficAudienceCommand{id:string;effectId:string;viewerRef:string;source:string;receivedTick:number;scheduledTick:number;expiresAtTick:number;payload:Record<string,unknown>}
export interface TrafficInfluenceRecord{id:string;effectId:string;tick:number;status:'queued'|'applied'|'rejected'|'expired'|'reversed'|'refused';applicationCount:number;source?:string;reason?:string;targetCommandId?:string}
export interface TrafficAudienceState{enabled:boolean;providerStatus:'healthy'|'degraded'|'offline';queued:TrafficAudienceCommand[];applied:Record<string,TrafficInfluenceRecord>;seenIds:string[];cooldowns:Record<string,number>;rateWindows:Record<string,{startTick:number;count:number}>;axisBias:TrafficAxis|null;axisBiasUntilTick:number;transitPriorityUntilTick:number;challengeMultiplierPermille:number;challengeUntilTick:number;themeId:'neon'|'night'|'day';themeUntilTick:number;recordCategory:'standard'|'audience-influenced'}
export interface TrafficEvent{seq:number;tick:number;type:string;data:Record<string,string|number|boolean|null>}
export interface TrafficState{schemaVersion:1;deterministicVersion:string;runId:string;seed:string;runIndex:number;tick:number;lifecycle:GameLifecycle;config:TrafficConfig;city:TrafficCity;vehicles:TrafficVehicle[];pendingDemand:PendingDemand[];nextVehicleId:number;nextDemandId:number;wave:TrafficWave;ai:TrafficAiState;incidents:TrafficIncident[];audience:TrafficAudienceState;metrics:TrafficMetrics;result?:TrafficRunResult;intermissionRemaining:number;meaningfulEventTick:number}
