import{checksum}from '../../../../packages/replay/src/index';import{applyRelic,RELICS}from '../content/catalogue';import type{DungeonAudienceInput,DungeonInfluenceState,DungeonRouteModifier,DungeonState}from '../state/types';import type{NamedRng}from '../../../../packages/seeded-rng/src/index';
export type AudienceSubmitResult={accepted:boolean;reason:'accepted'|'duplicate'|'disabled'|'stale'|'invalid'|'moderated'|'cooldown'|'cap'|'vote-closed'};
const ROUTES=new Set<DungeonRouteModifier>(['warded','riches','trial']);const THEMES=new Set(['default','ember','frost','violet']);const EFFECTS=new Set(['shield','theme','route','reveal','elite','challenge']);
export function createDungeonInfluenceState():DungeonInfluenceState{return{enabled:true,processedIds:[],ledger:[],queued:[],cooldowns:{},effectCounts:{},themeId:'default',revealUntilTick:0,pressure:0,nextRouteChoice:null,currentRouteModifier:null,vote:null}}
export function normalizeDungeonAudienceInput(raw:any):{ok:true;input:DungeonAudienceInput}|{ok:false;reason:string}{if(!raw||typeof raw!=='object'||raw.moderation!=='approved')return{ok:false,reason:'moderated'};const id=String(raw.providerEventId??'').trim();const actor=String(raw.actorId??'').trim();if(!id||id.length>96||!actor||actor.length>160||!Number.isInteger(raw.receivedTick)||raw.receivedTick<0)return{ok:false,reason:'invalid'};const source=['chat','paid','membership','operator'].includes(raw.source)?raw.source:'chat';const kind=raw.kind==='vote'?'vote':raw.kind==='effect'?'effect':null;if(!kind)return{ok:false,reason:'invalid'};const effectId=raw.effectId===undefined?undefined:String(raw.effectId);if(effectId&&!EFFECTS.has(effectId))return{ok:false,reason:'invalid'};return{ok:true,input:{providerEventId:id,actorToken:checksum({actor}).slice(0,16),source,kind,receivedTick:raw.receivedTick,effectId:effectId as any,optionId:raw.optionId===undefined?undefined:String(raw.optionId).slice(0,48),weight:Number.isFinite(raw.weight)?Math.max(1,Math.floor(raw.weight)):1}}}
function ledger(state:DungeonState,entry:DungeonInfluenceState['ledger'][number]){state.influence.ledger.push(entry);if(state.influence.ledger.length>128)state.influence.ledger.splice(0,state.influence.ledger.length-128)}
export function submitDungeonAudience(state:DungeonState,input:DungeonAudienceInput):AudienceSubmitResult{const i=state.influence;if(!i.enabled)return{accepted:false,reason:'disabled'};if(i.processedIds.includes(input.providerEventId))return{accepted:false,reason:'duplicate'};if(input.receivedTick>state.tick+5||state.tick-input.receivedTick>2400)return{accepted:false,reason:'stale'};if(i.queued.length>=32)return{accepted:false,reason:'cap'};i.processedIds.push(input.providerEventId);if(i.processedIds.length>256)i.processedIds.splice(0,i.processedIds.length-256);i.queued.push(input);ledger(state,{providerEventId:input.providerEventId,effectId:input.effectId,optionId:input.optionId,status:'queued',tick:state.tick,reversible:input.effectId==='theme'});return{accepted:true,reason:'accepted'}}
function setLedgerStatus(state:DungeonState,id:string,status:DungeonInfluenceState['ledger'][number]['status']){const entry=[...state.influence.ledger].reverse().find(e=>e.providerEventId===id);if(entry)entry.status=status}
function applyEffect(state:DungeonState,input:DungeonAudienceInput){const i=state.influence,id=input.effectId;if(!id)return false;const count=i.effectCounts[id]??0;if(count>=8)return false;const until=i.cooldowns[id]??0;if(state.tick<until)return false;i.effectCounts[id]=count+1;i.cooldowns[id]=state.tick+30;if(id==='shield'){state.hero.shield=Math.min(12,state.hero.shield+3);return true}if(id==='theme'){if(!input.optionId||!THEMES.has(input.optionId))return false;i.themeId=input.optionId;return true}if(id==='route'){if(!input.optionId||!ROUTES.has(input.optionId as DungeonRouteModifier))return false;i.nextRouteChoice=input.optionId as DungeonRouteModifier;return true}if(id==='reveal'){i.revealUntilTick=Math.max(i.revealUntilTick,state.tick+120);return true}if(id==='elite'){i.nextRouteChoice='trial';return true}if(id==='challenge'){i.pressure=Math.min(5,i.pressure+1);return true}return false}
function tallyVote(state:DungeonState,rng:NamedRng){const vote=state.influence.vote;if(!vote||vote.closed||state.tick<vote.endTick)return null;vote.closed=true;const tally:Record<string,number>={};for(const ballot of Object.values(vote.ballots))tally[ballot.optionId]=(tally[ballot.optionId]??0)+ballot.weight;const best=Math.max(0,...Object.values(tally));if(best===0){state.influence.vote=null;return null}const tied=vote.options.filter(option=>(tally[option]??0)===best).sort();const winner=tied[rng.nextInt('dungeon.audience.vote-tie',tied.length)];state.rewardChoices=[winner];state.influence.vote=null;return winner}
export function applyQueuedDungeonAudience(state:DungeonState,rng:NamedRng){const events:Array<{type:string;message?:string;value?:number}>=[];for(const input of state.influence.queued.splice(0,8)){if(input.kind==='vote'){const vote=state.influence.vote;if(!vote||vote.closed||!input.optionId||!vote.options.includes(input.optionId)){setLedgerStatus(state,input.providerEventId,'rejected');continue}const weight=input.source==='paid'||input.source==='membership'?Math.min(3,input.weight):1;if(!vote.ballots[input.actorToken])vote.ballots[input.actorToken]={optionId:input.optionId,weight};setLedgerStatus(state,input.providerEventId,'voted');events.push({type:'audience.vote-recorded',message:'A bounded relic vote was recorded.'});continue}const ok=applyEffect(state,input);setLedgerStatus(state,input.providerEventId,ok?'applied':'rejected');events.push({type:ok?'audience.effect-applied':'audience.effect-rejected',message:ok?`Audience effect ${input.effectId} applied within limits.`:'Audience effect was not eligible.'})}const winner=tallyVote(state,rng);if(winner)events.push({type:'audience.vote-resolved',message:`Audience relic vote selected ${RELICS[winner]?.name??winner}.`});if(state.influence.pressure>0&&state.tick%120===0)state.influence.pressure--;return events}
export function openDungeonRelicVote(state:DungeonState,durationTicks:number){if(state.lifecycle!=='chapter-result'||state.rewardChoices.length<2||!Number.isInteger(durationTicks)||durationTicks<1)return{opened:false};state.influence.vote={openedTick:state.tick,endTick:state.tick+Math.min(600,durationTicks),options:[...state.rewardChoices].slice(0,3),ballots:{},closed:false};return{opened:true}}
export function reverseDungeonAudience(state:DungeonState,providerEventId:string,role:string){if(role!=='operator')return{reversed:false,reason:'forbidden'};const entry=[...state.influence.ledger].reverse().find(e=>e.providerEventId===providerEventId);if(!entry||entry.status!=='applied'||!entry.reversible)return{reversed:false,reason:'not-reversible'};if(entry.effectId==='theme')state.influence.themeId='default';entry.status='reversed';return{reversed:true}}
export function applyRouteModifierAtFloorStart(state:DungeonState){const route=state.influence.nextRouteChoice;state.influence.currentRouteModifier=route;state.influence.nextRouteChoice=null;if(route==='warded')state.hero.shield=Math.min(12,state.hero.shield+4);if(route==='trial'){const occupied=new Set(state.enemies.map(e=>e.cell));const cell=state.floor.tiles.map((v,i)=>v===1?i:-1).filter(c=>c>=0&&!occupied.has(c)&&c!==state.floor.entrance&&c!==state.floor.sigil&&c!==state.floor.gate).sort((a,b)=>b-a)[0];if(cell!==undefined)state.enemies.push({id:`audience-trial-${state.floorNumber}`,kind:'bone-warden',cell,hp:9,maxHp:9,attack:3,armour:1,cooldown:0,telegraph:'melee',phase:1,alive:true})}return route}
export function emergencyDisableDungeonAudience(state:DungeonState){state.influence.enabled=false;state.influence.queued=[];state.influence.vote=null;state.influence.themeId='default';state.influence.revealUntilTick=0;state.influence.pressure=0}
