import{NamedRng}from'../../../../packages/seeded-rng/src/index';import type{RngSnapshot}from'../../../../packages/seeded-rng/src/index';import{parseCivilizationConfig}from'../config/schema';import type{CivilizationConfig}from'../config/schema';import{createInitialCivilizationState}from'../index';import{decideCivilizationAction}from'../ai/policy';import{applyCivilizationAction}from'../rules/step';import type{CivilizationEvent,CivilizationState}from'../state/types';
export interface CivilizationSignals{tier:string;renown:number;population:number;stability:number;foodRunway:number;danger:number;progress:number;meaningfulEventAge:number;lifecycle:string}
export class CivilizationRuntime{state:CivilizationState;rng:NamedRng;private events:CivilizationEvent[]=[];private nextSeq:number;
  private constructor(public config:CivilizationConfig,public seed:string,state?:CivilizationState,rng?:NamedRng,nextSeq=0){this.rng=rng??NamedRng.fromSeed(seed);this.state=state??createInitialCivilizationState(config,seed,`run-${seed}`,this.rng);this.nextSeq=nextSeq;if(!state)this.emit('initialized',{seed})}
  static create(config:Partial<CivilizationConfig>,seed:string){return new CivilizationRuntime(parseCivilizationConfig(config),seed)}
  static restore(config:CivilizationConfig,seed:string,state:CivilizationState,rngSnapshot:RngSnapshot,nextSeq:number){return new CivilizationRuntime(config,seed,state,NamedRng.restore(rngSnapshot),nextSeq)}
  private emit(type:string,data?:Record<string,unknown>){this.events.push({seq:this.nextSeq++,tick:this.state.tick,type,data});if(this.events.length>this.config.liveEventCap)this.events.splice(0,this.events.length-this.config.liveEventCap)}
  step(){if(this.state.lifecycle==='result'){this.state.lifecycle='intermission';this.emit('intermission',{remaining:this.state.intermissionRemaining});return this.state}
    if(this.state.lifecycle==='intermission'){this.state.intermissionRemaining--;if(this.state.intermissionRemaining<=0)this.restart(`${this.seed}:restart:${this.state.tick}`);return this.state}
    const decision=decideCivilizationAction(this.state);const previousGoal=this.state.ai.goal;this.state.ai.goal=decision.intent.goal;this.state.ai.actionKey=decision.action.key;this.state.ai.pressure=decision.intent.pressure;this.state.ai.confidence=decision.intent.confidence;this.state.ai.fallbackUsed=decision.intent.fallbackUsed;this.state.ai.decisions++;if(previousGoal!==decision.intent.goal){this.state.ai.planChanges++;this.state.ai.lastPlanChangeReason=decision.intent.planChangeReason}
    const out=applyCivilizationAction(this.state,decision.action,this.rng);this.state=out.state;for(const e of out.events)this.emit(e.type,e.data);this.emit('ai-intent',{goal:this.state.ai.goal,action:this.state.ai.actionKey,pressure:this.state.ai.pressure});return this.state}
  restart(seed=this.seed){this.seed=seed;this.rng=NamedRng.fromSeed(seed);this.state=createInitialCivilizationState(this.config,seed,`run-${seed}`,this.rng);this.emit('restart',{seed});return this.state}
  drainEvents(limit=10000){if(!Number.isInteger(limit)||limit<0)throw new RangeError('limit');return this.events.splice(0,Math.min(limit,this.events.length))}
  getNextEventSequence(){return this.nextSeq}
  signals():CivilizationSignals{const consumption=Math.max(1,Math.ceil(this.state.population.total/6));return{tier:this.state.progression.tier,renown:this.state.progression.renown,population:this.state.population.total,stability:this.state.stability,foodRunway:this.state.resources.food/consumption,danger:this.state.population.starvationDays>0||this.state.stability<25?1:0,progress:Math.min(1,this.state.progression.renown/this.config.legendaryRenown),meaningfulEventAge:this.state.tick-this.state.progression.lastMeaningfulTick,lifecycle:this.state.lifecycle}}
}
