import{isAntEffectId}from './catalogue';import type{AntAudienceInput,AntGatewayDecision,AntGatewayOptions}from './types';
const DEFAULTS:AntGatewayOptions={maxEventAgeTicks:120,maxFutureTicks:5,perViewerWindowTicks:60,perViewerLimit:4,globalWindowTicks:60,globalLimit:240,maxSeen:4096};
const TOKEN=/^[A-Za-z0-9_-]{8,64}$/;const ID=/^[A-Za-z0-9:_-]{3,96}$/;
export class AntAudienceGateway{
 private readonly options:AntGatewayOptions;private readonly seen=new Set<string>();private readonly seenOrder:string[]=[];private readonly viewerTicks=new Map<string,number[]>();private globalTicks:number[]=[];
 constructor(options:Partial<AntGatewayOptions>={}){this.options={...DEFAULTS,...options};for(const value of Object.values(this.options))if(!Number.isInteger(value)||value<1)throw new RangeError('gateway-options')}
 private reject(reason:AntGatewayDecision['reason']):AntGatewayDecision{return{status:'rejected',reason}}
 accept(value:AntAudienceInput):AntGatewayDecision{
  if(!value||value.schemaVersion!==1)return this.reject('schema');if(!['youtube','twitch','test'].includes(value.provider))return this.reject('provider');if(!value.authenticated)return this.reject('authentication');if(value.moderation==='unavailable')return this.reject('moderation-unavailable');if(value.moderation!=='pass')return this.reject('moderation-reject');if(!value.regionAllowed)return this.reject('region');if(!ID.test(value.providerEventId))return this.reject('event-id');if(!ID.test(value.idempotencyKey))return this.reject('idempotency-key');if(!TOKEN.test(value.viewerToken))return this.reject('viewer-token');if(!Number.isInteger(value.occurredTick)||!Number.isInteger(value.receivedTick)||value.occurredTick<0||value.receivedTick<0)return this.reject('tick');if(value.occurredTick>value.receivedTick+this.options.maxFutureTicks)return this.reject('future');if(value.receivedTick-value.occurredTick>this.options.maxEventAgeTicks)return this.reject('stale');if(value.kind!=='vote')return this.reject('kind');if(!isAntEffectId(value.optionId))return this.reject('effect');if(!Number.isInteger(value.entitlementWeight)||value.entitlementWeight<1||value.entitlementWeight>3)return this.reject('entitlement-weight');if(this.seen.has(value.idempotencyKey)||this.seen.has(`${value.provider}:${value.providerEventId}`))return this.reject('duplicate');
  const viewerCutoff=value.receivedTick-this.options.perViewerWindowTicks,viewer=(this.viewerTicks.get(value.viewerToken)??[]).filter(tick=>tick>viewerCutoff);if(viewer.length>=this.options.perViewerLimit)return this.reject('viewer-rate');const globalCutoff=value.receivedTick-this.options.globalWindowTicks;this.globalTicks=this.globalTicks.filter(tick=>tick>globalCutoff);if(this.globalTicks.length>=this.options.globalLimit)return this.reject('global-rate');
  viewer.push(value.receivedTick);this.viewerTicks.set(value.viewerToken,viewer);while(this.viewerTicks.size>this.options.maxSeen){const oldest=this.viewerTicks.keys().next().value as string|undefined;if(!oldest||oldest===value.viewerToken)break;this.viewerTicks.delete(oldest)}this.globalTicks.push(value.receivedTick);for(const key of[value.idempotencyKey,`${value.provider}:${value.providerEventId}`]){this.seen.add(key);this.seenOrder.push(key)}while(this.seenOrder.length>this.options.maxSeen){const oldest=this.seenOrder.shift();if(oldest)this.seen.delete(oldest)}return{status:'accepted',reason:'accepted',input:Object.freeze({...value})}
 }
 snapshot(){return Object.freeze({seenCount:this.seen.size,viewerBucketCount:this.viewerTicks.size,globalEventCount:this.globalTicks.length,limits:Object.freeze({...this.options})})}
}
