import type{Direction,SnakeAction}from '../../../../packages/game-contracts/src/index';import type{SnakeState}from '../state/types';import{DIRECTIONS,isHazardActiveAt,isLegalAction,resolveDestination}from '../rules/step';import{chooseFallbackAction}from './fallback';
export type StrategicMode='seek-food'|'preserve-space'|'follow-tail'|'cycle-fill'|'escape-hazard'|'replan'|'fallback-survival';
export interface DecisionIntent{mode:StrategicMode;confidence:number;explanation:string;target:number|null;fallbackUsed:boolean;nodeExpansions:number}
export interface CandidateTrace{direction:Direction;reachable:number;foodDistance:number;tailReachable:boolean;bottleneck:boolean;safe:boolean;score:number}
export interface ProductionDecision{action:SnakeAction|null;intent:DecisionIntent;candidates:CandidateTrace[]}
function blocked(s:SnakeState,allowTail=true){const xs=allowTail?s.snake.body.slice(0,-1):s.snake.body;const activeHazards=s.hazards.filter(h=>isHazardActiveAt(s,h,s.tick+1));return new Set([...xs,...s.obstacles,...activeHazards])}
function neighbors(s:SnakeState,i:number,b:Set<number>){const w=s.config.width,h=s.config.height,x=i%w,y=Math.floor(i/w),out:number[]=[];for(const[nx,ny]of[[x,y-1],[x+1,y],[x,y+1],[x-1,y]]){if(nx<0||ny<0||nx>=w||ny>=h)continue;let n=ny*w+nx;if(s.portalPairs[n]!==undefined)n=s.portalPairs[n];if(!b.has(n))out.push(n)}return out}
function flood(s:SnakeState,start:number,b:Set<number>){const q=[start],seen=new Set([start]);while(q.length){const i=q.shift()!;for(const n of neighbors(s,i,b))if(!seen.has(n)){seen.add(n);q.push(n)}}return seen.size}
function distance(s:SnakeState,start:number,target:number|null,b:Set<number>){if(target===null)return 1e9;const q:[number,number][]=[[start,0]],seen=new Set([start]);while(q.length){const[i,d]=q.shift()!;if(i===target)return d;for(const n of neighbors(s,i,b))if(!seen.has(n)){seen.add(n);q.push([n,d+1])}}return 1e9}
function tailReachable(s:SnakeState,start:number,b:Set<number>){const tail=s.snake.body.at(-1)!;return distance(s,start,tail,b)<1e9}
export function chooseProductionAction(s:SnakeState):ProductionDecision{const occupancy=s.snake.body.length/(s.config.width*s.config.height-s.obstacles.length);const longHorizon:StrategicMode=occupancy>=0.55?((s.config.profile==='open'&&(s.config.width%2===0||s.config.height%2===0))?'cycle-fill':'preserve-space'):'follow-tail';const traces:CandidateTrace[]=[];let nodes=0;for(const direction of DIRECTIONS){if(!isLegalAction(s,{direction}))continue;const dest=resolveDestination(s,direction).index,b=blocked(s,true);b.delete(dest);const reachable=flood(s,dest,b);nodes+=reachable;const foodDistance=distance(s,dest,s.food,b);const tail=tailReachable(s,dest,b);const bottleneck=neighbors(s,dest,b).length<=1;const required=Math.min(s.snake.body.length+2,Math.max(4,Math.floor((s.config.width*s.config.height-s.obstacles.length)*0.15)));const safe=reachable>=required&&(tail||occupancy<0.35);let score=reachable*20-(foodDistance<1e9?foodDistance*8:500)+(tail?120:0)-(bottleneck?180:0);if(dest===s.food)score+=safe?2200:-5000;if(!safe)score-=10000;traces.push({direction,reachable,foodDistance,tailReachable:tail,bottleneck,safe,score})}
let viable=traces.filter(t=>t.safe).sort((a,b)=>b.score-a.score||DIRECTIONS.indexOf(a.direction)-DIRECTIONS.indexOf(b.direction));let mode:StrategicMode='seek-food';if(occupancy>=0.55)mode=longHorizon;else if(!viable.some(v=>v.foodDistance<1e9))mode='follow-tail';if((s.ai?.repeatCount??0)>=6&&viable.length>1){mode='replan';viable=[viable[1],viable[0],...viable.slice(2)]}
if(viable.length){const best=viable[0];if(best.foodDistance>2&&mode==='seek-food')mode='preserve-space';return{action:{direction:best.direction},intent:{mode,confidence:Math.max(10,Math.min(99,50+Math.floor((best.reachable/Math.max(1,s.config.width*s.config.height-s.obstacles.length))*49))),explanation:`${mode}: reachable=${best.reachable}, foodDistance=${best.foodDistance}, tail=${best.tailReachable}`,target:s.food,fallbackUsed:false,nodeExpansions:nodes},candidates:traces}}
const fallback=chooseFallbackAction(s);const degradedMode=occupancy>=0.55?longHorizon:'fallback-survival';return{action:fallback,intent:{mode:degradedMode,confidence:5,explanation:`${degradedMode}: no candidate passed hard survivability constraints; deterministic fallback engaged.`,target:s.food,fallbackUsed:true,nodeExpansions:nodes},candidates:traces}}
export function safeProductionDecision(s:SnakeState,policy:(state:SnakeState)=>ProductionDecision=chooseProductionAction):ProductionDecision{try{return policy(s)}catch(error){const fallback=chooseFallbackAction(s);return{action:fallback,intent:{mode:'fallback-survival',confidence:1,explanation:`Planner exception degraded safely: ${error instanceof Error?error.message:'unknown planner error'}`,target:s.food,fallbackUsed:true,nodeExpansions:0},candidates:[]}}}
