import type{DungeonConfig}from '../../../../packages/game-contracts/src/index';
import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import type{DungeonEnemy,DungeonEnemyKind,DungeonFloor,DungeonState}from '../state/types';
export type RelicFamily='assault'|'guard'|'arcane'|'exploration'|'fortune';
export interface RelicDefinition{id:string;name:string;description:string;priority:number;family:RelicFamily;apply:(state:DungeonState)=>void}
export const RELICS:Record<string,RelicDefinition>={
'ember-edge':{id:'ember-edge',name:'Ember Edge',description:'+2 attack',priority:90,family:'assault',apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+2)}},
'ward-stone':{id:'ward-stone',name:'Ward Stone',description:'+4 max health and +1 armour',priority:85,family:'guard',apply:s=>{s.hero.maxHp=Math.min(48,s.hero.maxHp+4);s.hero.hp=Math.min(s.hero.maxHp,s.hero.hp+4);s.hero.armour=Math.min(8,s.hero.armour+1)}},
'swift-sigil':{id:'swift-sigil',name:'Swift Sigil',description:'+2 maximum energy',priority:65,family:'arcane',apply:s=>{s.hero.maxEnergy=Math.min(14,s.hero.maxEnergy+2);s.hero.energy=s.hero.maxEnergy}},
'lantern-of-depth':{id:'lantern-of-depth',name:'Lantern of Depth',description:'+1 vision radius',priority:55,family:'exploration',apply:s=>{s.hero.vision=Math.min(8,s.hero.vision+1)}},
'phoenix-thread':{id:'phoenix-thread',name:'Phoenix Thread',description:'+1 potion and +2 max health',priority:70,family:'guard',apply:s=>{s.hero.potions=Math.min(4,s.hero.potions+1);s.hero.maxHp=Math.min(48,s.hero.maxHp+2);s.hero.hp=Math.min(s.hero.maxHp,s.hero.hp+2)}},
'gilded-rune':{id:'gilded-rune',name:'Gilded Rune',description:'+15 gold',priority:35,family:'fortune',apply:s=>{s.hero.gold=Math.min(999,s.hero.gold+15)}},
'echo-guard':{id:'echo-guard',name:'Echo Guard',description:'+3 shield now and on every floor',priority:75,family:'guard',apply:s=>{s.hero.shield=Math.min(12,s.hero.shield+3)}},
'hunter-mark':{id:'hunter-mark',name:'Hunter Mark',description:'+1 attack and +1 vision',priority:80,family:'exploration',apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+1);s.hero.vision=Math.min(8,s.hero.vision+1)}},
'graveglass-prism':{id:'graveglass-prism',name:'Graveglass Prism',description:'+2 attack and +1 vision',priority:88,family:'assault',apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+2);s.hero.vision=Math.min(8,s.hero.vision+1)}},
'storm-vessel':{id:'storm-vessel',name:'Storm Vessel',description:'+4 maximum energy',priority:82,family:'arcane',apply:s=>{s.hero.maxEnergy=Math.min(14,s.hero.maxEnergy+4);s.hero.energy=s.hero.maxEnergy}},
'iron-covenant':{id:'iron-covenant',name:'Iron Covenant',description:'+2 armour and +2 shield',priority:86,family:'guard',apply:s=>{s.hero.armour=Math.min(8,s.hero.armour+2);s.hero.shield=Math.min(12,s.hero.shield+2)}},
'shadowstep-rune':{id:'shadowstep-rune',name:'Shadowstep Rune',description:'+1 attack and +2 maximum energy',priority:78,family:'assault',apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+1);s.hero.maxEnergy=Math.min(14,s.hero.maxEnergy+2);s.hero.energy=s.hero.maxEnergy}},
'depth-tithe':{id:'depth-tithe',name:'Depth Tithe',description:'+25 gold and +1 attack',priority:62,family:'fortune',apply:s=>{s.hero.gold=Math.min(999,s.hero.gold+25);s.hero.attack=Math.min(18,s.hero.attack+1)}},
'blood-ward':{id:'blood-ward',name:'Blood Ward',description:'+5 shield and +1 attack',priority:84,family:'guard',apply:s=>{s.hero.shield=Math.min(12,s.hero.shield+5);s.hero.attack=Math.min(18,s.hero.attack+1)}},
'seer-lens':{id:'seer-lens',name:'Seer Lens',description:'+2 vision and +2 maximum energy',priority:76,family:'arcane',apply:s=>{s.hero.vision=Math.min(8,s.hero.vision+2);s.hero.maxEnergy=Math.min(14,s.hero.maxEnergy+2);s.hero.energy=s.hero.maxEnergy}},
'cartographers-oath':{id:'cartographers-oath',name:"Cartographer's Oath",description:'+2 vision, +10 gold and +1 potion',priority:68,family:'exploration',apply:s=>{s.hero.vision=Math.min(8,s.hero.vision+2);s.hero.gold=Math.min(999,s.hero.gold+10);s.hero.potions=Math.min(4,s.hero.potions+1)}}
};
export function relicBuildProfile(relicIds:string[]){const families:Record<RelicFamily,number>={assault:0,guard:0,arcane:0,exploration:0,fortune:0};for(const id of relicIds){const relic=RELICS[id];if(relic)families[relic.family]++}const ranked=(Object.entries(families)as Array<[RelicFamily,number]>).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));return{families,total:Object.values(families).reduce((sum,value)=>sum+value,0),dominant:ranked[0][1]>0?ranked[0][0]:'none' as RelicFamily|'none'}}
export function scoreRelicForState(state:DungeonState,relicId:string){const relic=RELICS[relicId];if(!relic)return-100000;const profile=relicBuildProfile(state.hero.relics);let score=relic.priority;if(profile.dominant===relic.family)score+=12;if(relic.family==='guard'&&state.hero.hp*2<state.hero.maxHp)score+=30;if(relic.family==='assault'&&state.hero.attack<8)score+=12;if(relic.family==='arcane'&&(state.hero.maxEnergy<10||state.hero.energy*2<state.hero.maxEnergy))score+=14;if(relic.family==='exploration'&&state.hero.vision<5)score+=12;if(relic.family==='fortune'&&state.hero.gold<12)score+=8;return score}
export function applyRelic(state:DungeonState,relicId:string){if(state.hero.relics.length>=state.config.maxRelics||state.hero.relics.includes(relicId)||!RELICS[relicId])return false;state.hero.relics.push(relicId);RELICS[relicId].apply(state);return true}
export function chooseRelicCandidates(state:DungeonState,rng:NamedRng,count=3){const pool=Object.keys(RELICS).filter(id=>!state.hero.relics.includes(id));const candidates:string[]=[];while(pool.length&&candidates.length<count){const index=rng.nextInt('rewards-v1:relic-choice',pool.length);candidates.push(pool.splice(index,1)[0])}return candidates}
const stats:Record<DungeonEnemyKind,{hp:number;attack:number;armour:number}>={'mireling':{hp:3,attack:1,armour:0},'bone-warden':{hp:5,attack:1,armour:1},'ember-seer':{hp:4,attack:1,armour:0},'void-hound':{hp:4,attack:1,armour:0},'reliquary-mimic':{hp:6,attack:2,armour:0},'chapter-boss':{hp:14,attack:2,armour:1}};
function createEnemy(id:string,kind:DungeonEnemyKind,cell:number,floorNumber:number):DungeonEnemy{const base=stats[kind],scale=Math.floor((floorNumber-1)/5);const hp=base.hp+scale*(kind==='chapter-boss'?4:1);return{id,kind,cell,hp,maxHp:hp,attack:base.attack+Math.floor(scale/2),armour:Math.min(4,base.armour+Math.floor(scale/3)),cooldown:0,telegraph:null,phase:1,alive:true}}
export function spawnFloorEncounters(floor:DungeonFloor,floorNumber:number,config:DungeonConfig,rng:NamedRng):DungeonEnemy[]{const excluded=new Set([floor.entrance,floor.sigil,floor.shrine,floor.chest]);const candidates=floor.tiles.map((tile,cell)=>tile===1&&!excluded.has(cell)?cell:-1).filter(cell=>cell>=0&&cell!==floor.gate);const chapterBoss=floorNumber%config.chapterLength===0;const result:DungeonEnemy[]=[];result.push(createEnemy(chapterBoss?'boss-0':'guardian-0',chapterBoss?'chapter-boss':'bone-warden',floor.gate,floorNumber));const desired=Math.min(config.maxEnemies,Math.max(2,2+Math.floor(floorNumber/2)));const kinds:DungeonEnemyKind[]=['mireling','ember-seer','void-hound','reliquary-mimic'];while(result.length<desired&&candidates.length){const ci=rng.nextInt('encounters-v1:cell',candidates.length);const cell=candidates.splice(ci,1)[0];const kind=kinds[(result.length-1+rng.nextInt('encounters-v1:kind',kinds.length))%kinds.length];result.push(createEnemy(`enemy-${result.length}`,kind,cell,floorNumber))}return result.sort((a,b)=>a.id.localeCompare(b.id))}
