import type{DungeonConfig}from '../../../../packages/game-contracts/src/index';
import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import type{DungeonEnemy,DungeonEnemyKind,DungeonFloor,DungeonState}from '../state/types';
export interface RelicDefinition{id:string;name:string;description:string;priority:number;apply:(state:DungeonState)=>void}
export const RELICS:Record<string,RelicDefinition>={'ember-edge':{id:'ember-edge',name:'Ember Edge',description:'+2 attack',priority:90,apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+2)}},'ward-stone':{id:'ward-stone',name:'Ward Stone',description:'+4 max health and +1 armour',priority:85,apply:s=>{s.hero.maxHp=Math.min(48,s.hero.maxHp+4);s.hero.hp=Math.min(s.hero.maxHp,s.hero.hp+4);s.hero.armour=Math.min(8,s.hero.armour+1)}},'swift-sigil':{id:'swift-sigil',name:'Swift Sigil',description:'+2 maximum energy',priority:65,apply:s=>{s.hero.maxEnergy=Math.min(14,s.hero.maxEnergy+2);s.hero.energy=s.hero.maxEnergy}},'lantern-of-depth':{id:'lantern-of-depth',name:'Lantern of Depth',description:'+1 vision radius',priority:55,apply:s=>{s.hero.vision=Math.min(8,s.hero.vision+1)}},'phoenix-thread':{id:'phoenix-thread',name:'Phoenix Thread',description:'+1 potion capacity reward',priority:70,apply:s=>{s.hero.potions=Math.min(4,s.hero.potions+1)}},'gilded-rune':{id:'gilded-rune',name:'Gilded Rune',description:'+15 gold',priority:35,apply:s=>{s.hero.gold=Math.min(999,s.hero.gold+15)}},'echo-guard':{id:'echo-guard',name:'Echo Guard',description:'+3 shield on every floor',priority:75,apply:s=>{s.hero.shield=Math.min(12,s.hero.shield+3)}},'hunter-mark':{id:'hunter-mark',name:'Hunter Mark',description:'+1 attack and +1 vision',priority:80,apply:s=>{s.hero.attack=Math.min(18,s.hero.attack+1);s.hero.vision=Math.min(8,s.hero.vision+1)}}};
export function applyRelic(state:DungeonState,relicId:string){if(state.hero.relics.length>=state.config.maxRelics||state.hero.relics.includes(relicId)||!RELICS[relicId])return false;state.hero.relics.push(relicId);RELICS[relicId].apply(state);return true}
export function chooseRelicCandidates(state:DungeonState,rng:NamedRng,count=3){const pool=Object.keys(RELICS).filter(id=>!state.hero.relics.includes(id));const candidates:string[]=[];while(pool.length&&candidates.length<count){const index=rng.nextInt('rewards-v1:relic-choice',pool.length);candidates.push(pool.splice(index,1)[0])}return candidates}
const stats:Record<DungeonEnemyKind,{hp:number;attack:number;armour:number}>={'mireling':{hp:3,attack:1,armour:0},'bone-warden':{hp:5,attack:1,armour:1},'ember-seer':{hp:4,attack:1,armour:0},'void-hound':{hp:4,attack:1,armour:0},'reliquary-mimic':{hp:6,attack:2,armour:0},'chapter-boss':{hp:14,attack:2,armour:1}};
function createEnemy(id:string,kind:DungeonEnemyKind,cell:number,floorNumber:number):DungeonEnemy{const base=stats[kind],scale=Math.floor((floorNumber-1)/5);const hp=base.hp+scale*(kind==='chapter-boss'?4:1);return{id,kind,cell,hp,maxHp:hp,attack:base.attack+Math.floor(scale/2),armour:Math.min(4,base.armour+Math.floor(scale/3)),cooldown:0,telegraph:null,phase:1,alive:true}}
export function spawnFloorEncounters(floor:DungeonFloor,floorNumber:number,config:DungeonConfig,rng:NamedRng):DungeonEnemy[]{const excluded=new Set([floor.entrance,floor.sigil,floor.shrine,floor.chest]);const candidates=floor.tiles.map((tile,cell)=>tile===1&&!excluded.has(cell)?cell:-1).filter(cell=>cell>=0&&cell!==floor.gate);const chapterBoss=floorNumber%config.chapterLength===0;const result:DungeonEnemy[]=[];result.push(createEnemy(chapterBoss?'boss-0':'guardian-0',chapterBoss?'chapter-boss':'bone-warden',floor.gate,floorNumber));const desired=Math.min(config.maxEnemies,Math.max(2,2+Math.floor(floorNumber/2)));const kinds:DungeonEnemyKind[]=['mireling','ember-seer','void-hound','reliquary-mimic'];while(result.length<desired&&candidates.length){const ci=rng.nextInt('encounters-v1:cell',candidates.length);const cell=candidates.splice(ci,1)[0];const kind=kinds[(result.length-1+rng.nextInt('encounters-v1:kind',kinds.length))%kinds.length];result.push(createEnemy(`enemy-${result.length}`,kind,cell,floorNumber))}return result.sort((a,b)=>a.id.localeCompare(b.id))}
