import type{TrafficCityProfile,TrafficConfig}from '../../../packages/game-contracts/src/index';
const profiles:TrafficCityProfile[]=['grid','arterial','ring','mixed'];
export type TrafficConfigInput=Partial<TrafficConfig>&Pick<TrafficConfig,'width'|'height'>;
export function parseTrafficConfig(input:TrafficConfigInput):TrafficConfig{
  const config:TrafficConfig={schemaVersion:1,width:input.width,height:input.height,profile:input.profile??'mixed',laneLength:input.laneLength??6,tickRate:input.tickRate??10,maxVehicles:input.maxVehicles??480,spawnEveryTicks:input.spawnEveryTicks??3,pendingDemandCap:input.pendingDemandCap??64,runTicks:input.runTicks??9000,intermissionTicks:input.intermissionTicks??40,maxGridlockTicks:input.maxGridlockTicks??220,signalMinGreenTicks:input.signalMinGreenTicks??18,signalMaxGreenTicks:input.signalMaxGreenTicks??70,decisionIntervalTicks:input.decisionIntervalTicks??8,rerouteWaitTicks:input.rerouteWaitTicks??45,incidentEveryTicks:input.incidentEveryTicks??600,incidentDurationTicks:input.incidentDurationTicks??180,difficulty:input.difficulty??4};
  const integers=(Object.keys(config)as Array<keyof TrafficConfig>).filter(key=>key!=='profile');
  for(const key of integers)if(!Number.isInteger(config[key]))throw new TypeError(String(key));
  if(config.schemaVersion!==1)throw new RangeError('schemaVersion');if(config.width<3||config.width>12)throw new RangeError('width');if(config.height<3||config.height>12)throw new RangeError('height');if(!profiles.includes(config.profile))throw new RangeError('profile');if(config.laneLength<3||config.laneLength>24)throw new RangeError('laneLength');if(config.tickRate<2||config.tickRate>30)throw new RangeError('tickRate');if(config.maxVehicles<8||config.maxVehicles>1500)throw new RangeError('maxVehicles');if(config.spawnEveryTicks<1||config.spawnEveryTicks>300)throw new RangeError('spawnEveryTicks');if(config.pendingDemandCap<0||config.pendingDemandCap>512)throw new RangeError('pendingDemandCap');if(config.runTicks<10||config.runTicks>1_000_000)throw new RangeError('runTicks');if(config.intermissionTicks<0||config.intermissionTicks>5000)throw new RangeError('intermissionTicks');if(config.maxGridlockTicks<10||config.maxGridlockTicks>100_000)throw new RangeError('maxGridlockTicks');if(config.signalMinGreenTicks<2||config.signalMinGreenTicks>1000)throw new RangeError('signalMinGreenTicks');if(config.signalMaxGreenTicks<config.signalMinGreenTicks||config.signalMaxGreenTicks>5000)throw new RangeError('signalMaxGreenTicks');if(config.decisionIntervalTicks<1||config.decisionIntervalTicks>1000)throw new RangeError('decisionIntervalTicks');if(config.rerouteWaitTicks<5||config.rerouteWaitTicks>100_000)throw new RangeError('rerouteWaitTicks');if(config.incidentEveryTicks<20||config.incidentEveryTicks>1_000_000)throw new RangeError('incidentEveryTicks');if(config.incidentDurationTicks<5||config.incidentDurationTicks>100_000)throw new RangeError('incidentDurationTicks');if(config.difficulty<1||config.difficulty>10)throw new RangeError('difficulty');return config;
}
