import type{Direction,DungeonAction}from '../../../../packages/game-contracts/src/index';
import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import{generateDungeonFloor}from '../generation/dungeon';
import type{DungeonState}from '../state/types';
export interface PendingDungeonEvent{type:string;entityId?:string;cell?:number;value?:number;message?:string}
const delta:Record<Direction,[number,number]>={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
function cellFor(state:DungeonState,direction:Direction){const x=state.hero.cell%state.floor.width,y=Math.floor(state.hero.cell/state.floor.width),[dx,dy]=delta[direction];const nx=x+dx,ny=y+dy;return nx<0||ny<0||nx>=state.floor.width||ny>=state.floor.height?-1:ny*state.floor.width+nx}
function meaningful(state:DungeonState){state.meaningfulEventTick=state.tick}
function collectAtHero(state:DungeonState,events:PendingDungeonEvent[]){if(!state.floorProgress.sigilCollected&&state.hero.cell===state.floor.sigil){state.floorProgress.sigilCollected=true;state.floorProgress.gateUnlocked=true;state.hero.score+=100;meaningful(state);events.push({type:'objective.sigil-collected',cell:state.hero.cell,value:100,message:'Astra claimed the floor sigil.'})}if(!state.floorProgress.chestOpened&&state.hero.cell===state.floor.chest){state.floorProgress.chestOpened=true;state.hero.gold+=5;state.hero.score+=25;meaningful(state);events.push({type:'reward.chest-opened',cell:state.hero.cell,value:5,message:'Astra recovered five gold.'})}}
function advanceFloor(state:DungeonState,rng:NamedRng,events:PendingDungeonEvent[]){state.floorNumber++;state.chapter=Math.floor((state.floorNumber-1)/state.config.chapterLength)+1;state.floor=generateDungeonFloor(state.config,state.floorNumber,rng);state.hero.cell=state.floor.entrance;state.floorTick=0;state.lifecycle='running';state.intermissionRemaining=0;state.floorProgress={sigilCollected:false,gateUnlocked:false,chestOpened:false,shrineUsed:false,guardianDefeated:true};state.ai.goal='Find the floor sigil';state.ai.intent='Entering a new floor';state.ai.planReason='Floor advanced';state.ai.knownCells=[state.floor.entrance];meaningful(state);events.push({type:'progress.floor-started',cell:state.floor.entrance,value:state.floorNumber,message:`Floor ${state.floorNumber} begins.`})}
export function stepDungeonRules(state:DungeonState,action:DungeonAction,rng:NamedRng):PendingDungeonEvent[]{const events:PendingDungeonEvent[]=[];state.tick++;if(state.lifecycle==='quarantined'||state.lifecycle==='run-result')return events;if(state.lifecycle==='floor-result'||state.lifecycle==='chapter-result'){state.intermissionRemaining=Math.max(0,state.intermissionRemaining-1);if(state.intermissionRemaining===0)advanceFloor(state,rng,events);return events}state.floorTick++;collectAtHero(state,events);switch(action.kind){case'move':{const next=cellFor(state,action.direction);if(next>=0&&state.floor.tiles[next]===1){state.hero.cell=next;state.hero.facing=action.direction;state.hero.energy=Math.min(state.hero.maxEnergy,state.hero.energy+1);state.ai.lastCells.push(next);if(state.ai.lastCells.length>12)state.ai.lastCells.shift();if(!state.ai.knownCells.includes(next)){state.ai.knownCells.push(next);if(state.ai.knownCells.length>256)state.ai.knownCells.shift()}meaningful(state);events.push({type:'hero.moved',entityId:state.hero.id,cell:next})}else events.push({type:'action.rejected',entityId:state.hero.id,cell:state.hero.cell,message:'Blocked route.'});break}case'heal':if(state.hero.potions>0&&state.hero.hp<state.hero.maxHp){state.hero.potions--;const amount=Math.min(8,state.hero.maxHp-state.hero.hp);state.hero.hp+=amount;meaningful(state);events.push({type:'hero.healed',entityId:state.hero.id,value:amount})}else events.push({type:'action.rejected',entityId:state.hero.id,message:'Healing unavailable.'});break;case'descend':if(state.hero.cell===state.floor.gate&&state.floorProgress.gateUnlocked&&state.floorProgress.guardianDefeated){state.lifecycle=state.floorNumber%state.config.chapterLength===0?'chapter-result':'floor-result';state.intermissionRemaining=state.config.intermissionTicks;state.hero.score+=250;meaningful(state);events.push({type:'progress.floor-cleared',cell:state.hero.cell,value:state.floorNumber,message:`Floor ${state.floorNumber} cleared.`})}else events.push({type:'action.rejected',entityId:state.hero.id,message:'The descent gate remains sealed.'});break;case'guard':state.hero.shield=Math.min(8,state.hero.shield+2);events.push({type:'hero.guarded',entityId:state.hero.id,value:2});break;case'wait':events.push({type:'hero.waited',entityId:state.hero.id});break;case'interact':collectAtHero(state,events);break;case'melee':case'ranged':events.push({type:'action.rejected',entityId:state.hero.id,message:'No valid target.'});break}collectAtHero(state,events);if(state.floorTick>=state.config.maxTicksPerFloor||state.tick-state.meaningfulEventTick>=state.config.noProgressTicks){state.lifecycle='run-result';state.result={kind:'game',reason:state.floorTick>=state.config.maxTicksPerFloor?'timer-expired':'stagnation',tick:state.tick,floor:state.floorNumber,score:state.hero.score,bossesDefeated:state.bossesDefeated};events.push({type:'run.ended',value:state.floorNumber,message:state.result.reason})}return events}
