import type { SkillDefinition, SkillId } from './types';

export const skillDefinitions: Record<SkillId, SkillDefinition> = {
  masonry: {
    id: 'masonry',
    title: 'Block Laying Fundamentals',
    trade: 'Masonry',
    mentor: 'Emeka Nwosu',
    mentorRole: 'Masonry Mentor',
    mentorPosition: [-20, 0, 7],
    workstationPosition: [-18, 0, 8],
    learningRadius: 4.2,
    intro: 'Learn how a mason prepares, places and checks a block before moving to the next course.',
    objective: 'Place a block safely and accurately using a level bed, correct alignment and a clean joint.',
    safetyNote: 'Use gloves, safety boots and eye protection. Handle one block at a time and keep the work area clear.',
    steps: [
      { id: 'masonry-materials', title: 'Identify materials and tools', instruction: 'Identify the block, mortar bed, trowel, line and spirit level before starting.', actionType: 'identify-materials', feedback: 'Correct. Knowing the tool and material sequence prevents rushed placement.', scoreWeight: 12, worldTarget: 'brick-stack' },
      { id: 'masonry-bed', title: 'Prepare a level bed', instruction: 'Prepare an even mortar bed with enough coverage to support the block.', actionType: 'prepare-bed', feedback: 'Good. A level, continuous bed supports load transfer and alignment.', scoreWeight: 20, worldTarget: 'masonry-bed' },
      { id: 'masonry-place', title: 'Place the block', instruction: 'Lift one block, lower it onto the bed and avoid dragging it excessively through the mortar.', actionType: 'place-block', feedback: 'Placed. Controlled handling keeps the bed intact and reduces rework.', scoreWeight: 24, worldTarget: 'brick-drop' },
      { id: 'masonry-align', title: 'Align and level', instruction: 'Use the line and level to check face, height and plumb before the mortar stiffens.', actionType: 'align-block', feedback: 'Aligned. Small corrections now prevent cumulative wall error.', scoreWeight: 28, worldTarget: 'masonry-level' },
      { id: 'masonry-joint', title: 'Finish the joint', instruction: 'Remove excess mortar and finish the joint cleanly without disturbing the block.', actionType: 'finish-joint', feedback: 'Joint finished. The block is now ready for the next unit in the course.', scoreWeight: 16, worldTarget: 'masonry-joint' },
    ],
  },
  welding: {
    id: 'welding',
    title: 'Welding Travel Control',
    trade: 'Welding',
    mentor: 'Tunde Balogun',
    mentorRole: 'Welding Mentor',
    mentorPosition: [21, 0, 10],
    workstationPosition: [19, 0, 8],
    learningRadius: 4.2,
    intro: 'Learn a supervised practice sequence for preparing a welding bay and controlling travel over a coupon.',
    objective: 'Complete a safe practice pass with steady travel and inspect the result for consistency.',
    safetyNote: 'This is simulated practice. Live welding requires qualified supervision, approved PPE, ventilation and a controlled hot-work area.',
    steps: [
      { id: 'welding-ppe', title: 'Confirm PPE and bay safety', instruction: 'Confirm face/eye protection, gloves, skin coverage and a clear hot-work area.', actionType: 'welding-ppe', feedback: 'Safety controls confirmed before any arc activity.', scoreWeight: 18, worldTarget: 'welding-bay' },
      { id: 'welding-equipment', title: 'Inspect equipment', instruction: 'Inspect the torch/holder, lead condition, return connection and workstation condition.', actionType: 'inspect-equipment', feedback: 'Equipment condition checked before starting.', scoreWeight: 14, worldTarget: 'welding-equipment' },
      { id: 'welding-coupon', title: 'Secure the coupon', instruction: 'Position and secure the practice coupon so it cannot shift during the pass.', actionType: 'secure-coupon', feedback: 'The workpiece is stable and ready for a controlled pass.', scoreWeight: 18, worldTarget: 'welding-coupon' },
      { id: 'welding-pass', title: 'Control travel', instruction: 'Move steadily from start to end. Avoid backtracking, sudden pauses and stopping short.', actionType: 'travel-pass', feedback: 'Travel-control sample recorded for scoring.', scoreWeight: 34, worldTarget: 'welding-trace' },
      { id: 'welding-inspect', title: 'Inspect the practice bead', instruction: 'Check continuity and consistency, then identify whether another supervised practice pass is needed.', actionType: 'inspect-bead', feedback: 'Inspection complete. Use the result to improve the next supervised attempt.', scoreWeight: 16, worldTarget: 'welding-bead' },
    ],
  },
  formwork: {
    id: 'formwork',
    title: 'Formwork Readiness Inspection',
    trade: 'Formwork',
    mentor: 'Daniel Mensah',
    mentorRole: 'Foreman · Formwork Mentor',
    mentorPosition: [15, 0, -2],
    workstationPosition: [10, 0, -10],
    learningRadius: 4.4,
    intro: 'Learn how a foreman checks formwork line, support and bracing before a concrete placement.',
    objective: 'Identify a weak support condition, choose a safe correction and verify the system before handoff.',
    safetyNote: 'Do not alter structural formwork without authorization. The lesson teaches observation, correction logic and verification.',
    steps: [
      { id: 'formwork-identify', title: 'Identify the system', instruction: 'Identify the panel, walers, props and braces that are carrying or stabilizing the formwork.', actionType: 'identify-formwork', feedback: 'System components identified.', scoreWeight: 12, worldTarget: 'formwork' },
      { id: 'formwork-line', title: 'Check line and level', instruction: 'Check whether the form face and top reference are aligned to the intended geometry.', actionType: 'check-line-level', feedback: 'Line and level check recorded.', scoreWeight: 16, worldTarget: 'formwork-line' },
      { id: 'formwork-bracing', title: 'Check bracing', instruction: 'Inspect lateral bracing and prop seating for movement or inadequate restraint.', actionType: 'check-bracing', feedback: 'Bracing condition reviewed.', scoreWeight: 18, worldTarget: 'formwork-brace' },
      { id: 'formwork-fault', title: 'Find the weak support', instruction: 'Locate the modeled weak support before recommending any correction.', actionType: 'find-weak-support', feedback: 'Weak support correctly identified.', scoreWeight: 22, worldTarget: 'formwork-weak-support' },
      { id: 'formwork-correct', title: 'Choose the correction', instruction: 'Select the modeled correction that restores support and restraint without bypassing authorization.', actionType: 'correct-support', feedback: 'Correction selected within the training scenario.', scoreWeight: 20, worldTarget: 'formwork-correction' },
      { id: 'formwork-verify', title: 'Verify before pour', instruction: 'Re-check the corrected area and document that it is ready for authorized inspection/handoff.', actionType: 'verify-formwork', feedback: 'Verification complete. The decision can return to authorized site leadership.', scoreWeight: 12, worldTarget: 'formwork' },
    ],
  },
  'rebar-quality': {
    id: 'rebar-quality',
    title: 'Rebar & Quality Control',
    trade: 'Quality Control',
    mentor: 'Grace Adebayo',
    mentorRole: 'Consultant · Quality Mentor',
    mentorPosition: [7, 0, 8],
    workstationPosition: [10, 0, -1.8],
    learningRadius: 4.6,
    intro: 'Learn how a consultant checks reinforcement against the latest detail and records a quality discrepancy.',
    objective: 'Check spacing and cover, detect the modeled mismatch and request the correct inspection path.',
    safetyNote: 'Do not walk on unsupported reinforcement or approve structural work outside your authority.',
    steps: [
      { id: 'rebar-detail', title: 'Read the latest detail', instruction: 'Confirm the latest issued reinforcement detail before comparing site work.', actionType: 'read-detail', feedback: 'Latest detail confirmed for the lesson.', scoreWeight: 16, worldTarget: 'drawing-latest' },
      { id: 'rebar-spacing', title: 'Check bar spacing', instruction: 'Compare the modeled bar spacing to the latest detail.', actionType: 'check-spacing', feedback: 'Spacing check recorded.', scoreWeight: 18, worldTarget: 'rebar' },
      { id: 'rebar-cover', title: 'Check concrete cover', instruction: 'Check that the reinforcement is held at the required cover from the form face.', actionType: 'check-cover', feedback: 'Cover check recorded.', scoreWeight: 18, worldTarget: 'rebar-cover' },
      { id: 'rebar-mismatch', title: 'Find the mismatch', instruction: 'Identify the service-opening reinforcement mismatch shown in the training model.', actionType: 'find-mismatch', feedback: 'Mismatch found and isolated.', scoreWeight: 22, worldTarget: 'rebar-mismatch' },
      { id: 'rebar-record', title: 'Record the discrepancy', instruction: 'Record what differs, where it differs and which drawing detail governs the issue.', actionType: 'record-discrepancy', feedback: 'Quality discrepancy recorded clearly.', scoreWeight: 14, worldTarget: 'rebar-record' },
      { id: 'rebar-inspection', title: 'Request quality inspection', instruction: 'Request consultant/authorized inspection rather than approving the reinforcement yourself.', actionType: 'request-quality-inspection', feedback: 'Correct quality-control handoff selected.', scoreWeight: 12, worldTarget: 'rebar-inspection' },
    ],
  },
};
