const test=require('node:test');const assert=require('node:assert/strict');
const {parseSnakeConfig}=require('../../dist/games/autonomous-snake/src/config/schema.js');const {createInitialState}=require('../../dist/games/autonomous-snake/src/index.js');const {NamedRng}=require('../../dist/packages/seeded-rng/src/index.js');const {applyAction}=require('../../dist/games/autonomous-snake/src/rules/step.js');const {chooseProductionAction,safeProductionDecision}=require('../../dist/games/autonomous-snake/src/ai/production.js');const {SnakeRuntime}=require('../../dist/games/autonomous-snake/src/runtime/run.js');const {encodeSnapshot,restoreRuntime}=require('../../dist/games/autonomous-snake/src/persistence/snapshot.js');const {checksum}=require('../../dist/packages/replay/src/index.js');const {inspectDecision}=require('../../dist/games/autonomous-snake/src/debug/decision.js');
test('portal movement transforms entry to symmetric exit and emits semantic event',()=>{const c=parseSnakeConfig({width:8,height:8,targetLength:20,profile:'portals'});const s=createInitialState(c,'portal-fixture','r');s.snake.body=[27,26,25];s.snake.direction='right';s.portalPairs={28:45,45:28};s.obstacles=[];s.hazards=[];s.food=10;const r=applyAction(s,{direction:'right'},NamedRng.fromSeed('portal-fixture'));assert.equal(r.state.snake.body[0],45);assert.ok(r.events.some(e=>e.type==='portal-used'&&e.data.entry===28&&e.data.exit===45))});
test('hazard collision is a game terminal distinct from wall/self',()=>{const c=parseSnakeConfig({width:8,height:8,targetLength:20});const s=createInitialState(c,'hazard-fixture','r');s.snake.body=[27,26,25];s.snake.direction='right';s.hazards=[28];s.food=10;const r=applyAction(s,{direction:'right'},NamedRng.fromSeed('hazard-fixture'));assert.equal(r.state.result.reason,'hazard-collision')});
test('policy exception degrades to deterministic validated fallback instead of freezing',()=>{const c=parseSnakeConfig({width:8,height:8,targetLength:20});const s=createInitialState(c,'policy-error','r');const d=safeProductionDecision(s,()=>{throw new Error('planner exploded')});assert.ok(d.intent.fallbackUsed);assert.ok(d.action===null||['up','right','down','left'].includes(d.action.direction));assert.match(d.intent.explanation,/planner/i)});
test('repeat-state pathology selects deterministic replan when alternatives exist',()=>{const c=parseSnakeConfig({width:10,height:10,targetLength:30});const s=createInitialState(c,'repeat','r');s.ai.repeatCount=6;const d=chooseProductionAction(s);assert.equal(d.intent.mode,'replan');assert.ok(d.action)});
test('non-open snapshot preserves AI, topology and replay determinism',()=>{const a=SnakeRuntime.create({width:10,height:10,targetLength:20,profile:'corridors',hazardCount:2},'snap-r2');for(let i=0;i<12&&!a.state.result;i++)a.step();const b=restoreRuntime(encodeSnapshot(a));assert.equal(checksum(a.state),checksum(b.state));assert.deepEqual(a.state.obstacles,b.state.obstacles);assert.deepEqual(a.state.hazards,b.state.hazards);assert.deepEqual(a.state.ai,b.state.ai);for(let i=0;i<20&&!a.state.result&&!b.state.result;i++){a.step();b.step();assert.equal(checksum(a.state),checksum(b.state))}});
test('debug decision inspector exposes bounded candidate explanation without mutating authority',()=>{const c=parseSnakeConfig({width:10,height:10,targetLength:30,profile:'rings',hazardCount:1});const s=createInitialState(c,'debug','r');const before=checksum(s);const report=inspectDecision(s);assert.equal(checksum(s),before);assert.equal(report.profile,'rings');assert.ok(Array.isArray(report.candidates));assert.ok(report.candidates.length<=4);assert.ok(Number.isInteger(report.nodeExpansions));assert.ok(report.nodeExpansions<=c.width*c.height*4)});
test('no-progress cycle resolves as deterministic game stagnation, not technical timeout',()=>{const r=SnakeRuntime.create({width:8,height:8,targetLength:20,noProgressTicks:3},'stagnation');r.state.meaningfulEventTick=0;r.state.food=0;for(let i=0;i<5&&!r.state.result;i++)r.step();assert.ok(r.state.result);assert.equal(r.state.result.reason,'stagnation');assert.match(r.state.result.finalChecksum,/^[0-9a-f]{8}$/)});
