'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{DungeonRuntime}=require('../../dist/games/ai-dungeon-endless-adventure/src/runtime/run.js');
const{planDungeonAction}=require('../../dist/games/ai-dungeon-endless-adventure/src/ai/policy.js');

const base={schemaVersion:1,width:31,height:21,roomAttempts:24,roomMinSize:3,roomMaxSize:7,loopChancePermille:180,chapterLength:5,maxTicksPerFloor:1800,intermissionTicks:2,maxEnemies:18,maxRelics:6,maxEvents:96,noProgressTicks:600};
function arena(seed){const runtime=new DungeonRuntime(base,seed,`${seed}-run`),width=runtime.state.floor.width,hero=10*width+10,cells=[];runtime.state.floor.tiles.fill(0);for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const cell=hero+y*width+x;runtime.state.floor.tiles[cell]=1;cells.push(cell)}runtime.state.hero.cell=hero;runtime.state.hero.vision=4;runtime.state.hero.hp=runtime.state.hero.maxHp;runtime.state.hero.energy=0;runtime.state.hero.potions=0;runtime.state.ai.knownCells=[...cells].sort((a,b)=>a-b);runtime.state.floor.sigil=0;runtime.state.floor.gate=1;runtime.state.floor.chest=2;runtime.state.floor.shrine=3;return{runtime,width,hero}}

test('Astra creates space when two visible threats are closing and ranged energy is exhausted',()=>{const{runtime,width,hero}=arena('multi-threat-retreat');runtime.state.enemies=[{id:'north',kind:'mireling',cell:hero-2*width,hp:6,maxHp:6,attack:2,armour:0,cooldown:0,telegraph:null,phase:1,alive:true},{id:'east',kind:'void-hound',cell:hero+2,hp:6,maxHp:6,attack:2,armour:0,cooldown:0,telegraph:null,phase:1,alive:true}];const proposal=planDungeonAction(runtime.state);assert.equal(proposal.action.kind,'move');assert.equal(proposal.action.direction,'down');assert.equal(proposal.ai.goal,'Break enemy pressure');assert.match(proposal.ai.intent,/creating space/i)});

test('low-health Astra without recovery moves away from a visible threat instead of advancing toward optional treasure',()=>{const{runtime,hero}=arena('low-health-treasure-risk');runtime.state.hero.hp=Math.floor(runtime.state.hero.maxHp*.45);runtime.state.floor.chest=hero+2;runtime.state.ai.knownCells.push(runtime.state.floor.chest);runtime.state.enemies=[{id:'chest-guard',kind:'mireling',cell:hero+3,hp:6,maxHp:6,attack:2,armour:0,cooldown:0,telegraph:null,phase:1,alive:true}];const proposal=planDungeonAction(runtime.state);assert.equal(proposal.action.kind,'move');assert.equal(proposal.action.direction,'left');assert.equal(proposal.ai.goal,'Preserve the run');assert.match(proposal.ai.intent,/retreat/i)});

test('healthy Astra describes a known optional chest truthfully when choosing to approach it',()=>{const{runtime,hero}=arena('truthful-chest-intent');runtime.state.hero.energy=6;runtime.state.floor.chest=hero+2;runtime.state.ai.knownCells.push(runtime.state.floor.chest);runtime.state.enemies=[];const proposal=planDungeonAction(runtime.state);assert.deepEqual(proposal.action,{kind:'move',direction:'right'});assert.equal(proposal.ai.goal,'Recover optional treasure');assert.equal(proposal.ai.intent,'Approaching the known chest');assert.equal(proposal.ai.planReason,'Known optional reward is safe enough to pursue')});
