'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{TowerRuntime}=require('../../dist/games/infinite-tower-climb/src/runtime/run.js');
const{createTowerObservation}=require('../../dist/games/infinite-tower-climb/src/ai/observation.js');
const{chooseTowerAction}=require('../../dist/games/infinite-tower-climb/src/ai/policy.js');
function runtime(seed='tower-ai'){return TowerRuntime.create({maxTicks:5000,noProgressTicks:2200},seed,{policy:'autonomous'})}
test('observation exposes current permitted play state but no seed, checksums or future chunks',()=>{const r=runtime('privacy'),obs=createTowerObservation(r.state);assert.equal(obs.floor,0);assert.ok(obs.platforms.length>=6);assert.equal('seed'in obs,false);assert.equal('runId'in obs,false);assert.equal('config'in obs,false);assert.equal('checksum'in obs,false);assert.equal('chunks'in obs,false);assert.ok(obs.platforms.every(p=>!('checksum'in p)))});
test('nearby active enemy triggers a legal causal attack intent',()=>{const r=runtime('enemy-reflex'),s=structuredClone(r.state);s.enemies=[{id:'enemy',kind:'sentinel',floor:0,position:{x:s.player.position.x+24000,y:s.player.position.y},velocity:{x:0,y:0},halfWidth:9000,halfHeight:12000,health:3,maxHealth:3,facing:-1,patrolMinX:0,patrolMaxX:s.config.worldWidth,cooldown:0,telegraphUntilTick:0,active:true,damage:1}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.action.attack,true);assert.equal(d.intent.mode,'engaging-enemy');assert.ok([-1,0,1].includes(d.action.move))});
test('active hazard on the immediate route is not walked into blindly',()=>{const r=runtime('hazard-reflex'),s=structuredClone(r.state),p=s.player;s.chunks[0].hazards=[{id:'danger',kind:'spikes',x:p.position.x+12000,y:p.position.y-p.halfHeight,width:36000,height:12000,activeFromTick:0,activeEvery:40,activeFor:40,damage:1}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'evading-hazard');assert.ok(d.action.jump||d.action.move<=0,JSON.stringify(d))});
test('repeated height state activates bounded recovery rather than endless route churn',()=>{const r=runtime('stuck'),s=structuredClone(r.state);s.ai.recentHeights=Array(48).fill(s.height);s.player.grounded=true;s.player.groundedPlatformId=s.chunks[0].platforms[0].id;const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'recovering');assert.equal(d.intent.fallbackUsed,true);assert.ok(d.action.jump||d.action.dash||d.action.move!==0)});
test('autonomous policy advances through executable content without remote services',()=>{const r=runtime('autonomous-floor');for(let i=0;i<3500&&r.state.lifecycle==='running'&&r.state.floor===0;i++)r.step();assert.ok(r.state.floor>=1,JSON.stringify({result:r.state.result,stats:r.state.stats,ai:r.state.ai}));assert.equal(r.state.stats.technicalOutcomes,0)});
