'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{TowerRuntime}=require('../../dist/games/infinite-tower-climb/src/runtime/run.js');
const{createTowerObservation}=require('../../dist/games/infinite-tower-climb/src/ai/observation.js');
const{chooseTowerAction}=require('../../dist/games/infinite-tower-climb/src/ai/policy.js');
function runtime(seed='tower-ai'){return TowerRuntime.create({maxTicks:5000,noProgressTicks:2200},seed,{policy:'autonomous'})}
function guardianRuntime(seed='tower-guardian-ai'){return TowerRuntime.create({launchFloor:10,maxTicks:5000,noProgressTicks:2200},seed,{policy:'autonomous'})}
function stageGuardian(s){const g=s.enemies.find(e=>e.kind==='guardian'&&e.floor===s.floor);assert.ok(g,'launch floor must include guardian');const reach=s.config.attackReach+s.build.attackReachBonus,dir=s.player.position.x<s.config.worldWidth/2?1:-1,distance=reach+60000;g.position={x:s.player.position.x+dir*distance,y:s.player.position.y};g.patrolMinX=Math.max(0,g.position.x-50000);g.patrolMaxX=Math.min(s.config.worldWidth,g.position.x+50000);g.cooldown=0;g.telegraphUntilTick=0;g.active=true;return{g,dir,reach}}
function stageWallJump(s){const chunk=s.chunks.find(c=>c.floor===s.floor),base=chunk.baseY,p=s.player,wall={id:'test:ai-wall',kind:'solid',x:240000,y:base+90000,width:18000,height:160000},target={id:'test:ai-wall-target',kind:'solid',x:85000,y:base+245000,width:130000,height:10000};chunk.platforms=[chunk.platforms[0],wall,target];chunk.hazards=[];s.enemies=[];s.projectiles=[];s.pickups=[];p.position={x:wall.x-p.halfWidth-2500,y:base+165000};p.velocity={x:0,y:1500};p.grounded=false;p.groundedPlatformId=undefined;p.state='airborne';s.ai.targetPlatformId=target.id;s.ai.recentHeights=[];return{wall,target}}
test('observation exposes current permitted play state but no seed, checksums or future chunks',()=>{const r=runtime('privacy'),obs=createTowerObservation(r.state);assert.equal(obs.floor,0);assert.ok(obs.platforms.length>=6);assert.equal('seed'in obs,false);assert.equal('runId'in obs,false);assert.equal('config'in obs,false);assert.equal('checksum'in obs,false);assert.equal('chunks'in obs,false);assert.ok(obs.platforms.every(p=>!('checksum'in p)))});
test('nearby active enemy triggers a legal causal attack intent',()=>{const r=runtime('enemy-reflex'),s=structuredClone(r.state);s.enemies=[{id:'enemy',kind:'sentinel',floor:0,position:{x:s.player.position.x+24000,y:s.player.position.y},velocity:{x:0,y:0},halfWidth:9000,halfHeight:12000,health:3,maxHealth:3,facing:-1,patrolMinX:0,patrolMaxX:s.config.worldWidth,cooldown:0,telegraphUntilTick:0,active:true,damage:1}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.action.attack,true);assert.equal(d.intent.mode,'engaging-enemy');assert.ok([-1,0,1].includes(d.action.move))});
test('guardian outside melee reach is approached intentionally instead of ignored by traversal',()=>{const r=guardianRuntime('guardian-approach'),s=structuredClone(r.state),{g,dir,reach}=stageGuardian(s);s.build.upgradeIds=[...new Set([...s.build.upgradeIds,'pulse-shot'])];s.player.abilityCooldown=0;const distance=Math.abs(g.position.x-s.player.position.x);assert.ok(distance>reach);const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'engaging-guardian');assert.equal(d.action.move,dir);assert.equal(d.action.attack,false);assert.equal(d.action.ability,true);assert.ok(d.intent.summary.toLowerCase().includes('guardian'))});
test('incoming projectile remains higher priority than guardian engagement',()=>{const r=guardianRuntime('guardian-projectile-priority'),s=structuredClone(r.state);stageGuardian(s);const p=s.player;s.projectiles=[{id:'incoming',owner:'enemy',floor:s.floor,position:{x:p.position.x+40000,y:p.position.y},velocity:{x:-s.config.projectileSpeed,y:0},halfWidth:5000,halfHeight:3500,damage:1,ttl:40,active:true,hitIds:[]}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'evading-projectile');assert.equal(d.action.attack,false)});
test('active hazard on the immediate route is not walked into blindly',()=>{const r=runtime('hazard-reflex'),s=structuredClone(r.state),p=s.player;s.chunks[0].hazards=[{id:'danger',kind:'spikes',x:p.position.x+12000,y:p.position.y-p.halfHeight,width:36000,height:12000,activeFromTick:0,activeEvery:40,activeFor:40,damage:1}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'evading-hazard');assert.ok(d.action.jump||d.action.move<=0,JSON.stringify(d))});
test('repeated height state activates bounded recovery rather than endless route churn',()=>{const r=runtime('stuck'),s=structuredClone(r.state);s.ai.recentHeights=Array(48).fill(s.height);s.player.grounded=true;s.player.groundedPlatformId=s.chunks[0].platforms[0].id;const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'recovering');assert.equal(d.intent.fallbackUsed,true);assert.ok(d.action.jump||d.action.dash||d.action.move!==0)});
test('airborne agent beside a solid wall deliberately uses wall jump toward an elevated route',()=>{const r=runtime('wall-jump-policy'),s=structuredClone(r.state);stageWallJump(s);const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'wall-jumping');assert.equal(d.action.wallJump,true);assert.equal(d.action.move,-1);assert.ok(d.intent.summary.toLowerCase().includes('wall'))});
test('projectile evasion remains higher priority than wall-jump route mastery',()=>{const r=runtime('wall-jump-projectile-priority'),s=structuredClone(r.state);stageWallJump(s);const p=s.player;s.projectiles=[{id:'incoming-wall-route',owner:'enemy',floor:s.floor,position:{x:p.position.x+40000,y:p.position.y},velocity:{x:-s.config.projectileSpeed,y:0},halfWidth:5000,halfHeight:3500,damage:1,ttl:40,active:true,hitIds:[]}];const d=chooseTowerAction(s,createTowerObservation(s));assert.equal(d.intent.mode,'evading-projectile');assert.equal(d.action.wallJump,false)});
test('autonomous policy advances through executable content without remote services',()=>{const r=runtime('autonomous-floor');for(let i=0;i<3500&&r.state.lifecycle==='running'&&r.state.floor===0;i++)r.step();assert.ok(r.state.floor>=1,JSON.stringify({result:r.state.result,stats:r.state.stats,ai:r.state.ai}));assert.equal(r.state.stats.technicalOutcomes,0)});
