'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{ZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/runtime/run');
const{chooseSurvivorDecision}=require('../../dist/games/ai-zombie-survival/src/ai/policy');
const{stableNeighbors}=require('../../dist/games/ai-zombie-survival/src/rules/grid');
const{zombieManifest}=require('../../dist/games/ai-zombie-survival/src/manifest');
const{createZombieSnapshot,restoreZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/replay/snapshot');
function config(){return{width:24,height:16,dayTicks:50,nightTicks:50,maxDays:3,maxZombies:24,survivorDecisionInterval:1,waveBaseSize:4,waveGrowthPerDay:1}}
test('builder constructs a stronger perimeter when repairs are complete',()=>{const game=ZombieRuntime.create(config(),'construction'),state=structuredClone(game.state),builder=state.survivors.find(s=>s.role==='builder'),defense=state.defenses[0];state.defenses.forEach(item=>item.integrity=item.maxIntegrity);builder.cell=defense.cell;state.resources.materials=10;state.baseIntegrity=0;const decision=chooseSurvivorDecision(state,builder.id);assert.equal(decision.action,'build');assert.equal(decision.targetId,defense.id);const priorMax=defense.maxIntegrity;game.state=state;game.step();const built=game.state.defenses.find(item=>item.id===defense.id);assert.equal(game.state.resources.materials,0);assert.equal(built.level,2);assert.ok(built.maxIntegrity>priorMax);assert.equal(built.integrity,built.maxIntegrity);assert.equal(game.state.stats.wallsBuilt,1);assert.equal(game.state.baseIntegrity,1000);assert.ok(game.events.some(event=>event.type==='defense-built'))});
test('failed movement increments stuck state and policy breaks the loop deterministically',()=>{const game=ZombieRuntime.create(config(),'stuck-recovery'),state=structuredClone(game.state),scout=state.survivors.find(s=>s.role==='scout');const blockers=stableNeighbors(scout.cell,state.world.width,state.world.height);state.world.blockedCells=[...new Set([...state.world.blockedCells,...blockers])].sort((a,b)=>a-b);game.state=state;for(let i=0;i<4;i++)game.step();const recovered=game.state.survivors.find(s=>s.id===scout.id);assert.ok(recovered.stuckTicks>=3);assert.match(recovered.intent,/loop|stuck|alternate/i);const first=chooseSurvivorDecision(game.state,scout.id),second=chooseSurvivorDecision(game.state,scout.id);assert.deepEqual(first,second);assert.equal(first.action,'reposition')});
test('successful movement clears stale stuck state',()=>{const game=ZombieRuntime.create(config(),'stuck-clear'),state=structuredClone(game.state),scout=state.survivors.find(s=>s.role==='scout');scout.stuckTicks=3;game.state=state;game.step();const moved=game.state.survivors.find(s=>s.id===scout.id);assert.equal(moved.stuckTicks,0);assert.notEqual(moved.cell,scout.cell)});
test('material Phase 2 rules use a fresh deterministic version boundary',()=>{const game=ZombieRuntime.create(config(),'version-boundary'),snapshot=createZombieSnapshot(game);assert.equal(game.config.deterministicVersion,'zombie-v2');assert.equal(zombieManifest.gameVersion,'0.2.0');assert.equal(zombieManifest.deterministicVersion,'zombie-v2');assert.equal(snapshot.deterministicVersion,'zombie-v2');const old=structuredClone(snapshot);old.deterministicVersion='zombie-v1';assert.throws(()=>restoreZombieRuntime(old),/deterministicVersion/)});
