'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{ZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/runtime/run');
const{createSurvivorObservation,chooseTeamStrategy,chooseSurvivorDecision}=require('../../dist/games/ai-zombie-survival/src/ai/policy');
function runtime(){return ZombieRuntime.create({width:24,height:16,dayTicks:40,nightTicks:40,maxDays:3,maxZombies:32,waveBaseSize:4,waveGrowthPerDay:1},'phase2-ai')}
test('survivor observation excludes unspawned horde truth and respects fog visibility',()=>{const game=runtime(),state=structuredClone(game.state),scout=state.survivors.find(s=>s.role==='scout');state.weather='fog';state.horde.totalForNight=20;state.horde.spawned=1;state.zombies=[{id:'near',kind:'walker',cell:scout.cell+1,health:40,maxHealth:40,status:'active',gateId:'gate-north',moveCooldown:0,attackCooldown:0},{id:'far',kind:'brute',cell:state.world.gates[2].cell,health:120,maxHealth:120,status:'active',gateId:'gate-south',moveCooldown:0,attackCooldown:0}];const observation=createSurvivorObservation(state,scout.id);assert.equal(JSON.stringify(observation).includes('totalForNight'),false);assert.deepEqual(observation.visibleZombies.map(z=>z.id),['near']);assert.equal(observation.forecast.band,'low')});
test('team strategy responds deterministically to weak defenses, casualties and scarcity',()=>{const game=runtime(),state=structuredClone(game.state);state.defenses[0].integrity=20;assert.equal(chooseTeamStrategy(state),'fortify');state.defenses.forEach(d=>d.integrity=d.maxIntegrity);state.survivors[0].health=20;assert.equal(chooseTeamStrategy(state),'rescue');state.survivors[0].health=100;state.resources.materials=4;state.resources.food=5;assert.equal(chooseTeamStrategy(state),'stockpile');state.coreIntegrity=200;assert.equal(chooseTeamStrategy(state),'last-stand')});
test('medic heals and builder repairs through legal deterministic decisions',()=>{const game=runtime(),state=structuredClone(game.state),medic=state.survivors.find(s=>s.role==='medic'),builder=state.survivors.find(s=>s.role==='builder'),injured=state.survivors.find(s=>s.role==='guard');injured.health=45;state.resources.medicine=3;const heal=chooseSurvivorDecision(state,medic.id);assert.equal(heal.action,'heal');assert.equal(heal.targetId,injured.id);state.survivors.forEach(s=>s.health=100);state.defenses[1].integrity=80;state.resources.materials=20;const repair=chooseSurvivorDecision(state,builder.id);assert.equal(repair.action,'repair');assert.equal(repair.targetId,state.defenses[1].id);assert.deepEqual(chooseSurvivorDecision(state,builder.id),repair)});
test('night decisions prioritize visible lethal threats without reading hidden spawns',()=>{const game=runtime(),state=structuredClone(game.state),guard=state.survivors.find(s=>s.role==='guard');state.lifecycle='horde';state.resources.ammo=2;state.zombies=[{id:'threat',kind:'runner',cell:guard.cell+1,health:30,maxHealth:30,status:'active',gateId:'gate-east',moveCooldown:0,attackCooldown:0}];const decision=chooseSurvivorDecision(state,guard.id);assert.equal(decision.action,'attack');assert.equal(decision.targetId,'threat');assert.ok(decision.confidence>=0&&decision.confidence<=1);assert.ok(decision.intent.length<=96)});
