import type{TrafficInfluenceEffectId}from './types';
export interface TrafficInfluenceDefinition{id:TrafficInfluenceEffectId;label:string;category:'policy'|'challenge'|'recovery'|'presentation';durationTicks:number;cooldownTicks:number;conflictGroup:string;reversible:boolean;paidEligible:boolean;maxApplicationsPerRun:number;description:string}
export const trafficInfluenceCatalogue:Record<TrafficInfluenceEffectId,TrafficInfluenceDefinition>=Object.freeze({
  'green-wave-ns':{id:'green-wave-ns',label:'North–South Green Wave',category:'policy',durationTicks:120,cooldownTicks:90,conflictGroup:'axis-bias',reversible:true,paidEligible:true,maxApplicationsPerRun:20,description:'Temporarily biases eligible adaptive signals toward north–south traffic without overriding minimum green.'},
  'green-wave-ew':{id:'green-wave-ew',label:'East–West Green Wave',category:'policy',durationTicks:120,cooldownTicks:90,conflictGroup:'axis-bias',reversible:true,paidEligible:true,maxApplicationsPerRun:20,description:'Temporarily biases eligible adaptive signals toward east–west traffic without overriding minimum green.'},
  'transit-priority':{id:'transit-priority',label:'Transit Priority',category:'policy',durationTicks:140,cooldownTicks:110,conflictGroup:'transit-priority',reversible:true,paidEligible:true,maxApplicationsPerRun:16,description:'Raises bus movement priority while preserving collision and signal legality.'},
  'challenge-surge':{id:'challenge-surge',label:'Demand Surge',category:'challenge',durationTicks:100,cooldownTicks:180,conflictGroup:'demand-pressure',reversible:true,paidEligible:true,maxApplicationsPerRun:12,description:'Raises bounded demand pressure; it cannot force gridlock or alter terminal state directly.'},
  'incident-relief':{id:'incident-relief',label:'Incident Relief Crew',category:'recovery',durationTicks:1,cooldownTicks:160,conflictGroup:'incident-relief',reversible:false,paidEligible:true,maxApplicationsPerRun:12,description:'Shortens one active incident by a bounded amount while retaining a visible response window.'},
  'night-theme':{id:'night-theme',label:'Night Shift',category:'presentation',durationTicks:240,cooldownTicks:120,conflictGroup:'theme',reversible:true,paidEligible:true,maxApplicationsPerRun:12,description:'Changes only the public theme and never changes simulation authority.'}
});
