import type {GameState,Survivor,Zombie} from './types.js';

export type EvidenceScenario='exploration'|'scavenging'|'small-encounter'|'large-horde'|'barricade-defense'|'interior'|'day'|'night'|'near-death'|'failure';
export type EvidenceGameState=GameState&{evidenceScenario:EvidenceScenario};
const names:EvidenceScenario[]=['exploration','scavenging','small-encounter','large-horde','barricade-defense','interior','day','night','near-death','failure'];
export const evidenceScenarios=names as readonly EvidenceScenario[];
export function isEvidenceScenario(value:string|null):value is EvidenceScenario{return value!==null&&(names as readonly string[]).includes(value);}

function positionZombie(z:Zombie,x:number,y:number,action:Zombie['action']='pursue'){z.x=x;z.y=y;z.action=action;z.targetId='s-0';z.distanceToSafeHouse=Math.hypot(x,y);z.health=Math.max(1,z.health);}
function clearFocus(g:GameState){for(const s of g.survivors){s.action='idle';s.threat=.08;s.insideBuildingId=null;s.carrying=0;s.carryingKind=null;s.escortCivilianId=null;}for(const b of g.buildings){b.roofVisible=true;b.interiorLit=false;}g.weather={kind:'clear',intensity:0};g.time.phase='day';g.time.phaseProgress=.4;g.hordePressure=.18;}
function stageRing(g:GameState,count:number,radius:number,centerX=0,centerY=0){for(let i=0;i<g.zombies.length;i++){const z=g.zombies[i];if(i<count){const ring=radius+(i%5)*.34,a=i*2.399963229728653;positionZombie(z,centerX+Math.cos(a)*ring,centerY+Math.sin(a)*ring,i%7===0?'detect':'pursue');}else{positionZombie(z,38+(i%12)*.8,36+Math.floor(i/12)*.65,'wander');}}}
function focusSurvivor(g:GameState):Survivor{return g.survivors[0];}

export function applyEvidenceScenario(input:GameState,name:EvidenceScenario):EvidenceGameState{
 const g=structuredClone(input) as EvidenceGameState;g.evidenceScenario=name;clearFocus(g);const s=focusSurvivor(g);
 if(name==='exploration'){s.x=-25;s.y=-18;s.action='move';s.goal='Scout the residential district';s.intent='Sweep the street for a safe route';s.targetX=-18;s.targetY=-11;stageRing(g,8,13,-25,-18);g.objective={kind:'survive',targetId:null,label:'Scout the residential district',progress:.35};}
 else if(name==='scavenging'){const loot=g.loot.find(l=>l.amount>0)!;const b=g.buildings.find(v=>v.id===loot.buildingId)!;s.x=loot.x-.35;s.y=loot.y-.2;s.action='scavenge';s.role='scavenger';s.goal='Replenish scarce supplies';s.intent=`Search the ${b.kind}`;s.insideBuildingId=b.id;b.roofVisible=false;b.interiorLit=true;g.objective={kind:'scavenge',targetId:loot.id,label:`Search ${b.kind} for ${loot.kind}`,progress:.58};stageRing(g,6,10,b.x,b.y);}
 else if(name==='small-encounter'){s.x=-4;s.y=2;s.action='aim';s.goal='Protect the squad';s.intent='Hold the street against a small pack';s.threat=.72;stageRing(g,9,4.2,s.x,s.y);g.hordePressure=.35;g.objective={kind:'survive',targetId:null,label:'Clear the street',progress:.42};}
 else if(name==='large-horde'){s.x=2;s.y=1;s.action='aim';s.threat=.88;stageRing(g,Math.min(g.zombies.length,190),8.4,0,0);g.hordePressure=.98;g.objective={kind:'fortify',targetId:g.barricades[0]?.id??null,label:'Hold the safe-house perimeter',progress:.68};}
 else if(name==='barricade-defense'){const bar=g.barricades[0];bar.hp=bar.maxHp*.28;s.x=bar.x-1.2;s.y=bar.y+.5;s.action='aim';s.role='defender';s.goal='Hold the perimeter';s.intent='Protect the failing barricade';s.threat=.91;for(let i=0;i<Math.min(28,g.zombies.length);i++){const z=g.zombies[i],row=Math.floor(i/7),col=i%7;positionZombie(z,bar.x+1.4+row*.55,bar.y-1.5+col*.5,'attack');}g.hordePressure=.83;g.objective={kind:'fortify',targetId:bar.id,label:'Defend the eastern barricade',progress:.31};}
 else if(name==='interior'){const b=g.buildings.find(v=>v.kind==='shop'||v.kind==='supermarket')??g.buildings.find(v=>v.kind!=='safehouse')!;s.x=b.x;s.y=b.y;s.action='scavenge';s.insideBuildingId=b.id;b.roofVisible=false;b.interiorLit=true;const loot=g.loot.find(l=>l.buildingId===b.id);g.objective={kind:'scavenge',targetId:loot?.id??null,label:`Search inside ${b.kind}`,progress:.5};stageRing(g,4,9,b.x,b.y);}
 else if(name==='day'){g.time.phase='day';g.time.phaseProgress=.5;g.weather={kind:'clear',intensity:0};s.action='move';s.x=-10;s.y=-7;stageRing(g,12,11);g.objective={kind:'survive',targetId:null,label:'Use daylight to secure supplies',progress:.45};}
 else if(name==='night'){g.time.phase='night';g.time.phaseProgress=.55;g.weather={kind:'fog',intensity:.32};s.action='aim';s.x=2;s.y=2;s.threat=.72;stageRing(g,28,7.5);g.hordePressure=.71;g.objective={kind:'fortify',targetId:g.barricades[1]?.id??null,label:'Survive the night',progress:.74};}
 else if(name==='near-death'){s.x=5;s.y=3;s.health=9;s.stamina=18;s.action='retreat';s.threat=.99;s.goal='Survive';s.intent='Break contact and reach the safe house';for(let i=0;i<Math.min(16,g.zombies.length);i++){const a=i/16*Math.PI*2,r=1.7+(i%3)*.35;positionZombie(g.zombies[i],s.x+Math.cos(a)*r,s.y+Math.sin(a)*r,'pursue');}g.hordePressure=.94;g.objective={kind:'survive',targetId:s.id,label:'Escape the encirclement',progress:.12};}
 else if(name==='failure'){g.status='overrun';g.safeHouse.integrity=0;for(const b of g.barricades)b.hp=Math.min(b.hp,b.maxHp*.08);for(let i=0;i<Math.min(42,g.zombies.length);i++){const a=i/42*Math.PI*2,r=2.2+(i%5)*.45;positionZombie(g.zombies[i],Math.cos(a)*r,Math.sin(a)*r,'attack');}for(let i=0;i<g.survivors.length;i++){g.survivors[i].health=i===0?6:0;g.survivors[i].alive=i===0;g.survivors[i].action=i===0?'injured':'dead';g.survivors[i].x=-1+i*.6;g.survivors[i].y=1+i*.35;}g.hordePressure=1;g.objective={kind:'survive',targetId:null,label:'Safe house overrun',progress:0};}
 return g;
}
