import type {Barricade,Building,District,DistrictKind,LootNode,Survivor,SurvivorRole,Zombie} from './types.js';
import {randomInt,randomRange} from './random.js';
const roles:SurvivorRole[]=['leader','scout','medic','defender','scavenger','engineer']; const names=['Mara','Jonah','Imani','Tariq','Ada','Luis','Nia','Eli'];
export function createDistricts():District[]{const kinds:DistrictKind[]=['residential','commercial','medical','civic','industrial','outskirts'];return kinds.map((kind,i)=>({id:`district-${kind}`,kind,x:(i%3)*34-34,y:Math.floor(i/3)*34-24,w:30,h:30}));}
export function createBuildings(seed:number):[Building[],LootNode[],number]{const districts=createDistricts(), buildings:Building[]=[],loot:LootNode[]=[];let rng=seed,bi=0,li=0;const kinds:Building['kind'][]=['apartment','shop','supermarket','hospital','police','warehouse','fuel'];for(const district of districts){for(let i=0;i<5;i++){let rx,ry,floors,dmg,kindIndex;[rx,rng]=randomRange(rng,-district.w*.36,district.w*.36);[ry,rng]=randomRange(rng,-district.h*.36,district.h*.36);[floors,rng]=randomInt(rng,1,5);[dmg,rng]=randomRange(rng,.08,.65);[kindIndex,rng]=randomInt(rng,0,kinds.length);let x=district.x+rx,y=district.y+ry;const center=Math.hypot(x,y);if(center<9){const a=Math.atan2(y||1,x||1);x=Math.cos(a)*9;y=Math.sin(a)*9;}const b:Building={id:`b-${bi++}`,district:district.kind,kind:kinds[kindIndex],x,y,w:6+(i%2)*2,h:5+((i+1)%2)*2,floors,damage:dmg,roofVisible:true};buildings.push(b);let amount;[amount,rng]=randomInt(rng,4,15);const lootKinds:(keyof import('./types.js').Resources)[]=district.kind==='medical'?['medicine','water','food']:district.kind==='industrial'?['materials','fuel','ammo']:['food','water','ammo','materials'];let lk;[lk,rng]=randomInt(rng,0,lootKinds.length);loot.push({id:`loot-${li++}`,kind:lootKinds[lk],amount,searched:0,buildingId:b.id,x:b.x+.6,y:b.y+.3});}}
buildings.push({id:'safehouse',district:'civic',kind:'safehouse',x:0,y:0,w:10,h:8,floors:2,damage:.1,roofVisible:true});return[buildings,loot,rng];}
export function createSurvivors(seed:number,count:number):[Survivor[],number]{const out:Survivor[]=[];let rng=seed;for(let i=0;i<count;i++){let a,r;[a,rng]=randomRange(rng,0,Math.PI*2);[r,rng]=randomRange(rng,1.2,4.5);const x=Math.cos(a)*r,y=Math.sin(a)*r;out.push({id:`s-${i}`,name:names[i%names.length],role:roles[i%roles.length],action:'idle',health:100,stamina:100,infection:0,morale:85,ammo:12+(i%4)*3,carrying:0,threat:0,x,y,targetX:0,targetY:0,facing:a,cooldown:0,kills:0,rescued:0,alive:true,goal:'Secure the safe house',intent:'Assessing the area',confidence:.7,fallback:false,planAgeTicks:0,stuckTicks:0,lastPlanX:x,lastPlanY:y});}return[out,rng];}
export function createZombies(seed:number,count:number):[Zombie[],number]{const out:Zombie[]=[];let rng=seed;for(let i=0;i<count;i++){const ring=17+Math.floor(i/32)*2.8,angle=((i*2.399963229728653)+(seed%97)*.031)%(Math.PI*2);let jitter,speed,variant;[jitter,rng]=randomRange(rng,-.45,.45);[speed,rng]=randomRange(rng,1.2,2.25);[variant,rng]=randomInt(rng,0,6);const rr=ring+jitter,x=Math.cos(angle)*rr,y=Math.sin(angle)*rr;out.push({id:`z-${i}`,action:'wander',health:45+variant*4,speed,facing:angle+Math.PI,variant,targetId:null,x,y,distanceToSafeHouse:Math.hypot(x,y),stagger:0});}return[out,rng];}
export function createBarricades():Barricade[]{const defs:[number,number,number,Barricade['material']][]=[[7,0,0,'metal'],[-7,0,Math.PI,'wood'],[0,6,Math.PI/2,'vehicle'],[0,-6,-Math.PI/2,'wood']];return defs.map(([x,y,angle,material],i)=>({id:`bar-${i}`,x,y,angle,hp:material==='vehicle'?220:material==='metal'?180:130,maxHp:material==='vehicle'?220:material==='metal'?180:130,material}));}
