import type{TowerConfig}from'../config/schema';import{canTraversePlatformEdge,towerMovementEnvelope}from'../generation/solver';import type{TowerObservation}from'./observation';
export interface TowerGraphNode{id:string;kind:'solid'|'oneway'|'moving';x:number;y:number;width:number;height:number;vx:number;neighbors:string[]}
export interface TowerRouteCandidate{platform:TowerGraphNode;riskPermille:number;progress:number;landingMargin:number;movingSpeed:number;reasons:string[]}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function horizontalOverlap(a:{x:number;width:number},b:{x:number;width:number}){return a.x<b.x+b.width&&b.x<a.x+a.width}
function top(p:{y:number;height:number}){return p.y+p.height}
export function buildTowerPlatformGraph(observation:TowerObservation,config:TowerConfig){const envelope=towerMovementEnvelope(config),platforms=observation.platforms,nodes:TowerGraphNode[]=platforms.map(a=>({id:a.id,kind:a.kind,x:a.x,y:a.y,width:a.width,height:a.height,vx:a.vx,neighbors:platforms.filter(b=>b.id!==a.id&&canTraversePlatformEdge(a,b,envelope)).map(b=>b.id).sort()}));return nodes.sort((a,b)=>a.y-b.y||a.id.localeCompare(b.id))}
function routeRisk(candidate:TowerGraphNode,observation:TowerObservation){let risk=0;const reasons:string[]=[];const surfaceY=top(candidate),centerX=candidate.x+Math.floor(candidate.width/2);for(const hazard of observation.hazards){if(!hazard.active)continue;const hazardCenterY=hazard.y+Math.floor(hazard.height/2);if(horizontalOverlap(candidate,hazard)&&Math.abs(hazardCenterY-surfaceY)<=48000){risk+=720;reasons.push('active-hazard')}}for(const enemy of observation.enemies){if(!enemy.active)continue;if(Math.abs(enemy.position.y-surfaceY)<=72000&&Math.abs(enemy.position.x-centerX)<=Math.floor(candidate.width/2)+48000){risk+=180;reasons.push('enemy-pressure')}}for(const projectile of observation.projectiles){if(projectile.owner!=='enemy')continue;if(Math.abs(projectile.position.y-surfaceY)<=52000&&Math.abs(projectile.position.x-centerX)<=Math.floor(candidate.width/2)+36000){risk+=140;reasons.push('projectile-lane')}}const movingSpeed=Math.abs(candidate.vx);if(movingSpeed>0){risk+=Math.min(160,Math.floor(movingSpeed/20));reasons.push('moving-platform')}return{riskPermille:clamp(risk,0,1000),movingSpeed,reasons:[...new Set(reasons)].sort()}}
export function rankTowerPlatformRoutes(observation:TowerObservation,config:TowerConfig,currentId?:string):TowerRouteCandidate[]{const graph=buildTowerPlatformGraph(observation,config),start=graph.find(n=>n.id===currentId)??graph[0];if(!start)return[];return start.neighbors.map(id=>graph.find(n=>n.id===id)!).filter(Boolean).map(platform=>{const risk=routeRisk(platform,observation);return{platform,riskPermille:risk.riskPermille,progress:top(platform)-top(start),landingMargin:Math.max(0,platform.width-observation.player.halfWidth*2),movingSpeed:risk.movingSpeed,reasons:risk.reasons}}).sort((a,b)=>a.riskPermille-b.riskPermille||a.progress-b.progress||b.landingMargin-a.landingMargin||a.platform.id.localeCompare(b.platform.id))}
export function nextTowerPlatform(observation:TowerObservation,config:TowerConfig,currentId?:string){return rankTowerPlatformRoutes(observation,config,currentId)[0]?.platform}