import type{TowerAction,TowerPlatform,TowerState}from'../state/types';import{chooseTowerUpgrade}from'../progression/builds';import{rankTowerPlatformRoutes,type TowerRouteCandidate}from'./graph';import type{TowerObservation}from'./observation';import{detectTowerStuck}from'./stuck';
export interface TowerIntent{mode:'choosing-upgrade'|'evading-projectile'|'evading-hazard'|'engaging-enemy'|'recovering'|'aligning'|'jumping'|'air-control'|'waiting';summary:string;confidence:number;fallbackUsed:boolean;targetPlatformId?:string}
export interface TowerDecision{action:TowerAction;intent:TowerIntent}
function action(move:TowerAction['move']=0,extra:Partial<TowerAction>={}):TowerAction{return{move,jump:false,dash:false,attack:false,ability:false,...extra}}
function moveSign(delta:number):TowerAction['move']{return Math.abs(delta)<4000?0:delta>0?1:-1}
function currentPlatform(obs:TowerObservation,id?:string){return id?obs.platforms.find(p=>p.id===id):undefined}
function launchX(current:TowerPlatform,target:TowerPlatform,halfWidth:number){const safeLeft=current.x+halfWidth+6000,safeRight=current.x+current.width-halfWidth-6000,center=target.x+target.width/2;if(target.x<=current.x+current.width&&target.x+target.width>=current.x)return Math.max(safeLeft,Math.min(safeRight,center));return center<current.x?safeLeft:safeRight}
function incomingProjectile(obs:TowerObservation){return obs.projectiles.filter(x=>x.owner==='enemy').find(x=>Math.abs(x.position.y-obs.player.position.y)<30000&&Math.abs(x.position.x-obs.player.position.x)<65000&&Math.sign(x.velocity.x)===Math.sign(obs.player.position.x-x.position.x))}
function immediateHazard(obs:TowerObservation){const p=obs.player;return obs.hazards.filter(h=>h.active&&Math.abs((h.y+h.height/2)-p.position.y)<42000).sort((a,b)=>Math.abs((a.x+a.width/2)-p.position.x)-Math.abs((b.x+b.width/2)-p.position.x)||a.id.localeCompare(b.id)).find(h=>Math.abs((h.x+h.width/2)-p.position.x)<62000)}
function nearbyEnemy(obs:TowerObservation,reach:number){return obs.enemies.filter(e=>e.active&&Math.abs(e.position.y-obs.player.position.y)<36000&&Math.abs(e.position.x-obs.player.position.x)<=reach).sort((a,b)=>Math.abs(a.position.x-obs.player.position.x)-Math.abs(b.position.x-obs.player.position.x)||a.id.localeCompare(b.id))[0]}
function avoidedActiveHazard(selected:TowerRouteCandidate|undefined,routes:TowerRouteCandidate[]){return !!selected&&routes.some(route=>route.platform.id!==selected.platform.id&&route.riskPermille>selected.riskPermille&&route.reasons.includes('active-hazard'))}
export function chooseTowerAction(state:TowerState,observation:TowerObservation):TowerDecision{
  if(observation.upgradeOffers.length){const selected=chooseTowerUpgrade(state);return{action:action(0,{upgradeChoice:selected?.id}),intent:{mode:'choosing-upgrade',summary:selected?`Selecting ${selected.name}`:'Waiting for a valid upgrade',confidence:1,fallbackUsed:false}}}
  const projectile=incomingProjectile(observation);if(projectile){const away=moveSign(observation.player.position.x-projectile.position.x);return{action:action(away,{jump:observation.player.grounded,dash:!observation.player.grounded&&observation.player.dashCooldown===0}),intent:{mode:'evading-projectile',summary:'Evading an incoming projectile',confidence:.98,fallbackUsed:false}}}
  const hazard=immediateHazard(observation);if(hazard){const center=hazard.x+hazard.width/2,away:TowerAction['move']=center>=observation.player.position.x?-1:1;return{action:action(away,{jump:observation.player.grounded}),intent:{mode:'evading-hazard',summary:`Avoiding ${hazard.kind}`,confidence:.96,fallbackUsed:false}}}
  const enemy=nearbyEnemy(observation,state.config.attackReach+state.build.attackReachBonus);if(enemy){const facing=moveSign(enemy.position.x-observation.player.position.x);return{action:action(facing,{attack:observation.player.attackCooldown===0}),intent:{mode:'engaging-enemy',summary:`Engaging ${enemy.kind}`,confidence:.94,fallbackUsed:false}}}
  if(detectTowerStuck(observation.recentHeights)){const direction:TowerAction['move']=observation.tick%2===0?1:-1;return{action:action(direction,{jump:observation.player.grounded,dash:!observation.player.grounded&&observation.player.dashCooldown===0}),intent:{mode:'recovering',summary:'Breaking a repeated height cycle',confidence:.82,fallbackUsed:true}}}
  let routes:TowerRouteCandidate[]=[],target=currentPlatform(observation,state.ai.targetPlatformId);if(observation.player.grounded){routes=rankTowerPlatformRoutes(observation,state.config,observation.player.groundedPlatformId);target=routes[0]?.platform}else if(!target){routes=rankTowerPlatformRoutes(observation,state.config,observation.player.groundedPlatformId);target=routes[0]?.platform}
  if(!target)return{action:action(),intent:{mode:'waiting',summary:'Waiting for a valid route node',confidence:.6,fallbackUsed:false}};
  const selected=routes.find(route=>route.platform.id===target?.id),safer=avoidedActiveHazard(selected,routes),confidence=Math.max(.72,.95-(selected?.riskPermille??0)/5000),center=target.x+target.width/2;
  if(!observation.player.grounded){const move=moveSign(center-observation.player.position.x),dash=Math.abs(center-observation.player.position.x)>165000&&observation.player.dashCooldown===0&&observation.player.velocity.y>0;return{action:action(move,{dash}),intent:{mode:'air-control',summary:safer?'Holding the safer landing line':'Steering toward the next landing',confidence,fallbackUsed:false,targetPlatformId:target.id}}}
  const support=currentPlatform(observation,observation.player.groundedPlatformId);if(!support)return{action:action(),intent:{mode:'waiting',summary:'Confirming ground support',confidence:.7,fallbackUsed:false,targetPlatformId:target.id}};const desired=launchX(support,target,state.config.playerHalfWidth),delta=desired-observation.player.position.x;if(Math.abs(delta)>12000){const summary=safer?'Choosing safer route around active hazard':target.kind==='moving'&&Math.abs(target.vx)>0?'Timing the moving platform approach':'Aligning with the launch point';return{action:action(moveSign(delta)),intent:{mode:'aligning',summary,confidence,fallbackUsed:false,targetPlatformId:target.id}}}return{action:action(moveSign(center-observation.player.position.x),{jump:true}),intent:{mode:'jumping',summary:safer?'Committing to the safer landing':'Committing to the next platform',confidence,fallbackUsed:false,targetPlatformId:target.id}}
}