import type{AntColonyConfig}from '../config/schema';
export type AntLifecycle='active'|'result'|'intermission'|'quarantined';
export type AntRole='worker'|'scout'|'nurse'|'digger'|'soldier';
export type AntTask='idle'|'forage'|'return'|'nurse'|'dig'|'guard'|'fight'|'rest'|'explore';
export type ColonyStrategy='foraging'|'expansion'|'defense'|'recovery'|'brood-boom';
export type ProgressBand='founding'|'growing'|'established'|'thriving'|'ascendant';
export type Season='spring'|'summer'|'autumn'|'winter';
export type Weather='clear'|'rain'|'heat'|'drought';
export type TileCode=0|1|2|3|4|5;
export interface AntState{id:number;role:AntRole;x:number;y:number;health:number;energy:number;carryingFood:number;task:AntTask;goalCell:number|null;intent:string;confidence:number;stuckTicks:number;lastCell:number;ageTicks:number;bias:number}
export interface BroodState{id:number;stage:'egg'|'larva'|'pupa';ageTicks:number;health:number}
export interface PredatorState{id:number;kind:'beetle'|'spider';x:number;y:number;health:number;intent:string}
export interface PheromoneFields{home:number[];food:number[];alarm:number[];excavation:number[]}
export interface AntWorldState{tiles:TileCode[];food:number[];moisture:number[];discovered:number[];pheromones:PheromoneFields;entrance:number;nestCenter:number}
export interface ColonySummary{foodStore:number;waterStore:number;tunnelsDug:number;foodDelivered:number;predatorsDefeated:number;antsBorn:number;antsLost:number;eggsLaid:number;strategy:ColonyStrategy;strategyReason:string;progressBand:ProgressBand;threat:number;meaningfulEventTick:number}
export interface QueenState{health:number;eggsLaid:number;lastEggTick:number}
export interface AntInfluenceCommand{id:string;type:string;scheduledTick:number;magnitude:number;payload:Record<string,unknown>}
export interface AntInfluenceState{enabled:boolean;emergencyDisabled:boolean;scheduled:AntInfluenceCommand[];appliedIds:string[];cooldowns:Record<string,number>;activeModifiers:Record<string,{untilTick:number;magnitude:number}>}
export interface AntRunResult{reason:'ascension'|'extinction'|'stagnation'|'quarantine';tick:number;population:number;foodStore:number;tunnelsDug:number;score:number;finalChecksum:string}
export interface AntColonyState{schemaVersion:1;deterministicVersion:'ant-colony-v1';runId:string;runIndex:number;seed:string;tick:number;lifecycle:AntLifecycle;config:AntColonyConfig;world:AntWorldState;queen:QueenState;ants:AntState[];brood:BroodState[];predators:PredatorState[];colony:ColonySummary;influence:AntInfluenceState;day:number;season:Season;weather:Weather;result?:AntRunResult;intermissionRemaining:number;nextAntId:number;nextBroodId:number;nextPredatorId:number}
export interface AntEvent{seq:number;tick:number;type:string;data?:Record<string,unknown>}
export type AntAction={kind:'move';cell:number;task:AntTask;intent:string;confidence:number}|{kind:'pickup'|'deposit'|'rest';task:AntTask;intent:string;confidence:number}|{kind:'dig';cell:number;task:AntTask;intent:string;confidence:number};
export interface StepOutput{state:AntColonyState;events:Array<{type:string;data?:Record<string,unknown>}>}
