import type{SnakeConfig}from '../../../../packages/game-contracts/src/index';import{NamedRng}from '../../../../packages/seeded-rng/src/index';import type{SnakeSignals}from '../../../../packages/telemetry-contracts/src/index';import{parseSnakeConfig}from '../config/schema';import{createInitialState}from '../index';import{chooseFallbackAction}from '../ai/fallback';import{applyAction}from '../rules/step';import type{SnakeEvent,SnakeState}from '../state/types';
export class SnakeRuntime{events:SnakeEvent[]=[];state:SnakeState;rng:NamedRng;private seq:number;private constructor(public config:SnakeConfig,public seed:string,state?:SnakeState,rng?:NamedRng,nextEventSeq=0){this.seq=nextEventSeq;this.rng=rng??NamedRng.fromSeed(seed);this.state=state??createInitialState(config,seed,`run-${seed}`,this.rng);if(!state)this.emit('initialized',{seed})}
static create(c:Partial<SnakeConfig>&Pick<SnakeConfig,'width'|'height'|'targetLength'>,seed:string){return new SnakeRuntime(parseSnakeConfig(c),seed)}
static restore(config:SnakeConfig,seed:string,state:SnakeState,rng:NamedRng,nextEventSeq=0){return new SnakeRuntime(config,seed,state,rng,nextEventSeq)}
private emit(type:string,data?:Record<string,unknown>){this.events.push({seq:this.seq++,tick:this.state.tick,type,data})}
step(){if(this.state.lifecycle==='result'){this.state.lifecycle='intermission';this.emit('intermission');return this.state}if(this.state.lifecycle==='intermission'){this.state.intermissionRemaining--;if(this.state.intermissionRemaining<=0)this.restart(`${this.seed}:restart:${this.state.tick}`);return this.state}const chosen=chooseFallbackAction(this.state);const action=chosen??{direction:this.state.snake.direction};const out=applyAction(this.state,action,this.rng);this.state=out.state;for(const e of out.events)this.emit(e.type,e.data);return this.state}
restart(seed=this.seed){this.seed=seed;this.rng=NamedRng.fromSeed(seed);this.state=createInitialState(this.config,seed,`run-${seed}`,this.rng);this.emit('restart',{seed});return this.state}
getNextEventSequence(){return this.seq}
signals():SnakeSignals{return{length:this.state.snake.body.length,occupancy:this.state.occupancy,danger:0,progress:this.state.snake.body.length/this.config.targetLength,meaningfulEventAge:this.state.tick-this.state.meaningfulEventTick,lifecycle:this.state.lifecycle}}
}
