import type{BoardProfile,SnakeConfig}from '../../../../packages/game-contracts/src/index';import{NamedRng}from '../../../../packages/seeded-rng/src/index';import{checksum}from '../../../../packages/replay/src/index';import type{SnakeSignals}from '../../../../packages/telemetry-contracts/src/index';import{parseSnakeConfig}from '../config/schema';import{createInitialState}from '../index';import{safeProductionDecision}from '../ai/production';import{applyDueInfluence}from '../influence/apply';import{applyAction,applyStagnationTerminal}from '../rules/step';import type{ProgressionBand,SnakeEvent,SnakeState}from '../state/types';
function bandFor(s:SnakeState):ProgressionBand{const ratio=s.snake.body.length/s.config.targetLength;if(ratio>=1)return'conquest';if(ratio>=0.7)return'major';if(ratio>=0.4)return'medium';return'small'}
function decisionHash(s:SnakeState){return checksum({head:s.snake.body[0],body:s.snake.body,food:s.food,mode:s.ai.mode,influence:s.influence})}
export class SnakeRuntime{events:SnakeEvent[]=[];state:SnakeState;rng:NamedRng;private seq:number;private constructor(public config:SnakeConfig,public seed:string,state?:SnakeState,rng?:NamedRng,nextEventSeq=0){this.seq=nextEventSeq;this.rng=rng??NamedRng.fromSeed(seed);this.state=state??createInitialState(config,seed,`run-${seed}`,this.rng);if(!state)this.emit('initialized',{seed,profile:config.profile})}
static create(c:Partial<SnakeConfig>&Pick<SnakeConfig,'width'|'height'|'targetLength'>,seed:string){return new SnakeRuntime(parseSnakeConfig(c),seed)}
static restore(config:SnakeConfig,seed:string,state:SnakeState,rng:NamedRng,nextEventSeq=0){return new SnakeRuntime(config,seed,state,rng,nextEventSeq)}
private emit(type:string,data?:Record<string,unknown>){this.events.push({seq:this.seq++,tick:this.state.tick,type,data})}
step(){if(this.state.lifecycle==='result'){this.state.lifecycle='intermission';this.emit('intermission');return this.state}if(this.state.lifecycle==='intermission'){this.state.intermissionRemaining--;if(this.state.intermissionRemaining<=0)this.restart(`${this.seed}:restart:${this.state.tick}`);return this.state}const influence=applyDueInfluence(this.state,this.rng);this.state=influence.state;for(const e of influence.events)this.emit(e.type,e.data);const hash=decisionHash(this.state),recent=this.state.ai.recentHashes;const occurrences=recent.filter(x=>x===hash).length;this.state.ai.repeatCount=occurrences;const decision=safeProductionDecision(this.state);this.state.ai.mode=decision.intent.mode;this.state.ai.confidence=decision.intent.confidence;this.state.ai.explanation=decision.intent.explanation;this.state.ai.decisions++;this.state.ai.nodeExpansions+=decision.intent.nodeExpansions;if(decision.intent.fallbackUsed)this.state.ai.fallbackCount++;if(decision.intent.mode==='replan')this.state.ai.replans++;this.state.ai.recentHashes=[...recent,hash].slice(-32);const action=decision.action??{direction:this.state.snake.direction};const previousBand=this.state.progressionBand;const out=applyAction(this.state,action,this.rng);this.state=out.state;for(const e of out.events)this.emit(e.type,e.data);if(!this.state.result&&this.state.tick-this.state.meaningfulEventTick>=this.config.noProgressTicks){const stalled=applyStagnationTerminal(this.state);this.state=stalled.state;for(const e of stalled.events)this.emit(e.type,e.data)}const nextBand=bandFor(this.state);if(nextBand!==previousBand){this.state.progressionBand=nextBand;this.state.lastMilestoneLength=this.state.snake.body.length;this.emit('milestone',{band:nextBand,length:this.state.snake.body.length})}this.emit('ai-intent',{mode:this.state.ai.mode,confidence:this.state.ai.confidence});return this.state}
restart(seed=this.seed){this.seed=seed;this.rng=NamedRng.fromSeed(seed);this.state=createInitialState(this.config,seed,`run-${seed}`,this.rng);this.emit('restart',{seed,profile:this.config.profile});return this.state}
drainEvents(limit=10000){if(!Number.isInteger(limit)||limit<0)throw new RangeError('limit');return this.events.splice(0,Math.min(limit,this.events.length))}
getNextEventSequence(){return this.seq}
signals():SnakeSignals{return{length:this.state.snake.body.length,occupancy:this.state.occupancy,danger:this.state.ai.mode==='escape-hazard'||this.state.ai.mode==='fallback-survival'?1:0,progress:this.state.snake.body.length/this.config.targetLength,meaningfulEventAge:this.state.tick-this.state.meaningfulEventTick,lifecycle:this.state.lifecycle}}
}
export type{BoardProfile};
