import type{DungeonEnemy,DungeonRoom,DungeonState}from '../state/types';

export type DungeonBiome='ancient-crypt'|'infernal-forge'|'fungal-caverns'|'flooded-ruins'|'frozen-vault'|'arcane-library'|'void-depths';
export type DungeonRoomArchetype='corridor'|'combat'|'treasure'|'shrine'|'crypt'|'library'|'forge'|'prison'|'ritual'|'boss'|'sanctuary';
export type DungeonAnimationState='idle'|'advance'|'attack'|'cast'|'leap'|'guard'|'stagger'|'dead'|'boss-attack';
export type DungeonTacticalRole='swarm'|'controller'|'caster'|'flanker'|'ambusher'|'boss';

export interface DungeonWorldTile{cell:number;worldX:number;worldY:number;isoX:number;isoY:number;elevation:number;walkable:boolean;visible:boolean;room:DungeonRoomArchetype;material:string;edge:boolean}
export interface DungeonWorldProp{id:string;cell:number;kind:'pillar'|'rubble'|'statue'|'bookshelf'|'torch'|'altar'|'bones'|'mushroom'|'chain'|'crystal'|'ice-spire'|'urn';worldX:number;worldY:number;elevation:number;variant:number}
export interface DungeonWorldLight{id:string;cell:number;kind:'torch'|'candle'|'crystal'|'lava'|'rune'|'boss';intensity:number;radius:number;worldX:number;worldY:number;elevation:number}
export interface DungeonWorldInteractable{id:string;cell:number;kind:'entrance'|'sigil'|'gate'|'shrine'|'chest'|'boss';state:'active'|'open'|'spent'|'sealed'|'defeated';worldX:number;worldY:number;elevation:number}
export interface DungeonWorldDirector{mode:'exploration'|'danger'|'combat'|'boss'|'near-death'|'result';cameraDistance:number;cameraPitch:number;lookAhead:number;fogDensity:number;lightState:string;musicState:string;shakePermille:number}
export interface DungeonWorldPresentation{version:1;biome:DungeonBiome;paletteId:string;tiles:DungeonWorldTile[];props:DungeonWorldProp[];lights:DungeonWorldLight[];interactables:DungeonWorldInteractable[];director:DungeonWorldDirector}

interface PublicCell{cell:number;walkable:boolean;visible:boolean;objective:null|'entrance'|'sigil'|'gate'|'shrine'|'chest'|'boss'}

const BIOMES:DungeonBiome[]=['ancient-crypt','infernal-forge','fungal-caverns','flooded-ruins','frozen-vault','arcane-library','void-depths'];
const PROP_CAP=96,LIGHT_CAP=32;
const hash=(value:number,salt:number)=>{let x=(value^salt)>>>0;x=Math.imul(x^x>>>16,0x45d9f3b);x=Math.imul(x^x>>>16,0x45d9f3b);return(x^x>>>16)>>>0};
const worldPoint=(cell:number,width:number,elevation=0)=>{const x=cell%width,y=Math.floor(cell/width);return{worldX:x,worldY:y,isoX:x-y,isoY:(x+y)*.5-elevation,elevation}};
const objectiveRoom=(objective:PublicCell['objective']):DungeonRoomArchetype=>objective==='chest'?'treasure':objective==='shrine'?'shrine':objective==='boss'||objective==='gate'?'boss':objective==='sigil'?'ritual':objective==='entrance'?'sanctuary':'corridor';
function biomeFor(floor:number,theme:string):DungeonBiome{const normalized=theme.toLowerCase();for(const biome of BIOMES)if(normalized.includes(biome.split('-')[0]))return biome;return BIOMES[(Math.max(1,floor)-1)%BIOMES.length]}
function materialFor(biome:DungeonBiome,walkable:boolean){if(!walkable)return`${biome}:wall`;return`${biome}:floor`}
function roomContains(room:DungeonRoom,cell:number,width:number){const x=cell%width,y=Math.floor(cell/width);return x>=room.x&&x<room.x+room.width&&y>=room.y&&y<room.y+room.height}
function roomArchetype(state:DungeonState,cell:PublicCell):DungeonRoomArchetype{if(cell.objective)return objectiveRoom(cell.objective);const room=state.floor.rooms.find(candidate=>roomContains(candidate,cell.cell,state.floor.width));if(!room)return'corridor';if(roomContains(room,state.floor.bossCell,state.floor.width)||roomContains(room,state.floor.gate,state.floor.width))return'boss';if(roomContains(room,state.floor.chest,state.floor.width))return'treasure';if(roomContains(room,state.floor.shrine,state.floor.width))return'shrine';if(roomContains(room,state.floor.sigil,state.floor.width))return'ritual';if(roomContains(room,state.floor.entrance,state.floor.width))return'sanctuary';const roll=hash(room.id,state.floorNumber*7919)%100;return roll<18?'crypt':roll<31?'library':roll<43?'forge':roll<54?'prison':'combat'}
function elevationFor(cell:number,floor:number,walkable:boolean){if(!walkable)return 2;const roll=hash(cell,floor*104729)%24;return roll===0?1:0}
function propKind(biome:DungeonBiome,roll:number):DungeonWorldProp['kind']{const sets:Record<DungeonBiome,DungeonWorldProp['kind'][]>= {'ancient-crypt':['bones','urn','statue','pillar','torch'],'infernal-forge':['chain','pillar','rubble','torch','altar'],'fungal-caverns':['mushroom','crystal','rubble','urn','mushroom'],'flooded-ruins':['statue','pillar','rubble','urn','torch'],'frozen-vault':['ice-spire','crystal','pillar','statue','urn'],'arcane-library':['bookshelf','crystal','altar','pillar','torch'],'void-depths':['crystal','altar','statue','rubble','pillar']};const values=sets[biome];return values[roll%values.length]}
function lightKind(biome:DungeonBiome):DungeonWorldLight['kind']{return biome==='infernal-forge'?'lava':biome==='fungal-caverns'||biome==='frozen-vault'||biome==='void-depths'?'crystal':biome==='arcane-library'?'rune':'torch'}
function director(state:DungeonState,visibleEnemies:number,bossVisible:boolean):DungeonWorldDirector{const hp=state.hero.hp/Math.max(1,state.hero.maxHp);const result=state.lifecycle==='run-result'||state.lifecycle==='chapter-result'||state.lifecycle==='floor-result';const mode:DungeonWorldDirector['mode']=result?'result':bossVisible?'boss':hp<.28?'near-death':visibleEnemies>=3?'combat':visibleEnemies>0?'danger':'exploration';return{mode,cameraDistance:mode==='boss'?13:mode==='combat'?11:10,cameraPitch:48,lookAhead:mode==='exploration'?2.2:1.2,fogDensity:mode==='boss'?.34:.24,lightState:mode==='boss'?'boss-contrast':mode==='near-death'?'low-health-pulse':'biome-ambient',musicState:mode==='boss'?`boss-phase-${Math.max(1,state.enemies.find(e=>e.kind==='chapter-boss'&&e.alive)?.phase??1)}`:mode==='combat'?'combat':mode==='danger'?'danger':mode==='near-death'?'low-health-tension':mode==='result'?'result':'exploration',shakePermille:mode==='boss'?120:mode==='combat'?70:mode==='near-death'?45:0}}

export function enemyTacticalRole(kind:DungeonEnemy['kind']):DungeonTacticalRole{return kind==='mireling'?'swarm':kind==='bone-warden'?'controller':kind==='ember-seer'?'caster':kind==='void-hound'?'flanker':kind==='reliquary-mimic'?'ambusher':'boss'}
export function enemyAnimation(kind:DungeonEnemy['kind'],telegraph:DungeonEnemy['telegraph'],cooldown:number):DungeonAnimationState{if(kind==='chapter-boss'&&telegraph)return'boss-attack';if(telegraph==='ranged')return'cast';if(telegraph==='leap')return'leap';if(telegraph==='melee'||telegraph==='boss')return'attack';if(kind==='bone-warden'&&cooldown>0)return'guard';return cooldown>0?'idle':'advance'}
export function entityWorldPoint(cell:number,width:number,floor:number){const elevation=elevationFor(cell,floor,true);return worldPoint(cell,width,elevation)}

export function buildDungeonWorldPresentation(state:DungeonState,cells:PublicCell[],visibleEnemyCount:number,bossVisible:boolean):Readonly<DungeonWorldPresentation>{const biome=biomeFor(state.floorNumber,state.influence.themeId);const known=new Set(cells.map(cell=>cell.cell));const tiles=cells.slice(0,640).map(cell=>{const elevation=elevationFor(cell.cell,state.floorNumber,cell.walkable),point=worldPoint(cell.cell,state.floor.width,elevation),neighbours=[cell.cell-1,cell.cell+1,cell.cell-state.floor.width,cell.cell+state.floor.width],edge=!cell.walkable||neighbours.some(n=>!known.has(n));return{cell:cell.cell,...point,walkable:cell.walkable,visible:cell.visible,room:roomArchetype(state,cell),material:materialFor(biome,cell.walkable),edge}});
const props:DungeonWorldProp[]=[];const lights:DungeonWorldLight[]=[];for(const tile of tiles){if(!tile.walkable||!tile.visible)continue;const roll=hash(tile.cell,state.floorNumber*31337);if(props.length<PROP_CAP&&roll%11===0){const kind=propKind(biome,roll>>>5);props.push({id:`prop-${state.floorNumber}-${tile.cell}`,cell:tile.cell,kind,worldX:tile.worldX,worldY:tile.worldY,elevation:tile.elevation,variant:(roll>>>9)%4})}if(lights.length<LIGHT_CAP&&roll%23===0){lights.push({id:`light-${state.floorNumber}-${tile.cell}`,cell:tile.cell,kind:lightKind(biome),intensity:700+(roll%301),radius:3+(roll%3),worldX:tile.worldX,worldY:tile.worldY,elevation:tile.elevation+.8})}}
const interactables:DungeonWorldInteractable[]=cells.filter(cell=>cell.objective!==null).slice(0,16).map(cell=>{const point=entityWorldPoint(cell.cell,state.floor.width,state.floorNumber),kind=cell.objective!;const stateLabel:DungeonWorldInteractable['state']=kind==='chest'&&state.floorProgress.chestOpened?'open':kind==='shrine'&&state.floorProgress.shrineUsed?'spent':kind==='boss'&&state.floorProgress.guardianDefeated?'defeated':kind==='gate'&&!state.floorProgress.sigilCollected?'sealed':'active';return{id:`${kind}-${cell.cell}`,cell:cell.cell,kind,state:stateLabel,...point}});
return Object.freeze({version:1 as const,biome,paletteId:`${biome}:${state.influence.themeId||'default'}`,tiles:Object.freeze(tiles) as unknown as DungeonWorldTile[],props:Object.freeze(props) as unknown as DungeonWorldProp[],lights:Object.freeze(lights) as unknown as DungeonWorldLight[],interactables:Object.freeze(interactables) as unknown as DungeonWorldInteractable[],director:Object.freeze(director(state,visibleEnemyCount,bossVisible))})}
