import{isDigest}from '../../release-governance/src/hashes';
export interface ProviderChecks{authentication:boolean;reconnect:boolean;duplicates:boolean;reversal:boolean;outage:boolean;rateLimit:boolean}
export interface ProviderEvidence{provider:string;candidateChecksum:string;environment:'fixture'|'staging'|'production-equivalent'|'production';credentialed:boolean;productionEquivalent:boolean;source:'ci'|'fixture'|'external-signed';collectedAtMs:number;expiresAtMs:number;evidenceDigest:string;checks:ProviderChecks}
export interface ProviderEvidenceContext{expectedCandidateChecksum:string;nowMs:number;requiredProviders:string[]}
export interface EvidenceGateResult{status:'pass'|'blocked';blockers:string[]}
export function assessProviderEvidence(records:ProviderEvidence[],context:ProviderEvidenceContext):EvidenceGateResult{
  const blockers:string[]=[];for(const provider of context.requiredProviders){const matches=records.filter(record=>record.provider===provider);if(!matches.length){blockers.push(`${provider}:missing`);continue}if(matches.length>1)blockers.push(`${provider}:duplicate`);for(const record of matches){if(record.candidateChecksum!==context.expectedCandidateChecksum)blockers.push(`${provider}:candidate-mismatch`);if(record.expiresAtMs<context.nowMs)blockers.push(`${provider}:expired`);if(!isDigest(record.evidenceDigest))blockers.push(`${provider}:invalid-digest`);if(!record.credentialed)blockers.push(`${provider}:not-credentialed`);if(!record.productionEquivalent||!['production-equivalent','production'].includes(record.environment))blockers.push(`${provider}:not-production-equivalent`);if(record.source!=='external-signed')blockers.push(`${provider}:not-external-signed`);for(const[key,value]of Object.entries(record.checks))if(value!==true)blockers.push(`${provider}:${key}`)}}return{status:blockers.length?'blocked':'pass',blockers:[...new Set(blockers)].sort()};
}
export type SafetyAttestationKind='security'|'privacy'|'moderation'|'accessibility'|'audiovisual'|'assets'|'supply-chain'|string;
export interface SafetyAttestation{kind:SafetyAttestationKind;candidateChecksum:string;environment:'ci'|'staging'|'production-equivalent'|'production';source:'ci'|'synthetic'|'external-signed';status:'pass'|'fail'|'blocked';collectedAtMs:number;expiresAtMs:number;evidenceDigest:string;reviewer:string;blockingFindings:number;details:Record<string,unknown>}
export interface SafetyContext{expectedCandidateChecksum:string;nowMs:number;requiredKinds:string[]}
export function assessSafetyAttestations(records:SafetyAttestation[],context:SafetyContext):EvidenceGateResult{
  const blockers:string[]=[];for(const kind of context.requiredKinds){const matches=records.filter(record=>record.kind===kind);if(!matches.length){blockers.push(`${kind}:missing`);continue}if(matches.length>1)blockers.push(`${kind}:duplicate`);for(const record of matches){if(record.candidateChecksum!==context.expectedCandidateChecksum)blockers.push(`${kind}:candidate-mismatch`);if(record.expiresAtMs<context.nowMs)blockers.push(`${kind}:expired`);if(!isDigest(record.evidenceDigest))blockers.push(`${kind}:invalid-digest`);if(!['production-equivalent','production'].includes(record.environment))blockers.push(`${kind}:not-production-equivalent`);if(record.source!=='external-signed')blockers.push(`${kind}:not-external-signed`);if(!record.reviewer)blockers.push(`${kind}:missing-reviewer`);if(record.status!=='pass')blockers.push(`${kind}:status-${record.status}`);if(record.blockingFindings>0)blockers.push(`${kind}:blocking-findings`)}}return{status:blockers.length?'blocked':'pass',blockers:[...new Set(blockers)].sort()};
}
