import{isDigest}from '../../release-governance/src/hashes';
export interface CapacitySource{kind:'ci-reference'|'production-reference';attested:boolean;hardwareRef?:string;digest?:string}
export interface CapacitySample{atMs:number;tickMs:number;aiMs:number;renderMs:number;snapshotMs:number;restoreMs:number;queueRatio:number;memoryMb:number}
export interface CapacityBudgets{tickP99Ms:number;aiP99Ms:number;renderP99Ms:number;snapshotP99Ms:number;restoreP99Ms:number;queueMaxRatio:number;memorySlopeMbPerHour:number;minHeadroomRatio:number}
export interface CapacityInput{source:CapacitySource;samples:CapacitySample[];budgets:CapacityBudgets}
interface LatencyMetric{p50:number;p95:number;p99:number;max:number;budget:number;headroomRatio:number;pass:boolean}
export interface CapacityResult{performancePass:boolean;productionReferenceSatisfied:boolean;blockers:string[];metrics:{tick:LatencyMetric;ai:LatencyMetric;render:LatencyMetric;snapshot:LatencyMetric;restore:LatencyMetric;queue:{max:number;budget:number;headroomRatio:number;pass:boolean};memory:{start:number;end:number;max:number;slopePerHour:number;budgetSlope:number;pass:boolean}}}
function invalid(message:string){const error=new Error(message);Object.assign(error,{code:'INVALID_CAPACITY'});return error}
function percentile(values:number[],q:number){const sorted=[...values].sort((a,b)=>a-b),index=Math.min(sorted.length-1,Math.max(0,Math.ceil(sorted.length*q)-1));return sorted[index]}
function latency(values:number[],budget:number,minHeadroom:number):LatencyMetric{const p99=percentile(values,.99),headroomRatio=(budget-p99)/budget;return{p50:percentile(values,.5),p95:percentile(values,.95),p99,max:Math.max(...values),budget,headroomRatio,pass:p99<=budget&&headroomRatio>=minHeadroom}}
function slopePerHour(samples:CapacitySample[],key:'memoryMb'){if(samples.length<2)return 0;const x=samples.map(sample=>sample.atMs/3600000),y=samples.map(sample=>sample[key]),xm=x.reduce((a,b)=>a+b,0)/x.length,ym=y.reduce((a,b)=>a+b,0)/y.length;let numerator=0,denominator=0;for(let i=0;i<x.length;i++){numerator+=(x[i]-xm)*(y[i]-ym);denominator+=(x[i]-xm)**2}return denominator===0?0:numerator/denominator}
export function evaluateCapacity(input:CapacityInput):CapacityResult{
  if(!input.samples.length)throw invalid('samples');for(const sample of input.samples)for(const value of Object.values(sample))if(!Number.isFinite(value))throw invalid('sample');for(const value of Object.values(input.budgets))if(!Number.isFinite(value)||value<=0)throw invalid('budget');if(input.samples.some(sample=>sample.queueRatio<0||sample.queueRatio>1))throw invalid('queue ratio');
  const b=input.budgets,tick=latency(input.samples.map(s=>s.tickMs),b.tickP99Ms,b.minHeadroomRatio),ai=latency(input.samples.map(s=>s.aiMs),b.aiP99Ms,b.minHeadroomRatio),render=latency(input.samples.map(s=>s.renderMs),b.renderP99Ms,b.minHeadroomRatio),snapshot=latency(input.samples.map(s=>s.snapshotMs),b.snapshotP99Ms,b.minHeadroomRatio),restore=latency(input.samples.map(s=>s.restoreMs),b.restoreP99Ms,b.minHeadroomRatio);
  const queueMax=Math.max(...input.samples.map(s=>s.queueRatio)),queueHeadroom=(b.queueMaxRatio-queueMax)/b.queueMaxRatio,queue={max:queueMax,budget:b.queueMaxRatio,headroomRatio:queueHeadroom,pass:queueMax<=b.queueMaxRatio&&queueHeadroom>=b.minHeadroomRatio};const memorySlope=slopePerHour(input.samples,'memoryMb'),memory={start:input.samples[0].memoryMb,end:input.samples[input.samples.length-1].memoryMb,max:Math.max(...input.samples.map(s=>s.memoryMb)),slopePerHour:memorySlope,budgetSlope:b.memorySlopeMbPerHour,pass:memorySlope<=b.memorySlopeMbPerHour};
  const blockers:string[]=[];for(const[name,metric]of Object.entries({tick,ai,render,snapshot,restore}))if(!metric.pass)blockers.push(`${name}-budget`);if(!queue.pass)blockers.push('queue-budget');if(!memory.pass)blockers.push('memory-slope');
  const productionReferenceSatisfied=input.source.kind==='production-reference'&&input.source.attested===true&&Boolean(input.source.hardwareRef)&&Boolean(input.source.digest)&&isDigest(input.source.digest!);return{performancePass:blockers.length===0,productionReferenceSatisfied,blockers,metrics:{tick,ai,render,snapshot,restore,queue,memory}};
}
