import{isDigest}from '../../release-governance/src/hashes';
export const MANDATORY_DRILLS=['provider-outage','moderation-outage','entitlement-outage','audit-outage','disable-interactions','disable-public-text','simulation-failure','renderer-failure','audio-failure','gateway-failure','persistence-failure','black-output','frozen-output','wrong-scene','silent-output','verified-restore','older-snapshot-fallback','divergence-quarantine','credential-rotation','credential-revocation','config-rollback','content-rollback','deployment-rollback','safe-intermission','emergency-halt','alert-escalation']as const;
export type MandatoryDrillId=typeof MANDATORY_DRILLS[number];
export interface DrillRecord{id:string;candidateChecksum:string;environment:'ci'|'staging'|'production-equivalent'|'production';source:'synthetic'|'ci'|'external-signed';owner:string;witness:string;runbook:string;startedAtMs:number;endedAtMs:number;status:'pass'|'fail'|'blocked';evidenceDigest:string;automatedActionsVerified:boolean;outputVerified:boolean;observations?:Record<string,unknown>}
export interface DrillContext{expectedCandidateChecksum:string}
export interface DrillAssessment{implementationStatus:'pass'|'blocked';productionStatus:'pass'|'blocked';completed:number;missing:string[];duplicates:string[];implementationBlockers:string[];productionBlockers:string[]}
function unique(values:string[]){return[...new Set(values)].sort()}
function implementationIssues(record:DrillRecord,context:DrillContext):string[]{const issues:string[]=[];if(record.candidateChecksum!==context.expectedCandidateChecksum)issues.push(`${record.id}:candidate-mismatch`);if(!record.owner)issues.push(`${record.id}:missing-owner`);if(!record.runbook)issues.push(`${record.id}:missing-runbook`);if(!Number.isFinite(record.startedAtMs)||!Number.isFinite(record.endedAtMs)||record.endedAtMs<=record.startedAtMs)issues.push(`${record.id}:invalid-duration`);if(record.status!=='pass')issues.push(`${record.id}:status-${record.status}`);if(!isDigest(record.evidenceDigest))issues.push(`${record.id}:invalid-digest`);if(!record.automatedActionsVerified)issues.push(`${record.id}:automated-actions`);if(!record.outputVerified)issues.push(`${record.id}:output-verification`);return issues}
export function assessDrillProgramme(records:DrillRecord[],context:DrillContext):DrillAssessment{
  const missing:string[]=[],duplicates:string[]=[],implementationBlockers:string[]=[],productionBlockers:string[]=[];let completed=0;
  for(const id of MANDATORY_DRILLS){const matches=records.filter(record=>record.id===id);if(!matches.length){missing.push(id);continue}if(matches.length>1)duplicates.push(id);let hasImplementationPass=false;for(const record of matches){const issues=implementationIssues(record,context);implementationBlockers.push(...issues);if(!issues.length)hasImplementationPass=true;if(!['production-equivalent','production'].includes(record.environment))productionBlockers.push(`${id}:not-production-equivalent`);if(record.source!=='external-signed')productionBlockers.push(`${id}:not-external-signed`);if(!record.witness)productionBlockers.push(`${id}:missing-witness`);productionBlockers.push(...issues)}if(hasImplementationPass)completed++}
  const known=new Set<string>(MANDATORY_DRILLS);for(const record of records)if(!known.has(record.id))implementationBlockers.push(`${record.id}:unknown-drill`);
  implementationBlockers.push(...missing.map(id=>`${id}:missing`),...duplicates.map(id=>`${id}:duplicate`));productionBlockers.push(...missing.map(id=>`${id}:missing`),...duplicates.map(id=>`${id}:duplicate`));const impl=unique(implementationBlockers),prod=unique(productionBlockers);return{implementationStatus:impl.length?'blocked':'pass',productionStatus:prod.length?'blocked':'pass',completed,missing:unique(missing),duplicates:unique(duplicates),implementationBlockers:impl,productionBlockers:prod};
}
