import{isDigest}from '../../release-governance/src/hashes';
export interface EnduranceEvidence{candidateChecksum:string;source:'synthetic'|'staging'|'production';realElapsed:boolean;startedAtMs:number;endedAtMs:number;samples:number;resourceSlopes:{memoryMbPerHour:number;handlesPerHour:number;queuePerHour:number};limits:{memoryMbPerHour:number;handlesPerHour:number;queuePerHour:number};duplicateEffects:number;replayDivergences:number;unresolvedOutputFailures:number;manualCommonRecoveries:number;privateExposures:number;crashLoops:number;evidenceDigest:string}
export interface EnduranceContext{expectedCandidateChecksum?:string}
export interface EnduranceAssessment{status:'pass'|'blocked'|'fail';elapsedHours:number;blockers:string[];integrityFailures:string[]}
export function assessEndurance(evidence:EnduranceEvidence,requiredHours=72,context:EnduranceContext={}):EnduranceAssessment{
  if(!Number.isFinite(requiredHours)||requiredHours<=0)throw new RangeError('requiredHours');const elapsedHours=(evidence.endedAtMs-evidence.startedAtMs)/3600000,blockers:string[]=[],integrityFailures:string[]=[];
  if(context.expectedCandidateChecksum&&evidence.candidateChecksum!==context.expectedCandidateChecksum)blockers.push('candidate-mismatch');if(!isDigest(evidence.evidenceDigest))blockers.push('invalid-evidence-digest');if(evidence.source==='synthetic'||!evidence.realElapsed)blockers.push('real-elapsed-evidence');if(!Number.isFinite(elapsedHours)||elapsedHours<requiredHours)blockers.push('minimum-duration');if(!Number.isInteger(evidence.samples)||evidence.samples<2)blockers.push('insufficient-samples');
  if(evidence.resourceSlopes.memoryMbPerHour>evidence.limits.memoryMbPerHour)integrityFailures.push('memory-slope');if(evidence.resourceSlopes.handlesPerHour>evidence.limits.handlesPerHour)integrityFailures.push('handles-slope');if(evidence.resourceSlopes.queuePerHour>evidence.limits.queuePerHour)integrityFailures.push('queue-slope');if(evidence.duplicateEffects>0)integrityFailures.push('duplicate-effects');if(evidence.replayDivergences>0)integrityFailures.push('replay-divergence');if(evidence.unresolvedOutputFailures>0)integrityFailures.push('unresolved-output-failure');if(evidence.manualCommonRecoveries>0)integrityFailures.push('manual-common-recovery');if(evidence.privateExposures>0)integrityFailures.push('private-exposure');if(evidence.crashLoops>0)integrityFailures.push('crash-loop');
  const all=[...new Set([...blockers,...integrityFailures])].sort();return{status:integrityFailures.length?'fail':blockers.length?'blocked':'pass',elapsedHours,blockers:all,integrityFailures:[...new Set(integrityFailures)].sort()};
}
