import{NamedRng,type RngSnapshot}from'../../../../packages/seeded-rng/src/index';import{checksum}from'../../../../packages/replay/src/index';import{parseZombieConfig,type ZombieConfig}from'../config/schema';import{generateZombieWorld}from'../generation/world';import{assertZombieInvariants,stepZombieRules}from'../rules/step';import type{SurvivorRole,ZombieEvent,ZombieState}from'../state/types';
const roles:SurvivorRole[]=['scout','builder','medic','guard'];
function initialState(config:ZombieConfig,seed:string,restartIndex:number,rng:NamedRng):ZombieState{const generated=generateZombieWorld(config,rng);const spawnCells=generated.world.baseCells.filter(cell=>cell!==generated.world.coreCell).slice(0,config.initialSurvivors);const survivors=spawnCells.map((cell,index)=>({id:`survivor-${index+1}`,role:roles[index]??'guard',cell,health:100,stamina:100,status:'active' as const,action:'idle' as const,targetCell:null,stuckTicks:0,intent:'Assessing the refuge.'}));const state:ZombieState={schemaVersion:1,runId:`zombie-${checksum({seed,restartIndex,profile:config.profile})}`,seed,tick:0,lifecycle:'preparation',phaseTick:0,day:1,config,world:generated.world,features:generated.features,survivors,zombies:[],resources:{materials:60,ammo:80,medicine:20,food:60,power:40},baseIntegrity:1000,coreIntegrity:1000,meaningfulEventTick:0,stats:{daysCompleted:0,hordesSurvived:0,resourcesCollected:0,wallsBuilt:0,repairs:0,zombiesDefeated:0,breaches:0,fallbackActions:0},intermissionRemaining:config.resultTicks,restartIndex};assertZombieInvariants(state);return state}
export interface ZombieRuntimeRestore{config:ZombieConfig;seed:string;state:ZombieState;rng:RngSnapshot;nextEventSequence:number;events?:ZombieEvent[]}
export class ZombieRuntime{public events:ZombieEvent[];public state:ZombieState;public rng:NamedRng;private seq:number;public config:ZombieConfig;public seed:string;private constructor(config:ZombieConfig,seed:string,state?:ZombieState,rng?:NamedRng,nextEventSequence=0,events:ZombieEvent[]=[]){this.config=config;this.seed=seed;this.rng=rng??NamedRng.fromSeed(seed);this.state=state??initialState(config,seed,0,this.rng);this.seq=nextEventSequence;this.events=events.map(e=>structuredClone(e));if(!state)this.emit('run-initialized',{seed,profile:config.profile})}
static create(config:Partial<ZombieConfig>,seed:string){return new ZombieRuntime(parseZombieConfig(config),seed)}
static restore(input:ZombieRuntimeRestore){return new ZombieRuntime(parseZombieConfig(input.config),input.seed,structuredClone(input.state),NamedRng.restore(input.rng),input.nextEventSequence,input.events??[])}
private emit(type:string,data?:Record<string,unknown>,tick=this.state.tick){this.events.push({seq:this.seq++,tick,type,data});if(this.events.length>this.config.eventRetention)this.events.splice(0,this.events.length-this.config.eventRetention)}
step(){if(this.state.lifecycle==='result'){this.state=structuredClone(this.state);this.state.lifecycle='intermission';this.emit('intermission-started',{remaining:this.state.intermissionRemaining});return this.state}if(this.state.lifecycle==='intermission'){this.state=structuredClone(this.state);this.state.intermissionRemaining--;if(this.state.intermissionRemaining<=0)this.restart();return this.state}const output=stepZombieRules(this.state);this.state=output.state;for(const e of output.events)this.emit(e.type,e.data,e.tick);return this.state}
restart(){const restartIndex=this.state.restartIndex+1;this.seed=`${this.seed}:restart:${restartIndex}`;this.rng=NamedRng.fromSeed(this.seed);this.state=initialState(this.config,this.seed,restartIndex,this.rng);this.emit('run-restarted',{seed:this.seed,restartIndex});return this.state}
stateChecksum(){return checksum(this.state)}getNextEventSequence(){return this.seq}}
