import type{TrafficEvent,TrafficState}from '../state/types';
export type TrafficAudioCueType='signal-shift'|'incident-alert'|'incident-clear'|'trip-burst'|'wave-change'|'result-success'|'result-gridlock'|'audience-impact'|'recovery';
export interface TrafficAudioCue{id:string;type:TrafficAudioCueType;tick:number;priority:number;caption:string;toneHz:number;durationMs:number;gainPermille:number}
export interface TrafficMixState{intensityPermille:number;masterGainPermille:number;ambienceGainPermille:number;effectsGainPermille:number;duckingPermille:number}
const mapping:Record<string,Omit<TrafficAudioCue,'id'|'tick'>>={
  'signal-changed':{type:'signal-shift',priority:1,caption:'Signal plan adjusted',toneHz:520,durationMs:80,gainPermille:260},
  'incident-started':{type:'incident-alert',priority:5,caption:'Road incident active',toneHz:190,durationMs:260,gainPermille:520},
  'incident-cleared':{type:'incident-clear',priority:4,caption:'Road incident cleared',toneHz:760,durationMs:180,gainPermille:420},
  'trip-completed':{type:'trip-burst',priority:1,caption:'Trip completed',toneHz:640,durationMs:55,gainPermille:170},
  'wave-changed':{type:'wave-change',priority:3,caption:'Demand wave changed',toneHz:420,durationMs:170,gainPermille:330},
  'audience-effect-applied':{type:'audience-impact',priority:4,caption:'Audience policy applied',toneHz:880,durationMs:220,gainPermille:420}
};
export class TrafficAudioDirector{private readonly voiceLimit:number;private readonly muted:boolean;private seenSeq=0;private lastTypeTick=new Map<TrafficAudioCueType,number>();constructor(options:{voiceLimit:number;muted:boolean}){if(!Number.isInteger(options.voiceLimit)||options.voiceLimit<1||options.voiceLimit>12)throw new RangeError('voiceLimit');this.voiceLimit=options.voiceLimit;this.muted=options.muted}route(events:TrafficEvent[],state:TrafficState):TrafficAudioCue[]{if(this.muted)return[];const candidates:TrafficAudioCue[]=[];for(const event of events){if(event.seq<=this.seenSeq)continue;this.seenSeq=Math.max(this.seenSeq,event.seq);let template=mapping[event.type];if(event.type==='run-result')template=event.data.reason==='gridlock'?{type:'result-gridlock',priority:6,caption:'Gridlock ended the experiment',toneHz:130,durationMs:520,gainPermille:600}:{type:'result-success',priority:6,caption:'City experiment complete',toneHz:960,durationMs:520,gainPermille:580};if(!template)continue;const last=this.lastTypeTick.get(template.type)??-1000,cooldown=template.type==='trip-burst'?8:2;if(event.tick-last<cooldown)continue;this.lastTypeTick.set(template.type,event.tick);candidates.push({id:`cue-${event.seq}`,tick:event.tick,...template})}return candidates.sort((a,b)=>b.priority-a.priority||a.tick-b.tick||a.id.localeCompare(b.id)).slice(0,this.voiceLimit)}mix(state:TrafficState):TrafficMixState{const active=Math.max(1,state.vehicles.length),waiting=state.vehicles.filter(vehicle=>vehicle.waitTicks>0).length,intensity=Math.max(120,Math.min(900,Math.floor(waiting*1000/active)+(state.wave==='surge'||state.wave==='incident'?160:0)));return{intensityPermille:intensity,masterGainPermille:850,ambienceGainPermille:Math.max(180,520-Math.floor(intensity/3)),effectsGainPermille:Math.min(760,300+Math.floor(intensity/2)),duckingPermille:state.lifecycle==='result'?550:180}}
}
