import{checksum}from'../../../../packages/replay/src/index';import{NamedRng}from'../../../../packages/seeded-rng/src/index';import{stepTowerCombat}from'../combat/step';import{generateTowerChunk}from'../generation/chunks';import{generateTowerContent}from'../generation/content';import{validateTowerChunk}from'../generation/validator';import{stepTowerPhysics}from'../physics/step';import{applyTowerUpgrade,offerTowerUpgrades}from'../progression/builds';import type{TowerAction,TowerEvent,TowerResultReason,TowerState}from'../state/types';
export interface TowerRuleResult{state:TowerState;events:Omit<TowerEvent,'seq'>[];accepted:boolean;reason?:string}
export function normalizeTowerAction(action:Partial<TowerAction>|undefined):TowerAction{const move=action?.move??0;if(move!==-1&&move!==0&&move!==1)throw new RangeError('move');const upgradeChoice=action?.upgradeChoice;if(upgradeChoice!==undefined&&typeof upgradeChoice!=='string')throw new TypeError('upgradeChoice');return{move,jump:Boolean(action?.jump),dash:Boolean(action?.dash),attack:Boolean(action?.attack),ability:Boolean(action?.ability),upgradeChoice}}
export function makeTowerTerminal(input:TowerState,reason:TowerResultReason,kind:'game'|'technical'|'operator'='game'){const state=structuredClone(input);state.player.state='dead';state.lifecycle='result';const base={kind,reason,tick:state.tick,floor:state.floor,height:state.stats.maxHeight};state.result={...base,checksum:checksum(base)};if(kind==='technical')state.stats.technicalOutcomes++;return state}
function damageFromHazard(state:TowerState,id:string,events:Omit<TowerEvent,'seq'>[]){if(state.player.invulnerableTicks>0)return;const hazard=state.chunks.flatMap(c=>c.hazards).find(h=>h.id===id),amount=hazard?.damage??1;if(state.player.shieldCharges>0){state.player.shieldCharges--;state.player.invulnerableTicks=10;events.push({tick:state.tick,type:'shield-block',data:{source:id}});return}state.player.health=Math.max(0,state.player.health-amount);state.player.invulnerableTicks=20;state.player.state='hurt';state.stats.hazardHits++;state.stats.damageTaken+=amount;events.push({tick:state.tick,type:'player-damage',data:{source:id,amount,health:state.player.health}})}
function holdAtGuardian(state:TowerState,events:Omit<TowerEvent,'seq'>[]){const chunk=state.chunks.find(c=>c.floor===state.floor)!,cap=chunk.platforms[chunk.platforms.length-1];state.player.position.y=cap.y+cap.height+state.player.halfHeight;state.player.velocity={x:0,y:0};state.player.grounded=true;state.player.groundedPlatformId=cap.id;events.push({tick:state.tick,type:'guardian-gate',data:{floor:state.floor}})}
export function applyTowerAction(input:TowerState,actionInput:Partial<TowerAction>|undefined,rng:NamedRng):TowerRuleResult{if(input.lifecycle!=='running')return{state:structuredClone(input),events:[],accepted:false,reason:'not-running'};let action:TowerAction;try{action=normalizeTowerAction(actionInput)}catch{return{state:structuredClone(input),events:[],accepted:false,reason:'invalid-action'}}let state=structuredClone(input),events:Omit<TowerEvent,'seq'>[]=[];
  if(state.pendingUpgradeOffers.length){const offer=state.pendingUpgradeOffers.find(x=>x.id===action.upgradeChoice);if(!offer)return{state,events,accepted:false,reason:'upgrade-choice-required'};const applied=applyTowerUpgrade(state,offer);if(!applied.applied)return{state,events,accepted:false,reason:applied.reason};state=applied.state;events.push({tick:state.tick,type:'upgrade-applied',data:{id:offer.id,family:offer.family}});action={move:0,jump:false,dash:false,attack:false,ability:false}}
  const physics=stepTowerPhysics(state,action);state=physics.state;if(physics.integrityFailure){state=makeTowerTerminal(state,'integrity-quarantine','technical');events.push({tick:state.tick,type:'technical-terminal',data:{reason:physics.integrityFailure}});return{state,events,accepted:true}}
  const combat=stepTowerCombat(state,action,rng);state=combat.state;events.push(...combat.events);for(const contact of physics.contacts){events.push({tick:state.tick,type:`contact-${contact.kind}`,data:{entityId:contact.entityId}});if(contact.kind==='hazard')damageFromHazard(state,contact.entityId,events)}state.tick++;
  const current=state.chunks.find(c=>c.floor===state.floor)??state.chunks[state.chunks.length-1];if(state.player.health<=0){state=makeTowerTerminal(state,'health-depleted');events.push({tick:state.tick,type:'game-terminal',data:{reason:'health-depleted'}})}else if(state.player.position.y<current.baseY-state.config.killDepth){state.stats.falls++;state=makeTowerTerminal(state,'fall');events.push({tick:state.tick,type:'game-terminal',data:{reason:'fall'}})}else if(state.player.position.y>=current.exitY){const guardianAlive=state.enemies.some(e=>e.active&&e.floor===state.floor&&e.kind==='guardian');if(guardianAlive)holdAtGuardian(state,events);else{const nextFloor=state.floor+1,next=generateTowerChunk(state.config,state.seed,nextFloor,rng),validation=validateTowerChunk(next,state.config);if(!validation.valid){state=makeTowerTerminal(state,'integrity-quarantine','technical');events.push({tick:state.tick,type:'technical-terminal',data:{reason:'invalid-generated-chunk',issues:validation.issues}})}else{const content=generateTowerContent(next,state.config,state.seed,rng);state.floor=nextFloor;state.stats.floorsCleared++;state.stats.checkpoints++;state.player.position={...next.spawn};state.player.velocity={x:0,y:0};state.player.grounded=false;state.player.groundedPlatformId=undefined;state.player.checkpoint={...next.spawn};state.player.checkpointFloor=nextFloor;state.player.health=Math.min(state.player.maxHealth,state.player.health+1);state.player.invulnerableTicks=12;state.chunks.push(next);state.chunks=state.chunks.filter(c=>c.floor>=nextFloor-state.config.visibleChunkCount+1);state.enemies=content.enemies;state.pickups=content.pickups;state.projectiles=[];state.ai.targetPlatformId=undefined;state.meaningfulEventTick=state.tick;if(nextFloor%state.config.upgradeInterval===0)state.pendingUpgradeOffers=offerTowerUpgrades(state,rng,nextFloor);events.push({tick:state.tick,type:'floor-complete',data:{floor:nextFloor,theme:next.theme,guardian:next.guardian,upgradeOffers:state.pendingUpgradeOffers.map(x=>x.id)}})}}}
  return{state,events,accepted:true}}
