'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const ant=require('../../dist/games/ai-ant-colony/src/index.js');
function runtime(seed='effects'){return ant.AntColonyRuntime.create({width:36,height:24,targetPopulation:64,initialWorkers:16,maxAnts:128,predatorCap:3,predatorSpawnInterval:1000,noProgressTicks:5000},seed)}
function command(id,effectId,tick=0,magnitude=1,payload={}){return ant.createAntInfluenceCommand({id,effectId,scheduledTick:tick,magnitude,source:'operator',payload})}

test('effect catalogue contains ten disclosed non-terminal effect classes',()=>{assert.equal(ant.ANT_EFFECT_CATALOGUE.length,10);assert.equal(new Set(ant.ANT_EFFECT_CATALOGUE.map(effect=>effect.id)).size,10);assert.ok(ant.ANT_EFFECT_CATALOGUE.every(effect=>effect.canGuaranteeTerminal===false&&effect.disclosure.length>30&&effect.maxMagnitude>0))});

test('a due nectar bloom applies exactly once through the pre-authority boundary',()=>{const r=runtime('once'),before=r.state.world.food.reduce((a,b)=>a+b,0),cmd=command('effect-once','nectar-bloom');assert.equal(ant.scheduleAntInfluence(r.state,cmd).status,'scheduled');assert.equal(ant.scheduleAntInfluence(r.state,cmd).status,'duplicate');r.step();const after=r.state.world.food.reduce((a,b)=>a+b,0);assert.ok(after>before);assert.equal(r.state.influence.appliedIds.filter(id=>id==='effect-once').length,1);const applied=r.state.influence.records.filter(record=>record.id==='effect-once'&&record.status==='applied');assert.equal(applied.length,1);r.step();assert.equal(r.state.influence.records.filter(record=>record.id==='effect-once'&&record.status==='applied').length,1)});

test('placement candidates exclude occupied cells and tunnel direction never digs directly',()=>{const r=runtime('candidates'),occupied=new Set([...r.state.ants.map(a=>a.y*r.state.config.width+a.x),r.state.world.entrance]),surface=ant.antEffectSurfaceCandidates(r.state);assert.ok(surface.every(cell=>!occupied.has(cell)&&r.state.world.tiles[cell]===2));const candidates=ant.antEffectExcavationCandidates(r.state),before=r.state.colony.tunnelsDug;assert.ok(candidates.length>0);ant.scheduleAntInfluence(r.state,command('direction','tunnel-direction',0,3));r.step();assert.equal(r.state.colony.tunnelsDug>=before,true);assert.ok(r.state.influence.records.some(record=>record.id==='direction'&&record.status==='applied'))});

test('cooldown, queue cap and terminal lifecycle fail closed',()=>{const r=runtime('bounds');ant.scheduleAntInfluence(r.state,command('cool-a','nectar-bloom'));ant.scheduleAntInfluence(r.state,command('cool-b','nectar-bloom'));r.step();assert.equal(r.state.influence.records.find(record=>record.id==='cool-b'&&record.status==='rejected').details.reason,'cooldown');const q=runtime('queue');for(let i=0;i<128;i++)assert.equal(ant.scheduleAntInfluence(q.state,command(`queue-${i}`,'colony-theme',999,1,{theme:'forest'})).status,'scheduled');assert.equal(ant.scheduleAntInfluence(q.state,command('queue-over','colony-theme',999,1,{theme:'forest'})).reason,'queue-cap');const terminal=runtime('terminal');ant.scheduleAntInfluence(terminal.state,command('terminal-effect','nectar-bloom'));terminal.state.lifecycle='result';terminal.state.result={reason:'stagnation',tick:0,population:terminal.state.ants.length,foodStore:terminal.state.colony.foodStore,tunnelsDug:0,score:0,finalChecksum:'fixed'};const before=terminal.state.world.food.reduce((a,b)=>a+b,0);terminal.step();assert.equal(terminal.state.world.food.reduce((a,b)=>a+b,0),before);assert.equal(terminal.state.influence.appliedIds.includes('terminal-effect'),false)});

test('support effects cannot directly satisfy ascension and challenge pressure respects safety gates',()=>{const r=runtime('terminal-safety');r.state.colony.foodStore=r.state.config.targetPopulation+100;r.state.ants.length=r.state.config.targetPopulation-1;const before=r.state.colony.foodStore;ant.scheduleAntInfluence(r.state,command('fungus-safe','fungus-garden',0,5));r.step();assert.ok(r.state.colony.foodStore>=before);assert.notEqual(r.state.result?.reason,'ascension');const unsafe=runtime('challenge-safe');unsafe.state.queen.health=10;const predators=unsafe.state.predators.length;ant.scheduleAntInfluence(unsafe.state,command('challenge','challenge-pressure'));unsafe.step();assert.equal(unsafe.state.predators.length,predators)});

test('active modifiers expire and reversal remains append-only and idempotent',()=>{const r=runtime('reversal');ant.scheduleAntInfluence(r.state,command('shade','shade-canopy',0,2));r.step();assert.ok(r.state.influence.activeModifiers['shade-canopy']);assert.equal(ant.reverseAntInfluence(r.state,'shade').status,'reversed');assert.equal(r.state.influence.activeModifiers['shade-canopy'],undefined);assert.equal(ant.reverseAntInfluence(r.state,'shade').status,'duplicate');assert.ok(r.state.influence.records.some(record=>record.status==='reversed'&&record.details.commandId==='shade'))});
