'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const ant=require('../../dist/games/ai-ant-colony/src/index.js');const{NamedRng}=require('../../dist/packages/seeded-rng/src/index.js');

test('logical-tick vote windows enforce one viewer, legal options and exact cutoff',()=>{const window=ant.createAntVoteWindow({id:'vote-001',openTick:10,closeTick:20,options:['nectar-bloom','gentle-rain']});assert.equal(ant.castAntVote(window,{viewerToken:'viewer_one',optionId:'nectar-bloom',weight:1,tick:10}).status,'accepted');assert.equal(ant.castAntVote(window,{viewerToken:'viewer_one',optionId:'gentle-rain',weight:1,tick:11}).reason,'viewer-already-voted');assert.equal(ant.castAntVote(window,{viewerToken:'viewer_two',optionId:'gentle-rain',weight:2,tick:20}).status,'accepted');assert.equal(ant.castAntVote(window,{viewerToken:'viewer_late',optionId:'gentle-rain',weight:1,tick:21}).reason,'window-closed');assert.throws(()=>ant.createAntVoteWindow({id:'vote-bad',openTick:0,closeTick:1,options:['nectar-bloom','kill-queen']}),/effect/)});

test('weighted vote ties resolve deterministically through the named RNG stream',()=>{function resolved(){const window=ant.createAntVoteWindow({id:'vote-tie',openTick:0,closeTick:10,options:['nectar-bloom','gentle-rain']});ant.castAntVote(window,{viewerToken:'viewer_a',optionId:'nectar-bloom',weight:2,tick:2});ant.castAntVote(window,{viewerToken:'viewer_b',optionId:'gentle-rain',weight:2,tick:3});return ant.resolveAntVote(window,NamedRng.fromSeed('vote-seed'))}const a=resolved(),b=resolved();assert.deepEqual(a,b);assert.ok(['nectar-bloom','gentle-rain'].includes(a.winner));assert.equal(a.command.scheduledTick,11);assert.equal(a.command.source,'vote')});

test('director normalizes accepted votes into one scheduled authoritative command',()=>{const runtime=ant.AntColonyRuntime.create({width:32,height:22,targetPopulation:50,initialWorkers:12},'director'),director=new ant.AntAudienceDirector();director.open({id:'director-vote',openTick:0,closeTick:5,options:['nectar-bloom','gentle-rain']});const input=ant.normalizeAntProviderVote({provider:'test',eventId:'director-event',subject:'viewer',optionId:'nectar-bloom',entitlementWeight:1,occurredTick:3,receivedTick:3,authenticated:true,moderation:'pass',regionAllowed:true,identitySalt:'director-private-salt'});assert.equal(director.ingest(input,runtime.state).status,'accepted');runtime.state.tick=5;const result=director.resolve(runtime.state,runtime.rng);assert.equal(result.scheduled.status,'scheduled');assert.equal(runtime.state.influence.scheduled.length,1);assert.equal(runtime.state.influence.scheduled[0].effectId,result.winner)});
