'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const battle=require('../../dist/games/ai-battle-royale/src/index.js');
const{NamedRng}=require('../../dist/packages/seeded-rng/src/index.js');
const salt='battle-phase4-private-identity-salt';
function config(overrides={}){return battle.createBattleConfig({width:24,height:18,combatantCount:12,lootCount:24,maxTicks:320,intermissionTicks:8,startingHealth:500,startingShield:250,zoneFirstShrinkTick:120,zoneShrinkInterval:60,supplyDropEvery:70,noProgressTicks:160,voteWindowEvery:40,voteWindowTicks:10,maxProcessedInfluence:32,maxAuditEntries:32,maxScheduledEffects:4,...overrides})}
function runtime(seed='phase4-runtime'){return new battle.BattleRoyaleRuntime(config(),seed,`run-${seed}`)}
function providerVote(overrides={}){return battle.normalizeBattleProviderVote({provider:'youtube',eventId:'evt-001',subject:'provider-user-44',displayName:'Never Persist This Name',optionId:'supply-rain',entitlementWeight:1,occurredTick:40,receivedTick:40,authenticated:true,moderation:'pass',regionAllowed:true,identitySalt:salt,...overrides})}
function gatewayInput(gateway,overrides={}){const decision=gateway.accept(providerVote(overrides));assert.equal(decision.status,'accepted',decision.reason);return decision.input}

test('provider normalization pseudonymizes identity and drops display metadata',()=>{const first=providerVote(),sameViewer=providerVote({eventId:'evt-002'}),otherViewer=providerVote({eventId:'evt-003',subject:'provider-user-45'});assert.match(first.viewerToken,/^viewer_[a-f0-9]{24}$/);assert.equal(first.viewerToken,sameViewer.viewerToken);assert.notEqual(first.viewerToken,otherViewer.viewerToken);assert.equal(first.idempotencyKey,'youtube:evt-001');assert.equal('displayName'in first,false);assert.equal(JSON.stringify(first).includes('Never Persist This Name'),false)});

test('gateway accepts a valid vote once and rejects unsafe or duplicate delivery',()=>{const gateway=new battle.BattleAudienceGateway();const input=providerVote();assert.equal(gateway.accept(input).status,'accepted');assert.deepEqual(gateway.accept(input),{status:'rejected',reason:'duplicate'});for(const[overrides,reason]of[[{eventId:'evt-auth',authenticated:false},'authentication'],[{eventId:'evt-mod-down',moderation:'unavailable'},'moderation-unavailable'],[{eventId:'evt-mod-reject',moderation:'reject'},'moderation-reject'],[{eventId:'evt-region',regionAllowed:false},'region'],[{eventId:'evt-weight',entitlementWeight:3},'entitlement-weight'],[{eventId:'evt-stale',occurredTick:1,receivedTick:200},'stale'],[{eventId:'evt-future',occurredTick:60,receivedTick:40},'future']])assert.equal(gateway.accept(providerVote(overrides)).reason,reason);const invalid=providerVote({eventId:'evt-effect'});invalid.optionId='kill-the-leader';assert.equal(gateway.accept(invalid).reason,'effect');assert.equal(gateway.snapshot().seenCount,2)});

test('rejected traffic does not consume rate capacity and gateway memory is bounded',()=>{const gateway=new battle.BattleAudienceGateway({perViewerLimit:1,globalLimit:1,maxSeen:8});assert.equal(gateway.accept(providerVote({eventId:'evt-bad',authenticated:false})).reason,'authentication');assert.equal(gateway.accept(providerVote({eventId:'evt-good'})).status,'accepted');assert.equal(gateway.accept(providerVote({eventId:'evt-over'})).reason,'viewer-rate');for(let index=0;index<20;index+=1){const isolated=new battle.BattleAudienceGateway({maxSeen:8});isolated.accept(providerVote({eventId:`evt-${index}`,subject:`viewer-${index}`}));assert.ok(isolated.snapshot().seenCount<=8)}});

test('one bounded ballot per pseudonymous viewer enters an open deterministic window',()=>{const game=runtime('window');for(let index=0;index<40;index+=1)game.step();assert.equal(game.state.tick,40);assert.equal(game.state.influence.currentWindow.status,'open');const gateway=new battle.BattleAudienceGateway();const first=gatewayInput(gateway);assert.equal(battle.submitBattleAudienceInput(game.state,first).status,'accepted');const replacement=gatewayInput(gateway,{eventId:'evt-002',optionId:'medic-mist'});assert.deepEqual(battle.submitBattleAudienceInput(game.state,replacement),{status:'rejected',reason:'viewer-already-voted'});const weighted=gatewayInput(gateway,{eventId:'evt-003',subject:'provider-user-45',optionId:'radar-pulse',entitlementWeight:2});assert.equal(battle.submitBattleAudienceInput(game.state,weighted).status,'accepted');const ballots=Object.values(game.state.influence.currentWindow.ballots);assert.deepEqual(ballots.map(ballot=>ballot.weight).sort(),[1,2]);assert.equal(JSON.stringify(game.state.influence).includes('Never Persist'),false);assert.equal(game.state.influence.processedInputIds.length,2)});

test('equal vote totals resolve deterministically and apply exactly once',()=>{const first=runtime('tie'),second=runtime('tie');for(let index=0;index<40;index+=1){first.step();second.step()}const gatewayA=new battle.BattleAudienceGateway(),gatewayB=new battle.BattleAudienceGateway();const votes=[providerVote({eventId:'evt-tie-a',subject:'viewer-a',optionId:'supply-rain'}),providerVote({eventId:'evt-tie-b',subject:'viewer-b',optionId:'medic-mist'})];for(const input of votes){const acceptedA=gatewayA.accept(input),acceptedB=gatewayB.accept(input);assert.equal(acceptedA.status,'accepted');assert.equal(acceptedB.status,'accepted');assert.equal(battle.submitBattleAudienceInput(first.state,acceptedA.input).status,'accepted');assert.equal(battle.submitBattleAudienceInput(second.state,acceptedB.input).status,'accepted')}for(let index=0;index<12;index+=1){first.step();second.step()}assert.equal(first.state.checksum,second.state.checksum);assert.equal(first.state.influence.currentWindow.winner,second.state.influence.currentWindow.winner);assert.ok(['supply-rain','medic-mist'].includes(first.state.influence.currentWindow.winner));assert.equal(first.state.events.filter(event=>event.type==='influence-applied').length,1);assert.equal(first.state.influence.scheduled.filter(effect=>effect.applied).length,1)});

test('every audience effect is global, bounded and unable to create a terminal result',()=>{for(const effectId of['supply-rain','zone-hold','medic-mist','radar-pulse','theme-shift']){const game=runtime(`effect-${effectId}`),state=game.state,rng=NamedRng.restore(state.rng),before={loot:state.arena.loot.length,nextShrink:state.zone.nextShrinkTick,theme:state.influence.theme,survivors:state.combatants.filter(agent=>agent.alive).length};if(effectId==='medic-mist')for(const agent of state.combatants)agent.health=Math.max(1,agent.maxHealth-10);assert.equal(battle.scheduleBattleInfluenceEffect(state,effectId,'direct-window',state.tick).status,'scheduled');battle.advanceBattleInfluence(state,rng);assert.equal(state.result,null);assert.equal(state.combatants.filter(agent=>agent.alive).length,before.survivors);if(effectId==='supply-rain')assert.ok(state.arena.loot.length-before.loot>=1&&state.arena.loot.length-before.loot<=3);if(effectId==='zone-hold')assert.ok(state.zone.nextShrinkTick-before.nextShrink>=1&&state.zone.nextShrinkTick-before.nextShrink<=40);if(effectId==='medic-mist')assert.ok(state.combatants.every(agent=>agent.health===agent.maxHealth-5));if(effectId==='radar-pulse')assert.ok(state.influence.radarUntilTick>state.tick&&state.influence.radarUntilTick<=state.tick+30);if(effectId==='theme-shift')assert.notEqual(state.influence.theme,before.theme)}});

test('emergency disable and provider outage preserve autonomous gameplay',()=>{const game=runtime('outage');battle.setBattleInfluenceEnabled(game.state,false,'operator-emergency-disable');battle.setBattleInfluenceProviderStatus(game.state,'degraded','provider-outage');for(let index=0;index<80;index+=1)game.step();assert.equal(game.state.tick,80);assert.equal(game.state.influence.currentWindow,null);assert.equal(game.state.events.some(event=>event.type==='vote-opened'),false);battle.setBattleInfluenceEnabled(game.state,true,'operator-restore');battle.setBattleInfluenceProviderStatus(game.state,'disabled','provider-disabled');for(let index=0;index<40;index+=1)game.step();assert.equal(game.state.tick,120);assert.equal(game.state.influence.currentWindow,null);assert.notEqual(game.state.lifecycle,'quarantined')});

test('authoritative influence histories, ballots and scheduled effects stay within configured caps',()=>{const game=runtime('caps'),state=game.state;assert.equal(battle.openBattleVoteWindow(state).status,'opened');const gateway=new battle.BattleAudienceGateway({perViewerLimit:2,globalLimit:100,maxSeen:128});let accepted=0;for(let index=0;index<40;index+=1){const decision=gateway.accept(providerVote({eventId:`evt-cap-${index}`,subject:`viewer-cap-${index}`,occurredTick:0,receivedTick:0,optionId:index%2===0?'supply-rain':'medic-mist'}));assert.equal(decision.status,'accepted');if(battle.submitBattleAudienceInput(state,decision.input).status==='accepted')accepted+=1}assert.equal(accepted,state.config.maxProcessedInfluence);assert.ok(state.influence.processedInputIds.length<=state.config.maxProcessedInfluence);assert.ok(state.influence.audit.length<=state.config.maxAuditEntries);assert.ok(Object.keys(state.influence.currentWindow.ballots).length<=state.config.maxProcessedInfluence);let scheduled=0;for(let index=0;index<8;index+=1)if(battle.scheduleBattleInfluenceEffect(state,'radar-pulse',`window-${index}`,state.tick+index).status==='scheduled')scheduled+=1;assert.equal(scheduled,state.config.maxScheduledEffects);assert.ok(state.influence.scheduled.length<=state.config.maxScheduledEffects);assert.deepEqual(battle.assertBattleInvariants(state),[])});
