const test=require('node:test');const assert=require('node:assert/strict');
const {NamedRng}=require('../../dist/packages/seeded-rng/src/index.js');
const {SnakeRuntime}=require('../../dist/games/autonomous-snake/src/runtime/run.js');
const {createVoteWindow,submitVote,resolveVote}=require('../../dist/packages/interaction-core/src/index.js');
const {createDirectorState,buildSafeChoiceSet,scheduleVoteResult}=require('../../dist/games/autonomous-snake/src/influence/director.js');
function vote(serial,token){return{schemaVersion:1,provider:'fixture',providerEventId:serial,occurredAtMs:1,receivedAtMs:1,channelRef:'c',viewerRef:`v-${serial}`,displayName:null,kind:'vote',fixedToken:token,entitlementBand:'none',entitlementWeight:1,rawDigest:serial,reversalOf:null,idempotencyKey:`k-${serial}`}}
test('director builds only currently eligible distinct effects and remains deterministic',()=>{const r=SnakeRuntime.create({width:16,height:12,targetLength:30,profile:'portals'},'director');const s=createDirectorState();const a=buildSafeChoiceSet(r.state,s,NamedRng.fromSeed('d')),b=buildSafeChoiceSet(r.state,s,NamedRng.fromSeed('d'));assert.deepEqual(a,b);assert.ok(a.length>=2&&a.length<=4);assert.equal(new Set(a.map(x=>x.effectId)).size,a.length)});
test('resolved vote maps to exactly one validated queued influence command',()=>{const r=SnakeRuntime.create({width:16,height:12,targetLength:30,profile:'portals'},'schedule');const choices=buildSafeChoiceSet(r.state,createDirectorState(),NamedRng.fromSeed('choices')).slice(0,2);let w=createVoteWindow({id:'window',runToken:r.state.runId,startTick:r.state.tick,endTick:r.state.tick+5,options:choices.map((c,i)=>({id:`o${i}`,label:c.effectId,effectId:c.effectId,candidateId:c.id}))});w=submitVote(w,vote('1','A'),{A:'o0',B:'o1'},1).window;const resolved=resolveVote(w,NamedRng.fromSeed('tie'),5);const out=scheduleVoteResult(r.state,resolved.window);assert.equal(out.status,'queued');assert.equal(out.state.influence.queued.length,1);assert.equal(out.state.influence.queued[0].candidateId,choices[0].id)});
test('director suppresses windows during non-running lifecycle and excessive pressure',()=>{const r=SnakeRuntime.create({width:12,height:10,targetLength:20},'suppress');const state=createDirectorState();r.state.lifecycle='result';assert.equal(buildSafeChoiceSet(r.state,state,NamedRng.fromSeed('x')).length,0);r.state.lifecycle='running';r.state.influence.chatVsAi.pressure=r.state.influence.chatVsAi.pressureCap;assert.equal(buildSafeChoiceSet(r.state,state,NamedRng.fromSeed('x')).length,0)});
