'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{MazeRuntime}=require('../../dist/games/ai-maze-escape/src/runtime/run.js');
const{buildMazeInfluenceCandidates}=require('../../dist/games/ai-maze-escape/src/influence/candidates.js');
const{createMazeInfluenceCommand,queueMazeInfluence}=require('../../dist/games/ai-maze-escape/src/influence/apply.js');
const{createMazeVoteWindow,resolveMazeVoteToCommand}=require('../../dist/games/ai-maze-escape/src/influence/director.js');
const{submitVote}=require('../../dist/packages/interaction-core/src/index.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
function audience(id,token,weight=1){return{schemaVersion:1,provider:'fixture',providerEventId:id,occurredAtMs:1,receivedAtMs:2,channelRef:'maze',viewerRef:`viewer-${id}`,displayName:null,kind:'vote',fixedToken:token,entitlementBand:weight>1?'supporter':'none',entitlementWeight:weight,rawDigest:'abcdef12',reversalOf:null,idempotencyKey:`key-${id}`}}
test('vote windows use fixed tokens, one vote per viewer, bounded weights and deterministic tie-breaks',()=>{const run=MazeRuntime.create({width:13,height:11,profile:'loops',keyCount:1,trapCount:2},'vote-window');for(let i=0;i<8;i++)run.step();let{window,tokenToOption}=createMazeVoteWindow(run.state,run.rng,{id:'vote-1',startTick:run.state.tick,endTick:run.state.tick+4});assert.ok(window.options.length>=2&&window.options.length<=4);let decision=submitVote(window,audience('a','A',3),tokenToOption,run.state.tick);assert.equal(decision.status,'accepted');window=decision.window;decision=submitVote(window,audience('a','A',3),tokenToOption,run.state.tick);assert.equal(decision.status,'duplicate');decision=submitVote(window,audience('b','B',3),tokenToOption,run.state.tick);assert.equal(decision.status,'accepted');window=decision.window;const first=resolveMazeVoteToCommand(run.state,window,run.rng,window.endTick),secondRun=MazeRuntime.create(run.config,'vote-window');for(let i=0;i<8;i++)secondRun.step();let second=createMazeVoteWindow(secondRun.state,secondRun.rng,{id:'vote-1',startTick:secondRun.state.tick,endTick:secondRun.state.tick+4});second.window=submitVote(second.window,audience('a','A',3),second.tokenToOption,secondRun.state.tick).window;second.window=submitVote(second.window,audience('b','B',3),second.tokenToOption,secondRun.state.tick).window;const resolved=resolveMazeVoteToCommand(secondRun.state,second.window,secondRun.rng,second.window.endTick);assert.deepEqual(first,resolved);assert.ok(first.command)});
test('maximum bounded pressure remains deterministic, consequential and cannot buy terminal outcomes',()=>{const simulate=seed=>{const run=MazeRuntime.create({width:15,height:13,profile:'loops',visibilityRadius:2,keyCount:1,trapCount:3,maxTicks:12000,noProgressTicks:3000},seed);let issued=0;for(let guard=0;guard<12000&&run.state.lifecycle==='running';guard++){if(run.state.tick%5===0){const candidates=buildMazeInfluenceCandidates(run.state);for(const candidate of candidates.slice(0,2)){const id=`pressure-${issued++}`,command=createMazeInfluenceCommand(run.state,{id,candidate,scheduledTick:run.state.tick+1,expiresAtTick:run.state.tick+20,source:'support'});queueMazeInfluence(run.state,command);queueMazeInfluence(run.state,command)}}run.step()}const records=Object.values(run.state.influence.applied),applied=records.filter(record=>record.status==='applied');return{result:run.state.result?.reason,kind:run.state.result?.kind,applied:applied.length,duplicates:applied.reduce((sum,record)=>sum+Math.max(0,record.applicationCount-1),0),recordCategory:run.state.influence.recordCategory,stateChecksum:checksum(run.state)}};const a=simulate('max-pressure'),b=simulate('max-pressure');assert.deepEqual(a,b);assert.equal(a.duplicates,0);assert.ok(a.applied>0);assert.equal(a.recordCategory,'audience-influenced');assert.notEqual(a.kind,'technical');assert.notEqual(a.result,'operator-abort');assert.notEqual(a.result,'integrity-quarantine')});
test('zero audience remains a complete deterministic autonomous game',()=>{const run=()=>{const runtime=MazeRuntime.create({width:13,height:11,profile:'tree',maxTicks:12000,noProgressTicks:3000},'zero-audience');while(runtime.state.lifecycle==='running')runtime.step();return{result:runtime.state.result,checksum:checksum(runtime.state),pressure:runtime.state.influence.chatVsAi.pressure}};const a=run(),b=run();assert.deepEqual(a,b);assert.equal(a.result.reason,'escape');assert.equal(a.pressure,0)});
