'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{MazeRuntime}=require('../../dist/games/ai-maze-escape/src/runtime/run.js');
const{buildMazeInfluenceCandidates}=require('../../dist/games/ai-maze-escape/src/influence/candidates.js');
const{createMazeInfluenceCommand,queueMazeInfluence,applyDueMazeInfluence,reverseMazeInfluence}=require('../../dist/games/ai-maze-escape/src/influence/apply.js');
const{validateMazeContent}=require('../../dist/games/ai-maze-escape/src/generation/content.js');
const{encodeMazeSnapshot,restoreMazeRuntime}=require('../../dist/games/ai-maze-escape/src/persistence/snapshot.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
function runtime(seed='influence'){const run=MazeRuntime.create({width:17,height:13,profile:'hunter',visibilityRadius:2,keyCount:2,trapCount:5,threatCount:1,maxTicks:20000,noProgressTicks:5000},seed);for(let i=0;i<12&&run.state.lifecycle==='running';i++)run.step();return run}
test('all launch effects expose bounded prevalidated candidates that preserve a solution',()=>{const run=runtime('candidate-catalogue'),candidates=buildMazeInfluenceCandidates(run.state);const expected=['directional-hint','fog-pulse','next-profile','open-eligible-door','resource-choice','reveal-frontier','safe-obstacle','threat-pulse'];assert.deepEqual([...new Set(candidates.map(item=>item.effectId))].sort(),expected);assert.ok(candidates.length<=32);for(const candidate of candidates){assert.match(candidate.id,/^[a-z0-9:-]+$/);assert.equal(candidate.valid,true,JSON.stringify(candidate));assert.ok(candidate.responseDistance>=2);const clone=structuredClone(run.state);candidate.preview(clone);const validation=validateMazeContent(clone.world,{minimumThreatResponseDistance:2});assert.equal(validation.valid,true,`${candidate.effectId}:${validation.reasons.join(',')}`)}});
test('accepted command is queued and applied exactly once across retries and snapshot restore',()=>{const run=runtime('exactly-once'),candidate=buildMazeInfluenceCandidates(run.state).find(item=>item.effectId==='reveal-frontier');assert.ok(candidate);const command=createMazeInfluenceCommand(run.state,{id:'command-1',candidate,scheduledTick:run.state.tick,expiresAtTick:run.state.tick+20,source:'free-vote'});assert.equal(queueMazeInfluence(run.state,command).status,'queued');assert.equal(queueMazeInfluence(run.state,command).status,'duplicate');run.step();assert.equal(run.state.influence.applied['command-1'].status,'applied');const before=checksum(run.state);run.step();assert.equal(checksum(run.state),checksum(run.state));assert.equal(Object.keys(run.state.influence.applied).filter(id=>id==='command-1').length,1);const restored=restoreMazeRuntime(encodeMazeSnapshot(run));restored.step();assert.equal(restored.state.influence.applied['command-1'].status,'applied');assert.equal(restored.state.influence.queued.some(item=>item.id==='command-1'),false);assert.notEqual(before,'')});
test('expired and terminal commands reject without mutating authoritative gameplay',()=>{const run=runtime('expiry'),candidate=buildMazeInfluenceCandidates(run.state)[0],expired=createMazeInfluenceCommand(run.state,{id:'expired',candidate,scheduledTick:run.state.tick-2,expiresAtTick:run.state.tick-1,source:'support'}),before=checksum(run.state);assert.equal(queueMazeInfluence(run.state,expired).status,'expired');assert.equal(checksum(run.state),before);run.state.lifecycle='result';const terminalBefore=checksum(run.state);const command=createMazeInfluenceCommand(run.state,{id:'terminal',candidate,scheduledTick:run.state.tick,expiresAtTick:run.state.tick+10,source:'free-vote'});assert.equal(queueMazeInfluence(run.state,command).status,'terminal');assert.equal(checksum(run.state),terminalBefore)});
test('reversal is append-only, idempotent and never erases learned truth',()=>{const run=runtime('reversal'),candidate=buildMazeInfluenceCandidates(run.state).find(item=>item.effectId==='fog-pulse');assert.ok(candidate);const command=createMazeInfluenceCommand(run.state,{id:'fog-1',candidate,scheduledTick:run.state.tick,expiresAtTick:run.state.tick+10,source:'support'});queueMazeInfluence(run.state,command);applyDueMazeInfluence(run.state,run.rng);assert.ok(run.state.influence.fogUntilTick>run.state.tick);const discovered=[...run.state.discoveredCells],first=reverseMazeInfluence(run.state,{id:'reversal-1',targetCommandId:'fog-1',tick:run.state.tick});assert.equal(first.status,'reversed');assert.equal(run.state.influence.fogUntilTick,run.state.tick);assert.deepEqual(run.state.discoveredCells,discovered);assert.equal(reverseMazeInfluence(run.state,{id:'reversal-1',targetCommandId:'fog-1',tick:run.state.tick}).status,'duplicate');assert.equal(run.state.influence.applied['reversal-1'].status,'reversed')});
