'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const traffic=require('../../dist/games/ai-city-traffic/src/index.js');
function input(overrides={}){return{schemaVersion:1,id:'event-001',effectId:'green-wave-ns',viewerRef:'viewer_token_001',source:'free-vote',authenticated:true,moderation:'approved',receivedTick:0,scheduledTick:1,expiresAtTick:120,payload:{},...overrides}}
function running(seed='audience'){return traffic.TrafficRuntime.create({width:4,height:4,runTicks:600,spawnEveryTicks:1,maxVehicles:160,incidentEveryTicks:40,incidentDurationTicks:30},seed)}

test('Phase 4 exports the bounded interaction API and six fixed effects',()=>{for(const name of ['trafficInfluenceCatalogue','queueTrafficInfluence','applyDueTrafficInfluence','reverseTrafficInfluence','resolveTrafficVote'])assert.ok(traffic[name],name);assert.deepEqual(Object.keys(traffic.trafficInfluenceCatalogue).sort(),['challenge-surge','green-wave-ew','green-wave-ns','incident-relief','night-theme','transit-priority'])});

test('authentication, moderation, schema, and provider gates reject before mutation',()=>{const runtime=running('gates'),before=runtime.checksum();for(const candidate of [input({id:'bad-auth',authenticated:false}),input({id:'bad-mod',moderation:'rejected'}),input({id:'bad-schema',schemaVersion:2}),input({id:'bad-text',viewerRef:'raw viewer <script>'})]){const result=traffic.queueTrafficInfluence(runtime.state,candidate);assert.equal(result.status,'rejected');assert.equal(runtime.state.audience.queued.length,0)}runtime.state.audience.providerStatus='offline';assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'offline'})).reason,'provider-unavailable');runtime.state.audience.providerStatus='healthy';assert.equal(runtime.checksum(),before,'rejected inputs leave authority unchanged');assert.equal(runtime.state.lifecycle,'running')});

test('authorization precedes duplicate disclosure and rejected runtime events sanitize attacker input',()=>{const runtime=running('disclosure-order'),accepted=input({id:'known-command',viewerRef:'viewer_known'});assert.equal(runtime.queueInfluence(accepted).status,'queued');const unauthorized=runtime.queueInfluence({...accepted,authenticated:false});assert.equal(unauthorized.status,'rejected');assert.equal(unauthorized.reason,'authentication-required');runtime.queueInfluence(input({id:'<script>alert(1)</script>',effectId:'<raw-effect>',viewerRef:'viewer_attack'}));const last=runtime.events.at(-1);assert.equal(JSON.stringify(last).includes('<script>'),false);assert.equal(JSON.stringify(last).includes('<raw-effect>'),false)});

test('paid evidence receives no duplicate, rate, cooldown, moderation, or capacity bypass',()=>{const runtime=running('paid-bounds'),paid=input({id:'paid-1',source:'paid-eligible',viewerRef:'viewer_paid'});const first=traffic.queueTrafficInfluence(runtime.state,paid);assert.equal(first.status,'queued');assert.equal(traffic.queueTrafficInfluence(runtime.state,paid).status,'duplicate');assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'paid-2',source:'paid-eligible',viewerRef:'viewer_paid'})).reason,'effect-cooldown');assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'paid-moderation',source:'paid-eligible',viewerRef:'viewer_paid_2',moderation:'rejected'})).status,'rejected');runtime.state.audience.queued=[];runtime.state.audience.cooldowns={};for(let i=0;i<4;i++){assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:`rate-${i}`,effectId:i%2?'night-theme':'transit-priority',viewerRef:'viewer_rate',scheduledTick:20+i,expiresAtTick:200+i})).status,'queued');runtime.state.audience.cooldowns={}}assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'rate-5',effectId:'challenge-surge',viewerRef:'viewer_rate'})).reason,'viewer-rate-limit');runtime.state.audience.queued=Array.from({length:64},(_,i)=>({id:`queued-${i}`,effectId:'night-theme',viewerRef:`viewer_q_${i}`,source:'free-vote',scheduledTick:500+i,expiresAtTick:900+i,payload:{}}));runtime.state.audience.cooldowns={};runtime.state.audience.rateWindows={};assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'cap-over',effectId:'challenge-surge',viewerRef:'viewer_cap_over'})).reason,'queue-capacity')});

test('authoritative invariants reject interaction state beyond declared resource bounds',()=>{const runtime=running('interaction-invariants');runtime.state.audience.queued=Array.from({length:65},(_,i)=>({id:`overflow-${i}`,effectId:'night-theme',viewerRef:`viewer_${i}`,source:'free-vote',receivedTick:0,scheduledTick:100+i,expiresAtTick:300+i,payload:{}}));assert.throws(()=>traffic.assertTrafficInvariants(runtime.state),/audience queue capacity/)});

test('vote ties resolve reproducibly with bounded weights and no arbitrary option',()=>{const ballots=[{id:'ballot-a',option:'green-wave-ns',weight:5,eligible:true},{id:'ballot-b',option:'green-wave-ew',weight:5,eligible:true},{id:'ballot-c',option:'night-theme',weight:99,eligible:true},{id:'ballot-d',option:'incident-relief',weight:2,eligible:false}],a=traffic.resolveTrafficVote(ballots,traffic.createTrafficRng('vote-tie')),b=traffic.resolveTrafficVote([...ballots].reverse(),traffic.createTrafficRng('vote-tie'));assert.deepEqual(a,b);assert.equal(a.tie,true);assert.ok(['green-wave-ew','green-wave-ns','night-theme'].includes(a.winner));assert.equal(a.totals['night-theme'],5);assert.equal(a.totals['incident-relief']??0,0)});

test('effects apply exactly once, stay bounded, emit safe acknowledgements, and never force a result',()=>{const runtime=running('apply-once'),beforeLifecycle=runtime.state.lifecycle;assert.equal(runtime.queueInfluence(input({id:'surge-1',effectId:'challenge-surge',source:'paid-eligible',viewerRef:'viewer_surge',scheduledTick:1,payload:{multiplierPermille:9999}})).status,'queued');runtime.step();assert.equal(runtime.state.audience.applied['surge-1'].status,'applied');assert.equal(runtime.state.audience.applied['surge-1'].applicationCount,1);assert.ok(runtime.state.audience.challengeMultiplierPermille<=1250);assert.equal(runtime.state.lifecycle,beforeLifecycle);assert.equal(runtime.state.result,undefined);const applications=runtime.events.filter(event=>event.type==='audience-effect-applied'&&event.data.commandId==='surge-1');assert.equal(applications.length,1);assert.equal(JSON.stringify(applications).includes('viewer_surge'),false);for(let i=0;i<5;i++)runtime.step();assert.equal(runtime.state.audience.applied['surge-1'].applicationCount,1)});

test('expired commands do not apply and reversible effects restore the safe default',()=>{const runtime=running('expiry-reversal');assert.equal(traffic.queueTrafficInfluence(runtime.state,input({id:'expired-1',effectId:'green-wave-ew',scheduledTick:4,expiresAtTick:5})).status,'queued');runtime.state.tick=6;const expiry=traffic.applyDueTrafficInfluence(runtime.state);assert.equal(expiry.expired,1);assert.equal(runtime.state.audience.applied['expired-1'].status,'expired');assert.notEqual(runtime.state.audience.axisBias,'ew');runtime.state.audience.cooldowns={};assert.equal(runtime.queueInfluence(input({id:'theme-1',effectId:'night-theme',viewerRef:'viewer_theme',receivedTick:runtime.state.tick,scheduledTick:runtime.state.tick+1,expiresAtTick:runtime.state.tick+50})).status,'queued');runtime.step();assert.equal(runtime.state.audience.themeId,'night');const reversed=runtime.reverseInfluence({schemaVersion:1,id:'reverse-1',targetCommandId:'theme-1',authenticated:true,moderation:'approved',tick:runtime.state.tick});assert.equal(reversed.status,'reversed');assert.equal(runtime.state.audience.themeId,'neon');assert.equal(runtime.reverseInfluence({schemaVersion:1,id:'reverse-1',targetCommandId:'theme-1',authenticated:true,moderation:'approved',tick:runtime.state.tick}).status,'duplicate')});

test('incident relief is bounded and irreversible without hiding the audit trail',()=>{const runtime=running('incident-relief');while(!runtime.state.incidents.some(item=>item.active)&&runtime.state.tick<250)runtime.step();const incident=runtime.state.incidents.find(item=>item.active);assert.ok(incident);const before=incident.clearsAtTick-runtime.state.tick;runtime.state.audience.cooldowns={};assert.equal(runtime.queueInfluence(input({id:'relief-1',effectId:'incident-relief',viewerRef:'viewer_relief',receivedTick:runtime.state.tick,scheduledTick:runtime.state.tick+1,expiresAtTick:runtime.state.tick+50})).status,'queued');runtime.step();const after=incident.clearsAtTick-runtime.state.tick;assert.ok(after>=5);assert.ok(before-after<=45);const reversal=runtime.reverseInfluence({schemaVersion:1,id:'reverse-relief',targetCommandId:'relief-1',authenticated:true,moderation:'approved',tick:runtime.state.tick});assert.equal(reversal.status,'refused-irreversible');assert.equal(runtime.state.audience.applied['relief-1'].applicationCount,1)});


test('public audience state is acknowledgement-only and timed presentation effects expire',()=>{const runtime=running('public-audience');const queued=runtime.queueInfluence(input({id:'public-theme',effectId:'night-theme',viewerRef:'viewer_public',payload:{message:'must not survive'},scheduledTick:1,expiresAtTick:80}));assert.equal(queued.status,'queued');assert.deepEqual(runtime.state.audience.queued[0].payload,{});runtime.step();let snapshot=traffic.buildTrafficRenderSnapshot(runtime.state),text=JSON.stringify(snapshot);assert.equal(snapshot.audience.queueDepth,0);assert.deepEqual(snapshot.audience.lastAcknowledgement,{effectId:'night-theme',status:'applied'});assert.equal(text.includes('viewer_public'),false);assert.equal(text.includes('must not survive'),false);assert.equal(snapshot.theme,'night');runtime.state.tick=runtime.state.audience.themeUntilTick+1;traffic.applyDueTrafficInfluence(runtime.state);snapshot=traffic.buildTrafficRenderSnapshot(runtime.state);assert.equal(snapshot.theme,'neon');assert.equal(runtime.state.audience.themeId,'neon')});

test('identical normalized logs replay identically and provider outage preserves autonomous play',()=>{const config={width:4,height:4,runTicks:500,spawnEveryTicks:1,maxVehicles:150},a=traffic.TrafficRuntime.create(config,'interaction-replay'),b=traffic.TrafficRuntime.create(config,'interaction-replay'),log=[input({id:'log-1',effectId:'transit-priority',viewerRef:'viewer_a',scheduledTick:3}),input({id:'log-2',effectId:'challenge-surge',viewerRef:'viewer_b',scheduledTick:30,expiresAtTick:120})];for(let tick=0;tick<120;tick++){for(const event of log.filter(item=>item.receivedTick===tick)){assert.deepEqual(a.queueInfluence(event),b.queueInfluence(event))}a.step();b.step()}assert.equal(a.checksum(),b.checksum());const offline=running('provider-outage');offline.state.audience.providerStatus='offline';const startTick=offline.state.tick;for(let i=0;i<100;i++)offline.step();assert.equal(offline.state.tick,startTick+100);assert.equal(offline.state.lifecycle,'running');assert.ok(offline.state.metrics.spawned>0);assert.equal(offline.state.metrics.collisions,0);assert.equal(traffic.queueTrafficInfluence(offline.state,input({id:'offline-paid',source:'paid-eligible',receivedTick:offline.state.tick,scheduledTick:offline.state.tick+1})).reason,'provider-unavailable')});
