'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{ZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/runtime/run');
const{buildZombieInfluenceCandidates,createZombieInfluenceCommand,queueZombieInfluence,applyDueZombieInfluence,reverseZombieInfluence,zombieInfluenceCatalogue}=require('../../dist/games/ai-zombie-survival/src/influence');
function config(){return{width:24,height:16,dayTicks:50,nightTicks:50,maxDays:3,maxZombies:32,survivorDecisionInterval:1,waveBaseSize:6,waveGrowthPerDay:2}}
test('catalogue exposes exactly the ten approved bounded effects',()=>{assert.deepEqual(Object.keys(zombieInfluenceCatalogue).sort(),['ammo-cache','fog-bank','fortification-sector','generator-boost','medicine-cache','next-weather','runner-surge','scout-route','spotlight','supply-priority'].sort())});
test('eligible fixed choices are deterministic and cannot encode terminal outcomes',()=>{const a=ZombieRuntime.create(config(),'zombie-influence'),b=ZombieRuntime.create(config(),'zombie-influence');const ac=buildZombieInfluenceCandidates(a.state),bc=buildZombieInfluenceCandidates(b.state);assert.deepEqual(ac.map(x=>({id:x.id,effectId:x.effectId,payload:x.payload})),bc.map(x=>({id:x.id,effectId:x.effectId,payload:x.payload})));assert.ok(ac.length>=6);assert.ok(ac.every(x=>x.valid));assert.ok(ac.every(x=>!/(result|evacuat|overrun|kill-all|record)/i.test(JSON.stringify(x.payload))))});
test('duplicate influence applies exactly once and survives snapshot-shaped state cloning',()=>{const game=ZombieRuntime.create(config(),'zombie-once'),candidate=buildZombieInfluenceCandidates(game.state).find(x=>x.effectId==='ammo-cache');assert.ok(candidate);const command=createZombieInfluenceCommand(game.state,{id:'evt-1',candidate,scheduledTick:game.state.tick,expiresAtTick:game.state.tick+20,source:'free-vote'});assert.equal(queueZombieInfluence(game.state,command).status,'queued');assert.equal(queueZombieInfluence(game.state,command).status,'duplicate');const before=game.state.resources.ammo;const first=applyDueZombieInfluence(game.state,game.rng);assert.equal(first.applied,1);assert.ok(game.state.resources.ammo>before);const second=applyDueZombieInfluence(game.state,game.rng);assert.equal(second.applied,0);assert.equal(game.state.influence.applied['evt-1'].applicationCount,1)});
test('reversal is append-only and queued reversal never deletes learned audit truth',()=>{const game=ZombieRuntime.create(config(),'zombie-reversal'),candidate=buildZombieInfluenceCandidates(game.state).find(x=>x.effectId==='next-weather');assert.ok(candidate);const command=createZombieInfluenceCommand(game.state,{id:'evt-weather',candidate,scheduledTick:game.state.tick,expiresAtTick:game.state.tick+20,source:'support'});queueZombieInfluence(game.state,command);applyDueZombieInfluence(game.state,game.rng);const result=reverseZombieInfluence(game.state,{id:'reverse-1',targetCommandId:'evt-weather',tick:game.state.tick});assert.equal(result.status,'reversed');assert.equal(game.state.influence.applied['evt-weather'].status,'applied');assert.equal(game.state.influence.applied['reverse-1'].status,'reversed')});
