import {createGame,stepGame,selectCameraEvent,survivorPose,zombiePose,districtPalette,buildAudioPlan,type Survivor,type Civilian,type Zombie,type Building,type Barricade,type LootNode} from '../index.js';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!;
const ctx=canvas.getContext('2d',{alpha:false})!;
const hud=document.querySelector<HTMLElement>('#hud')!;
const statusEl=document.querySelector<HTMLElement>('#status')!;
let game=createGame({seed:2026,zombieCount:180});
let paused=false,hideHud=false,last=performance.now(),acc=0,visualTime=0,lastEventId=0,nextStepSound=0,nextGroan=0;
const heard=new Set<number>(),fixed=1/30,camera={x:0,y:0,zoom:1.08,targetX:0,targetY:0,targetZoom:1.08};
const audio=new AudioContext(),master=audio.createGain(),musicGain=audio.createGain(),ambGain=audio.createGain();
master.gain.value=.42;musicGain.gain.value=0;ambGain.gain.value=0;musicGain.connect(master);ambGain.connect(master);master.connect(audio.destination);
const musicOsc=audio.createOscillator(),ambOsc=audio.createOscillator();musicOsc.type='triangle';ambOsc.type='sine';musicOsc.connect(musicGain);ambOsc.connect(ambGain);musicOsc.start();ambOsc.start();

function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=Math.floor(innerWidth*d);canvas.height=Math.floor(innerHeight*d);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
addEventListener('pointerdown',()=>audio.resume());
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'){hideHud=!hideHud;hud.style.display=hideHud?'none':'block'}if(e.key.toLowerCase()==='r')game=createGame({seed:2026,zombieCount:180});if(e.code==='Space')paused=!paused});

function iso(x:number,y:number,z=0){const s=22*camera.zoom;return{x:(x-y)*s+innerWidth/2-camera.x,y:(x+y)*s*.5+innerHeight*.48-z*s-camera.y}}
function poly(p:{x:number;y:number}[],fill:string,stroke?:string){ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function diamond(x:number,y:number,w:number,h:number,fill:string){poly([iso(x-w/2,y-h/2),iso(x+w/2,y-h/2),iso(x+w/2,y+h/2),iso(x-w/2,y+h/2)],fill)}
function shadow(x:number,y:number,rx:number,ry:number,a=.28){const p=iso(x,y);ctx.save();ctx.translate(p.x,p.y);ctx.scale(1,.42);ctx.beginPath();ctx.ellipse(0,0,rx*camera.zoom,ry*camera.zoom,0,0,Math.PI*2);ctx.fillStyle=`rgba(0,0,0,${a})`;ctx.fill();ctx.restore()}
function shade(hex:string,d:number){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+d)),g=Math.max(0,Math.min(255,((n>>8)&255)+d)),b=Math.max(0,Math.min(255,(n&255)+d));return`rgb(${r},${g},${b})`}

function drawGround(){const sky=ctx.createLinearGradient(0,0,0,innerHeight);sky.addColorStop(0,game.time.phase==='night'?'#101519':'#5a625f');sky.addColorStop(1,'#232826');ctx.fillStyle=sky;ctx.fillRect(0,0,innerWidth,innerHeight);for(const d of game.districts){const p=districtPalette(d.kind);diamond(d.x,d.y,d.w,d.h,p.ground);const q=iso(d.x-d.w*.42,d.y-d.h*.42,.03);ctx.fillStyle='rgba(238,227,196,.22)';ctx.font='600 10px system-ui';ctx.fillText(d.kind.toUpperCase(),q.x,q.y)}ctx.strokeStyle='rgba(255,255,255,.035)';for(let i=-55;i<=55;i+=4){let a=iso(i,-55),b=iso(i,55);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();a=iso(-55,i);b=iso(55,i);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}diamond(0,0,16,13,'#383b39');diamond(0,0,10,8,'#4d514e')}
function drawBuilding(b:Building){const pal=districtPalette(b.district),z=1.6+b.floors*.9,bb=iso(b.x+b.w/2,b.y-b.h/2),c=iso(b.x+b.w/2,b.y+b.h/2),d=iso(b.x-b.w/2,b.y+b.h/2),at=iso(b.x-b.w/2,b.y-b.h/2,z),bt=iso(b.x+b.w/2,b.y-b.h/2,z),ct=iso(b.x+b.w/2,b.y+b.h/2,z),dt=iso(b.x-b.w/2,b.y+b.h/2,z);poly([bb,c,ct,bt],shade(pal.wall,-18),'rgba(0,0,0,.24)');poly([d,c,ct,dt],shade(pal.wall,-32),'rgba(0,0,0,.28)');if(b.roofVisible)poly([at,bt,ct,dt],shade(pal.roof,-b.damage*30),'rgba(0,0,0,.35)');else{const p=iso(b.x,b.y,.1);diamond(b.x,b.y,b.w*.78,b.h*.78,b.interiorLit?'#5f5847':'#353a37');ctx.fillStyle='rgba(235,211,151,.18)';ctx.fillRect(p.x-18,p.y-12,36,18)}if(b.kind==='safehouse'){const p=iso(0,0,z+.25);ctx.fillStyle='#e3ca83';ctx.font='700 11px system-ui';ctx.fillText(`SAFE HOUSE · L${game.safeHouse.level}`,p.x-48,p.y);if(game.safeHouse.features.includes('generator')){const g=iso(3.3,1.8,.25);ctx.fillStyle='#6d735f';ctx.fillRect(g.x-7,g.y-7,14,8)}if(game.safeHouse.features.includes('medical-cot')){const m=iso(-2.8,1.6,.22);ctx.fillStyle='#d9d5c7';ctx.fillRect(m.x-8,m.y-4,16,5)}if(game.safeHouse.features.includes('lookout')){const l=iso(3,-2.5,2.4);ctx.strokeStyle='#5a4635';ctx.lineWidth=3;ctx.strokeRect(l.x-7,l.y-11,14,11)}if(game.safeHouse.features.includes('expanded-storage'))for(let i=0;i<3;i++){const s=iso(-3+i*1.2,-2,.2);ctx.fillStyle='#816847';ctx.fillRect(s.x-5,s.y-5,10,7)}}}
function drawBarricade(b:Barricade){const p=iso(b.x,b.y);shadow(b.x,b.y,15,7,.32);ctx.save();ctx.translate(p.x,p.y-4);ctx.rotate(b.angle*.32);ctx.fillStyle=b.material==='metal'?'#737b7b':b.material==='vehicle'?'#5d665f':'#70583f';ctx.fillRect(-14,-8,28,9);ctx.strokeStyle=b.hp/b.maxHp<.35?'#ca735e':'rgba(0,0,0,.5)';ctx.strokeRect(-14,-8,28,9);ctx.restore()}
function drawLoot(l:LootNode){if(l.amount<=0)return;const p=iso(l.x,l.y,.18);shadow(l.x,l.y,7,4,.18);ctx.fillStyle=l.kind==='medicine'?'#a9b6ad':l.kind==='ammo'?'#68655a':'#8f744c';ctx.fillRect(p.x-5,p.y-7,10,7)}
function drawSurvivor(s:Survivor){if(!s.alive){const p=iso(s.x,s.y,.05);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(.28);ctx.fillStyle='#3e4140';ctx.fillRect(-8,-2,17,5);ctx.restore();return}const p=iso(s.x,s.y),pose=survivorPose(s),phase=visualTime*(5+pose.stride*4)+Number(s.id.slice(2)),stride=Math.sin(phase)*pose.stride;shadow(s.x,s.y,9,5,.3);ctx.save();ctx.translate(p.x,p.y-16);if(pose.stance==='limp')ctx.rotate(.09);const colors:Record<string,string>={leader:'#c8ad70',scout:'#6e897d',medic:'#b8b7aa',defender:'#7f756c',scavenger:'#9b815d',engineer:'#7e8791'};ctx.strokeStyle='#202524';ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,10);ctx.lineTo(-4+stride*3,19);ctx.moveTo(2,10);ctx.lineTo(5-stride*3,19);ctx.stroke();ctx.fillStyle=colors[s.role];ctx.fillRect(-5,-2,10,13);ctx.strokeStyle='#b28a70';ctx.lineWidth=3;ctx.beginPath();if(pose.stance==='weapon-forward'){ctx.moveTo(3,0);ctx.lineTo(11,-3);ctx.moveTo(-2,1);ctx.lineTo(9,-1)}else{ctx.moveTo(-4,0);ctx.lineTo(-7,7+stride*2);ctx.moveTo(4,0);ctx.lineTo(7,7-stride*2)}ctx.stroke();ctx.fillStyle='#a77d65';ctx.beginPath();ctx.arc(0,-6,4,0,Math.PI*2);ctx.fill();if(s.carrying>0){ctx.fillStyle='#66513a';ctx.fillRect(-9,1,5,8)}if(pose.stance==='escort'){ctx.strokeStyle='#d6c789';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,-9,8,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawCivilian(c:Civilian){if(c.state==='safe'||c.state==='dead')return;const p=iso(c.x,c.y);shadow(c.x,c.y,7,4,.22);ctx.save();ctx.translate(p.x,p.y-14+Math.sin(visualTime*5+Number(c.id.slice(2)))*1.2);ctx.strokeStyle='#3b3935';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-2,7);ctx.lineTo(-3,16);ctx.moveTo(2,7);ctx.lineTo(4,16);ctx.stroke();ctx.fillStyle=c.state==='trapped'?'#b9946a':'#87957f';ctx.fillRect(-4,-2,8,10);ctx.fillStyle='#a77d65';ctx.beginPath();ctx.arc(0,-6,3.5,0,Math.PI*2);ctx.fill();if(c.state==='trapped'){ctx.strokeStyle='rgba(242,211,124,.9)';ctx.beginPath();ctx.arc(0,-7,9+Math.sin(visualTime*4)*2,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawZombie(z:Zombie){if(z.health<=0){const p=iso(z.x,z.y,.02);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-.35+(z.variant%3)*.2);ctx.fillStyle='#39433d';ctx.fillRect(-7,-2,15,4);ctx.restore();return}const p=iso(z.x,z.y),pose=zombiePose(z),sway=Math.sin(visualTime*(3.2*pose.cadence)+z.variant*1.7)*2.2,scale=pose.silhouette==='heavy'?1.28:pose.silhouette==='lean'?.84:1;shadow(z.x,z.y,8*scale,4,.25);ctx.save();ctx.translate(p.x,p.y-14*scale);ctx.scale(scale,pose.silhouette==='lean'?1.12:1);ctx.rotate(sway*.018+(pose.stance==='lunge'?.12:0));ctx.strokeStyle='#303a35';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-2,8);ctx.lineTo(-4-sway*.35,17);ctx.moveTo(2,8);ctx.lineTo(5+sway*.3,17);ctx.stroke();ctx.fillStyle=z.archetype==='brute'?'#595449':z.archetype==='runner'?'#65705b':'#59675b';ctx.fillRect(-4,-2,9,12);ctx.fillStyle='#71806f';ctx.beginPath();ctx.arc(0,-6,4,0,Math.PI*2);ctx.fill();if(z.archetype==='brute'){ctx.strokeStyle='#8b7656';ctx.strokeRect(-6,-3,12,13)}ctx.restore()}
function drawObjective(){const c=game.civilians.find(v=>v.id===game.objective.targetId);if(!c||c.state==='safe')return;const p=iso(c.x,c.y,.4),r=13+Math.sin(visualTime*3)*3;ctx.strokeStyle='rgba(239,207,116,.72)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y-13,r,0,Math.PI*2);ctx.stroke()}
function drawVfx(){for(const e of game.events){if(e.id<=Math.max(lastEventId-45,0))continue;const age=game.time.elapsed-e.time;if(age<0||age>1.3)continue;const p=iso(e.x,e.y,.5),a=1-age/1.3;if(e.type==='shot'){ctx.fillStyle=`rgba(255,213,122,${a})`;ctx.beginPath();ctx.arc(p.x,p.y-18,4*a+1,0,Math.PI*2);ctx.fill()}if(e.type==='barricade-hit'){ctx.fillStyle=`rgba(185,150,110,${.55*a})`;for(let i=0;i<4;i++)ctx.fillRect(p.x+(i-2)*3,p.y-10-age*18-(i%2)*4,2,2)}if(['loot','rescue','safehouse-upgrade'].includes(e.type)){ctx.fillStyle=`rgba(226,205,133,${a})`;ctx.font='700 11px system-ui';ctx.fillText(e.type==='loot'?'SUPPLIES':e.type==='rescue'?'RESCUED':'SAFE HOUSE FORTIFIED',p.x-36,p.y-24-age*14)}}lastEventId=game.events.at(-1)?.id??lastEventId}
function drawLighting(){if(game.time.phase==='night'||game.time.phase==='sunset'){ctx.fillStyle=game.time.phase==='night'?'rgba(9,18,27,.58)':'rgba(69,35,25,.20)';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.globalCompositeOperation='screen';for(const s of game.survivors.filter(s=>s.alive)){const p=iso(s.x,s.y,.7),g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,60*camera.zoom);g.addColorStop(0,'rgba(255,224,150,.16)');g.addColorStop(1,'rgba(255,224,150,0)');ctx.fillStyle=g;ctx.fillRect(p.x-70,p.y-70,140,140)}ctx.globalCompositeOperation='source-over'}if(game.weather.kind==='fog'){ctx.fillStyle=`rgba(190,199,196,${.1*game.weather.intensity})`;ctx.fillRect(0,0,innerWidth,innerHeight)}if(game.weather.kind==='rain'||game.weather.kind==='storm'){ctx.strokeStyle=`rgba(188,205,211,${.25+game.weather.intensity*.18})`;for(let i=0;i<90;i++){const x=((i*97+visualTime*210)%(innerWidth+80))-40,y=((i*53+visualTime*390)%(innerHeight+100))-50;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y+18);ctx.stroke()}}}
function render(){drawGround();const items:any[]=[];for(const b of game.buildings)items.push({d:b.x+b.y,k:'b',v:b});for(const l of game.loot)items.push({d:l.x+l.y,k:'l',v:l});for(const b of game.barricades)items.push({d:b.x+b.y+.2,k:'bar',v:b});for(const c of game.civilians)items.push({d:c.x+c.y+.45,k:'c',v:c});for(const z of game.zombies)items.push({d:z.x+z.y+.4,k:'z',v:z});for(const s of game.survivors)items.push({d:s.x+s.y+.6,k:'s',v:s});items.sort((a,b)=>a.d-b.d);for(const i of items){if(i.k==='b')drawBuilding(i.v);else if(i.k==='l')drawLoot(i.v);else if(i.k==='bar')drawBarricade(i.v);else if(i.k==='c')drawCivilian(i.v);else if(i.k==='z')drawZombie(i.v);else drawSurvivor(i.v)}drawObjective();drawVfx();drawLighting();updateHud()}
function updateCamera(dt:number){const ev=selectCameraEvent(game);let tx=0,ty=0,z=1.08;if(ev.targetId){const t=game.survivors.find(v=>v.id===ev.targetId)||game.civilians.find(v=>v.id===ev.targetId)||game.barricades.find(v=>v.id===ev.targetId);if(t){const p=iso(t.x,t.y);tx=p.x-innerWidth/2;ty=p.y-innerHeight*.5;z=ev.mode==='near-death'?1.35:ev.mode==='interior'?1.3:ev.mode==='rescue'?1.24:1.2}}if(ev.mode==='horde-overview')z=.9;camera.targetX=tx;camera.targetY=ty;camera.targetZoom=z;const k=1-Math.pow(.002,dt);camera.x+=(tx-camera.x)*k;camera.y+=(ty-camera.y)*k;camera.zoom+=(z-camera.zoom)*k}
function updateHud(){if(hideHud)return;const alive=game.survivors.filter(s=>s.alive).length,threat=Math.round(game.hordePressure*100),remaining=game.civilians.filter(c=>c.state!=='safe'&&c.state!=='dead').length;statusEl.textContent=game.status==='running'?`${game.time.phase.toUpperCase()} · DAY ${game.time.day}`:'SAFE HOUSE OVERRUN';hud.innerHTML=`<div class="brand">AI ZOMBIE SURVIVAL</div><div class="chips"><span>${alive} survivors</span><span>${game.zombies.filter(z=>z.health>0).length} infected</span><span>${threat}% threat</span><span>${game.score.rescued} rescued</span><span>${remaining} trapped</span><span>food ${Math.floor(game.resources.food)}</span><span>med ${Math.floor(game.resources.medicine)}</span><span>ammo ${Math.floor(game.resources.ammo)}</span><span>safehouse L${game.safeHouse.level} · ${Math.round(game.safeHouse.integrity)}%</span></div><div class="intent">${game.objective.label} · ${selectCameraEvent(game).mode.replaceAll('-',' ')} · H hide HUD · R restart · Space pause</div>`}
function tone(freq:number,d=.1,gain=.02,type:OscillatorType='sine',pan=0){if(audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),p=audio.createStereoPanner();o.type=type;o.frequency.value=freq;p.pan.value=Math.max(-1,Math.min(1,pan));g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(p).connect(master);o.start();o.stop(audio.currentTime+d+.02)}
function updateAudio(){if(audio.state!=='running')return;const plan=buildAudioPlan(game),freq:Record<string,number>={exploration:92,scavenging:110,tension:128,horde:66,combat:148,defense:104,critical:54,relief:164,defeat:44};musicOsc.frequency.setTargetAtTime(freq[plan.music]??92,audio.currentTime,.3);musicGain.gain.setTargetAtTime(.018+.035*plan.intensity,audio.currentTime,.5);ambOsc.frequency.setTargetAtTime(plan.ambience.includes('rain')?38:26,audio.currentTime,.6);ambGain.gain.setTargetAtTime(.008+(plan.ambience.includes('rain')?.016:.004),audio.currentTime,.7);for(const e of game.events.slice(-14)){if(heard.has(e.id))continue;heard.add(e.id);if(e.type==='shot')tone(150,.11,.03,'square',e.x/45);else if(e.type==='barricade-hit')tone(82,.16,.024,'sawtooth',e.x/45);else if(e.type==='near-death')tone(58,.25,.026,'sine');else if(e.type==='rescue')tone(420,.3,.025,'sine');else if(e.type==='safehouse-upgrade')tone(280,.45,.024,'triangle')}if(plan.footsteps>0&&visualTime>nextStepSound){tone(72,.045,.008,'square');nextStepSound=visualTime+.28/Math.min(2,1+plan.footsteps*.08)}if(plan.zombieBed>0&&visualTime>nextGroan){tone(plan.music==='horde'?48:56,.32,.012,'sawtooth',Math.sin(visualTime*.7));nextGroan=visualTime+(plan.music==='horde'?.7:1.8)}if(heard.size>256){const keep=new Set(game.events.slice(-64).map(e=>e.id));for(const id of heard)if(!keep.has(id))heard.delete(id)}}
function frame(now:number){const dt=Math.min(.08,(now-last)/1000);last=now;visualTime+=dt;if(!paused&&game.status==='running'){acc+=dt;while(acc>=fixed){game=stepGame(game,fixed);acc-=fixed}}updateCamera(dt);render();updateAudio();requestAnimationFrame(frame)}requestAnimationFrame(frame);
