import {
  createGame,stepGame,selectCameraEvent,survivorPose,zombiePose,districtPalette,buildAudioPlan,
  type Survivor,type Civilian,type Zombie,type Building,type Barricade,type LootNode,type GameState
} from '../index.js';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!;
const ctx=canvas.getContext('2d',{alpha:false})!;
const hud=document.querySelector<HTMLElement>('#hud')!;
const statusEl=document.querySelector<HTMLElement>('#status')!;
let game=createGame({seed:2026,zombieCount:180}) as GameState;
const evidenceMode=Boolean((globalThis as typeof globalThis&{__ZOMBIE_EVIDENCE__?:string}).__ZOMBIE_EVIDENCE__);
let paused=false,hideHud=false,last=performance.now(),acc=0,visualTime=0,lastEventId=0,nextStepSound=0,nextGroan=0;
const heard=new Set<number>(),fixed=1/30;
const camera={x:0,y:0,zoom:1.12,targetX:0,targetY:0,targetZoom:1.12};

const audio=new AudioContext(),master=audio.createGain(),musicGain=audio.createGain(),ambGain=audio.createGain();
master.gain.value=.42;musicGain.gain.value=0;ambGain.gain.value=0;musicGain.connect(master);ambGain.connect(master);master.connect(audio.destination);
const musicOsc=audio.createOscillator(),ambOsc=audio.createOscillator();musicOsc.type='triangle';ambOsc.type='sine';musicOsc.connect(musicGain);ambOsc.connect(ambGain);musicOsc.start();ambOsc.start();

function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=Math.floor(innerWidth*d);canvas.height=Math.floor(innerHeight*d);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
addEventListener('pointerdown',()=>audio.resume());
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'){hideHud=!hideHud;hud.style.display=hideHud?'none':'block'}if(e.key.toLowerCase()==='r'){game=createGame({seed:2026,zombieCount:180}) as GameState;camera.x=camera.y=0}if(e.code==='Space')paused=!paused});

function rawIso(x:number,y:number,z=0,zoom=camera.zoom){const s=26*zoom;return{x:(x-y)*s,y:(x+y)*s*.5-z*s}}
function iso(x:number,y:number,z=0){const p=rawIso(x,y,z);return{x:p.x+innerWidth/2-camera.x,y:p.y+innerHeight*.48-camera.y}}
function poly(points:{x:number;y:number}[],fill:string,stroke?:string,width=1){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function diamond(x:number,y:number,w:number,h:number,fill:string,stroke?:string){poly([iso(x-w/2,y-h/2),iso(x+w/2,y-h/2),iso(x+w/2,y+h/2),iso(x-w/2,y+h/2)],fill,stroke)}
function line(a:{x:number;y:number},b:{x:number;y:number},stroke:string,width=1,dash:number[]=[]){ctx.save();ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function shadow(x:number,y:number,rx:number,ry:number,a=.28){const p=iso(x,y);ctx.save();ctx.translate(p.x,p.y);ctx.scale(1,.42);ctx.beginPath();ctx.ellipse(0,0,rx*camera.zoom,ry*camera.zoom,0,0,Math.PI*2);ctx.fillStyle=`rgba(0,0,0,${a})`;ctx.fill();ctx.restore()}
function shade(hex:string,d:number){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+d)),g=Math.max(0,Math.min(255,((n>>8)&255)+d)),b=Math.max(0,Math.min(255,(n&255)+d));return`rgb(${r},${g},${b})`}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}

function drawRoads(){
  const road='#242a29',edge='rgba(205,198,173,.10)',mark='rgba(218,207,166,.20)';
  for(const y of [-8,26]){diamond(0,y,112,7,road);line(iso(-54,y),iso(54,y),mark,1,[10,13]);line(iso(-54,y-3.1),iso(54,y-3.1),edge);line(iso(-54,y+3.1),iso(54,y+3.1),edge)}
  for(const x of [-17,17]){diamond(x,8,7,78,road);line(iso(x,-29),iso(x,45),mark,1,[10,13]);line(iso(x-3.1,-29),iso(x-3.1,45),edge);line(iso(x+3.1,-29),iso(x+3.1,45),edge)}
  for(let i=-4;i<=4;i++){line(iso(-3+i*.8,-8-3),iso(-3+i*.8,-8+3),'rgba(230,224,201,.16)',2)}
}
function drawStreetProps(){
  const cars:[number,number,number,string][]=[[-24,-8,.1,'#505958'],[-8,-8,.1,'#62564b'],[26,-8,.1,'#4c5559'],[-17,13,1.4,'#595248'],[17,1,1.4,'#4e5954'],[17,31,1.4,'#5a514a'],[-2,26,.1,'#50565a']];
  for(const [x,y,a,c] of cars){const p=iso(x,y,.12);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a*.22);ctx.fillStyle=c;ctx.fillRect(-13,-6,26,10);ctx.fillStyle='rgba(183,205,202,.20)';ctx.fillRect(-6,-5,11,4);ctx.fillStyle='#171b1a';ctx.fillRect(-11,4,6,3);ctx.fillRect(6,4,6,3);ctx.restore()}
  for(let i=0;i<18;i++){const x=-46+(i*17)%92,y=-25+((i*29)%65),p=iso(x,y,.05);ctx.fillStyle=i%3?'rgba(103,91,72,.55)':'rgba(77,82,78,.65)';ctx.fillRect(p.x-2,p.y-2,4+(i%4),2+(i%3))}
  for(const [x,y] of [[-17,-13],[17,-13],[-17,22],[17,22],[0,29]] as [number,number][]){const b=iso(x,y),t=iso(x,y,2.4);line(b,t,'#3f4541',3);ctx.fillStyle=game.time.phase==='night'?'rgba(242,205,122,.85)':'#777260';ctx.beginPath();ctx.arc(t.x,t.y,4,0,Math.PI*2);ctx.fill()}
}
function drawGround(){
  const sky=ctx.createLinearGradient(0,0,0,innerHeight);sky.addColorStop(0,game.time.phase==='night'?'#0c1216':'#68706b');sky.addColorStop(1,game.time.phase==='night'?'#151b1c':'#252b29');ctx.fillStyle=sky;ctx.fillRect(0,0,innerWidth,innerHeight);
  for(const d of game.districts){const p=districtPalette(d.kind);diamond(d.x,d.y,d.w,d.h,shade(p.ground,-4),'rgba(255,255,255,.025)')}
  drawRoads();drawStreetProps();
  for(const d of game.districts){const q=iso(d.x-d.w*.42,d.y-d.h*.42,.03);ctx.fillStyle='rgba(235,226,198,.16)';ctx.font='600 10px system-ui';ctx.fillText(d.kind.toUpperCase(),q.x,q.y)}
  diamond(0,0,17,14,'#343a37','rgba(225,208,163,.10)');diamond(0,0,11,9,'#4b514d');
}

function drawWindow(x:number,y:number,z:number,lit=false){const p=iso(x,y,z);ctx.fillStyle=lit?'rgba(246,211,130,.62)':'rgba(20,27,27,.70)';ctx.fillRect(p.x-5,p.y-5,8,6);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(p.x-4,p.y-4,6,1)}
function drawInterior(b:Building){diamond(b.x,b.y,b.w*.82,b.h*.82,b.interiorLit?'#665c47':'#373b38','rgba(235,213,159,.28)');const h=hash(b.id);for(let i=0;i<3;i++){const dx=((h>>(i*4))&7)/7*b.w*.45-b.w*.22,dy=-b.h*.22+i*b.h*.20,p=iso(b.x+dx,b.y+dy,.18);ctx.fillStyle=i===0?'#755f42':'#4f5550';ctx.fillRect(p.x-10,p.y-4,20,7)}const door=iso(b.x,b.y+b.h*.35,.2);ctx.fillStyle='#1e2422';ctx.fillRect(door.x-7,door.y-10,14,12)}
function drawBuilding(b:Building){
  const pal=districtPalette(b.district),z=1.5+b.floors*.92,damage=b.damage;
  const a=iso(b.x-b.w/2,b.y-b.h/2),bb=iso(b.x+b.w/2,b.y-b.h/2),c=iso(b.x+b.w/2,b.y+b.h/2),d=iso(b.x-b.w/2,b.y+b.h/2),at=iso(b.x-b.w/2,b.y-b.h/2,z),bt=iso(b.x+b.w/2,b.y-b.h/2,z),ct=iso(b.x+b.w/2,b.y+b.h/2,z),dt=iso(b.x-b.w/2,b.y+b.h/2,z);
  poly([bb,c,ct,bt],shade(pal.wall,-24),'rgba(0,0,0,.30)');poly([d,c,ct,dt],shade(pal.wall,-38),'rgba(0,0,0,.34)');
  if(b.roofVisible){poly([at,bt,ct,dt],shade(pal.roof,-damage*28),'rgba(0,0,0,.38)');if(hash(b.id)%3===0){const vent=iso(b.x+.9,b.y-.8,z+.24);ctx.fillStyle='#4d524e';ctx.fillRect(vent.x-5,vent.y-5,10,6)}}else drawInterior(b);
  const lit=game.time.phase==='night'&&(b.kind==='safehouse'||b.interiorLit);for(let f=0;f<b.floors;f++){drawWindow(b.x+b.w/2+.02,b.y-b.h*.15,z*.20+f*.62+.45,lit);drawWindow(b.x+b.w*.18,b.y+b.h/2+.02,z*.20+f*.62+.45,lit&&f===0)}
  const sign=iso(b.x+b.w/2+.04,b.y+b.h*.12,.85);if(b.kind==='hospital'){ctx.fillStyle='#d7d2c6';ctx.fillRect(sign.x-6,sign.y-2,12,4);ctx.fillRect(sign.x-2,sign.y-6,4,12)}else if(b.kind==='police'){ctx.fillStyle='#83939a';ctx.fillRect(sign.x-9,sign.y-4,18,7)}else if(b.kind==='shop'||b.kind==='supermarket'){ctx.fillStyle=pal.accent;ctx.fillRect(sign.x-11,sign.y-4,22,5)}else if(b.kind==='warehouse'){ctx.strokeStyle='#2c312f';ctx.lineWidth=2;ctx.strokeRect(sign.x-11,sign.y-9,22,13)}
  if(damage>.40){const p=iso(b.x+b.w/2+.03,b.y,.9);ctx.strokeStyle='rgba(30,27,24,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x-2,p.y-16);ctx.lineTo(p.x+5,p.y-5);ctx.lineTo(p.x,p.y+3);ctx.lineTo(p.x+7,p.y+12);ctx.stroke()}
  if(damage>.52){const p=iso(b.x,b.y,z+.25),r=8+Math.sin(visualTime*.7+hash(b.id)%10)*3;ctx.fillStyle='rgba(55,58,55,.15)';ctx.beginPath();ctx.arc(p.x+6,p.y-5,r,0,Math.PI*2);ctx.fill()}
  if(b.kind==='safehouse'){const p=iso(0,0,z+.3);ctx.fillStyle='#efd57e';ctx.font='700 12px system-ui';ctx.fillText(`SAFE HOUSE · L${game.safeHouse.level}`,p.x-54,p.y);if(game.safeHouse.features.includes('generator')){const g=iso(3.3,1.8,.25);ctx.fillStyle='#67705f';ctx.fillRect(g.x-9,g.y-8,18,10);ctx.fillStyle='#d2bd67';ctx.fillRect(g.x+4,g.y-5,3,3)}if(game.safeHouse.features.includes('medical-cot')){const m=iso(-2.8,1.6,.22);ctx.fillStyle='#d9d5c7';ctx.fillRect(m.x-10,m.y-5,20,6);ctx.fillStyle='#a65a51';ctx.fillRect(m.x-2,m.y-8,4,8)}if(game.safeHouse.features.includes('lookout')){const l=iso(3,-2.5,2.4);ctx.strokeStyle='#5a4635';ctx.lineWidth=3;ctx.strokeRect(l.x-8,l.y-13,16,13)}if(game.safeHouse.features.includes('expanded-storage'))for(let i=0;i<3;i++){const s=iso(-3+i*1.2,-2,.2);ctx.fillStyle='#816847';ctx.fillRect(s.x-6,s.y-6,12,8)}}
}

function drawBarricade(b:Barricade){const p=iso(b.x,b.y,.05),hp=b.hp/b.maxHp;shadow(b.x,b.y,19,8,.35);ctx.save();ctx.translate(p.x,p.y-6);ctx.rotate(b.angle*.32);if(b.material==='vehicle'){ctx.fillStyle='#59615b';ctx.fillRect(-20,-9,40,12);ctx.fillStyle='#222827';ctx.fillRect(-15,2,8,5);ctx.fillRect(9,2,8,5)}else{ctx.fillStyle=b.material==='metal'?'#737c78':'#765c3d';for(let i=-2;i<=2;i++){ctx.save();ctx.rotate(i*.045);ctx.fillRect(-19,-8+i*2,38,5);ctx.restore()}}ctx.strokeStyle=hp<.35?'#d77961':'rgba(18,21,20,.65)';ctx.lineWidth=2;ctx.strokeRect(-20,-10,40,14);if(hp<.55){ctx.fillStyle='rgba(190,153,105,.75)';ctx.fillRect(-15,8,4,3);ctx.fillRect(5,9,5,3)}ctx.restore()}
function drawLoot(l:LootNode){if(l.amount<=0)return;const p=iso(l.x,l.y,.18);shadow(l.x,l.y,8,4,.18);ctx.fillStyle=l.kind==='medicine'?'#b9c2b9':l.kind==='ammo'?'#6c6a5d':l.kind==='fuel'?'#7b5d4d':'#91764e';ctx.fillRect(p.x-6,p.y-8,12,9);ctx.strokeStyle='rgba(235,221,179,.25)';ctx.strokeRect(p.x-6,p.y-8,12,9)}

function drawSurvivor(s:Survivor){
  if(!s.alive){const p=iso(s.x,s.y,.04);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(.35);ctx.fillStyle='#363b39';ctx.fillRect(-13,-3,25,7);ctx.restore();return}
  const p=iso(s.x,s.y),pose=survivorPose(s),stride=Math.sin(visualTime*(5+pose.stride*4)+Number(s.id.slice(2)))*pose.stride,scale=1.15*camera.zoom;shadow(s.x,s.y,11,6,.32);ctx.save();ctx.translate(p.x,p.y-19*scale);ctx.scale(scale,scale);if(pose.stance==='limp')ctx.rotate(.10);if(pose.stance==='frightened')ctx.rotate(-.05+Math.sin(visualTime*8)*.025);
  const colors:Record<string,string>={leader:'#c6aa6b',scout:'#738e80',medic:'#c1bfb2',defender:'#82766d',scavenger:'#a1845c',engineer:'#788895'};
  ctx.strokeStyle='#202524';ctx.lineWidth=3.5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,9);ctx.lineTo(-5+stride*3,18);ctx.moveTo(2,9);ctx.lineTo(5-stride*3,18);ctx.stroke();ctx.fillStyle=colors[s.role];ctx.fillRect(-5,-3,10,13);ctx.fillStyle='#353c39';ctx.fillRect(-6,5,12,4);
  ctx.strokeStyle='#ad846a';ctx.lineWidth=3;ctx.beginPath();if(pose.stance==='weapon-forward'){ctx.moveTo(-3,0);ctx.lineTo(9,-2);ctx.moveTo(3,0);ctx.lineTo(10,-1)}else{ctx.moveTo(-4,0);ctx.lineTo(-7,7+stride*2);ctx.moveTo(4,0);ctx.lineTo(7,7-stride*2)}ctx.stroke();ctx.fillStyle='#a87f66';ctx.beginPath();ctx.arc(0,-7,4.2,0,Math.PI*2);ctx.fill();
  if(s.role==='medic'){ctx.fillStyle='#b85b53';ctx.fillRect(3,1,3,6)}if(s.role==='engineer'){ctx.strokeStyle='#b69b66';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-7,3);ctx.lineTo(-11,8);ctx.stroke()}if(s.carrying>0){ctx.fillStyle='#624d36';ctx.fillRect(-10,0,5,10);ctx.strokeStyle='#8e754f';ctx.strokeRect(-10,0,5,10)}if(pose.stance==='weapon-forward'){ctx.strokeStyle='#252a28';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(8,-2);ctx.lineTo(16,-4);ctx.stroke()}if(pose.stance==='escort'){ctx.strokeStyle='#e0cb7d';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,-10,9,0,Math.PI*2);ctx.stroke()}if(s.health<45){ctx.fillStyle='rgba(166,69,59,.72)';ctx.fillRect(-5,5,5,2)}ctx.restore()
}
function drawCivilian(c:Civilian){if(c.state==='safe'||c.state==='dead')return;const p=iso(c.x,c.y),scale=1.05*camera.zoom;shadow(c.x,c.y,8,4,.23);ctx.save();ctx.translate(p.x,p.y-17*scale);ctx.scale(scale,scale);const bob=Math.sin(visualTime*5+Number(c.id.slice(2)))*.8;ctx.translate(0,bob);ctx.strokeStyle='#373a36';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-2,7);ctx.lineTo(-4,16);ctx.moveTo(2,7);ctx.lineTo(4,16);ctx.stroke();ctx.fillStyle=c.state==='trapped'?'#bc986f':'#84957f';ctx.fillRect(-4,-2,8,10);ctx.fillStyle='#a77d65';ctx.beginPath();ctx.arc(0,-6,3.6,0,Math.PI*2);ctx.fill();if(c.state==='trapped'){ctx.strokeStyle='rgba(244,210,111,.85)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,-7,9+Math.sin(visualTime*4)*2,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawZombie(z:Zombie){
  if(z.health<=0){const p=iso(z.x,z.y,.02);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-.35+(z.variant%3)*.2);ctx.fillStyle='#344039';ctx.fillRect(-10,-2,20,5);ctx.restore();return}
  const p=iso(z.x,z.y),pose=zombiePose(z),sway=Math.sin(visualTime*(3.2*pose.cadence)+z.variant*1.7)*2.2,body=pose.silhouette==='heavy'?1.35:pose.silhouette==='lean'?.88:1,scale=1.02*camera.zoom*body;shadow(z.x,z.y,9*body,5,.26);ctx.save();ctx.translate(p.x,p.y-17*scale);ctx.scale(scale,scale);ctx.rotate(sway*.014+(pose.stance==='lunge'?.12:0));ctx.strokeStyle='#2e3933';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,8);ctx.lineTo(-4-sway*.35,17);ctx.moveTo(2,8);ctx.lineTo(5+sway*.3,17);ctx.stroke();ctx.fillStyle=z.archetype==='brute'?'#5c5548':z.archetype==='runner'?'#66735e':['#52655a','#5e6652','#615f55'][z.variant%3];ctx.fillRect(-4,-2,9,12);ctx.strokeStyle='#58685e';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(-3,0);ctx.lineTo(-8,6+sway*.2);ctx.moveTo(3,0);ctx.lineTo(pose.stance==='lunge'?11:8,4-sway*.2);ctx.stroke();ctx.fillStyle='#71806f';ctx.beginPath();ctx.arc(0,-6,4,0,Math.PI*2);ctx.fill();if(z.archetype==='brute'){ctx.strokeStyle='#947a55';ctx.lineWidth=2;ctx.strokeRect(-6,-3,12,13)}if(z.archetype==='runner'){ctx.fillStyle='#313a34';ctx.fillRect(-5,7,10,2)}ctx.restore()
}
function drawObjective(){const c=game.civilians.find(v=>v.id===game.objective.targetId);if(!c||c.state==='safe')return;const p=iso(c.x,c.y,.5),r=15+Math.sin(visualTime*3)*3;ctx.strokeStyle='rgba(242,207,104,.72)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y-18,r,0,Math.PI*2);ctx.stroke()}
function drawVfx(){for(const e of game.events){if(e.id<=Math.max(lastEventId-45,0))continue;const age=game.time.elapsed-e.time;if(age<0||age>1.3)continue;const p=iso(e.x,e.y,.5),a=1-age/1.3;if(e.type==='shot'){ctx.fillStyle=`rgba(255,215,126,${a})`;ctx.beginPath();ctx.arc(p.x,p.y-20,6*a+1,0,Math.PI*2);ctx.fill()}if(e.type==='barricade-hit'){ctx.fillStyle=`rgba(194,153,101,${.65*a})`;for(let i=0;i<6;i++)ctx.fillRect(p.x+(i-3)*4,p.y-10-age*20-(i%2)*5,3,3)}if(['loot','rescue','safehouse-upgrade'].includes(e.type)){ctx.fillStyle=`rgba(231,208,127,${a})`;ctx.font='700 12px system-ui';ctx.fillText(e.type==='loot'?'SUPPLIES SECURED':e.type==='rescue'?'CIVILIAN RESCUED':'SAFE HOUSE FORTIFIED',p.x-50,p.y-28-age*15)}}lastEventId=game.events.at(-1)?.id??lastEventId}
function drawLighting(){
  if(game.time.phase==='sunset'){const g=ctx.createLinearGradient(0,0,innerWidth,innerHeight);g.addColorStop(0,'rgba(128,70,40,.20)');g.addColorStop(1,'rgba(22,34,40,.08)');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight)}
  if(game.time.phase==='night'){ctx.fillStyle='rgba(7,13,19,.64)';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.globalCompositeOperation='screen';for(const s of game.survivors.filter(s=>s.alive)){const p=iso(s.x,s.y,.8),g=ctx.createRadialGradient(p.x,p.y,4,p.x,p.y,80*camera.zoom);g.addColorStop(0,'rgba(255,224,153,.24)');g.addColorStop(.45,'rgba(238,204,136,.10)');g.addColorStop(1,'rgba(255,224,150,0)');ctx.fillStyle=g;ctx.fillRect(p.x-95,p.y-95,190,190)}for(const [x,y] of [[-17,-13],[17,-13],[-17,22],[17,22]] as [number,number][]){const p=iso(x,y,2.3),g=ctx.createRadialGradient(p.x,p.y,1,p.x,p.y,65);g.addColorStop(0,'rgba(255,205,115,.18)');g.addColorStop(1,'rgba(255,205,115,0)');ctx.fillStyle=g;ctx.fillRect(p.x-70,p.y-70,140,140)}ctx.globalCompositeOperation='source-over'}
  if(game.weather.kind==='fog'){ctx.fillStyle=`rgba(190,199,196,${.11*game.weather.intensity})`;ctx.fillRect(0,0,innerWidth,innerHeight)}if(game.weather.kind==='rain'||game.weather.kind==='storm'){ctx.strokeStyle=`rgba(188,205,211,${.28+game.weather.intensity*.18})`;ctx.lineWidth=1;for(let i=0;i<120;i++){const x=((i*97+visualTime*230)%(innerWidth+80))-40,y=((i*53+visualTime*430)%(innerHeight+100))-50;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+20);ctx.stroke()}}
  const vg=ctx.createRadialGradient(innerWidth/2,innerHeight/2,innerHeight*.18,innerWidth/2,innerHeight/2,innerWidth*.72);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.28)');ctx.fillStyle=vg;ctx.fillRect(0,0,innerWidth,innerHeight)
}
function render(){drawGround();const items:any[]=[];for(const b of game.buildings)items.push({d:b.x+b.y,k:'b',v:b});for(const l of game.loot)items.push({d:l.x+l.y,k:'l',v:l});for(const b of game.barricades)items.push({d:b.x+b.y+.2,k:'bar',v:b});for(const c of game.civilians)items.push({d:c.x+c.y+.45,k:'c',v:c});for(const z of game.zombies)if(z.health>0||Math.hypot(z.x,z.y)<24)items.push({d:z.x+z.y+.4,k:'z',v:z});for(const s of game.survivors)items.push({d:s.x+s.y+.6,k:'s',v:s});items.sort((a,b)=>a.d-b.d);for(const i of items){if(i.k==='b')drawBuilding(i.v);else if(i.k==='l')drawLoot(i.v);else if(i.k==='bar')drawBarricade(i.v);else if(i.k==='c')drawCivilian(i.v);else if(i.k==='z')drawZombie(i.v);else drawSurvivor(i.v)}drawObjective();drawVfx();drawLighting();updateHud()}

function updateCamera(dt:number){const ev=selectCameraEvent(game);let target:any=null,z=1.10;if(ev.targetId)target=game.survivors.find(v=>v.id===ev.targetId)||game.civilians.find(v=>v.id===ev.targetId)||game.barricades.find(v=>v.id===ev.targetId);if(ev.mode==='horde-overview')z=.92;else if(ev.mode==='near-death')z=1.62;else if(ev.mode==='interior')z=1.55;else if(ev.mode==='rescue')z=1.42;else if(ev.mode==='scavenge')z=1.46;else if(ev.mode==='defense')z=1.34;else if(ev.mode==='survivor-follow')z=1.28;else if(ev.mode==='failure')z=1.02;if(target){const rp=rawIso(target.x,target.y,.5,z);camera.targetX=rp.x;camera.targetY=rp.y-innerHeight*.02}else{camera.targetX=0;camera.targetY=0}camera.targetZoom=z;const k=evidenceMode?1-Math.pow(.0000001,dt):1-Math.pow(.002,dt);camera.x+=(camera.targetX-camera.x)*k;camera.y+=(camera.targetY-camera.y)*k;camera.zoom+=(camera.targetZoom-camera.zoom)*k}
function updateHud(){if(hideHud)return;const alive=game.survivors.filter(s=>s.alive).length,threat=Math.round(game.hordePressure*100),remaining=game.civilians.filter(c=>c.state!=='safe'&&c.state!=='dead').length;statusEl.textContent=game.status==='running'?`${game.time.phase.toUpperCase()} · DAY ${game.time.day}`:'SAFE HOUSE OVERRUN';hud.innerHTML=`<div class="brand">AI ZOMBIE SURVIVAL</div><div class="chips"><span>${alive} survivors</span><span>${game.zombies.filter(z=>z.health>0).length} infected</span><span>${threat}% threat</span><span>${game.score.rescued} rescued</span><span>${remaining} trapped</span><span>food ${Math.floor(game.resources.food)}</span><span>med ${Math.floor(game.resources.medicine)}</span><span>ammo ${Math.floor(game.resources.ammo)}</span><span>safehouse L${game.safeHouse.level} · ${Math.round(game.safeHouse.integrity)}%</span></div><div class="intent">${game.objective.label} · ${selectCameraEvent(game).mode.replaceAll('-',' ')} · H hide HUD · R restart · Space pause</div>`}
function tone(freq:number,d=.1,gain=.02,type:OscillatorType='sine',pan=0){if(audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),p=audio.createStereoPanner();o.type=type;o.frequency.value=freq;p.pan.value=Math.max(-1,Math.min(1,pan));g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(p).connect(master);o.start();o.stop(audio.currentTime+d+.02)}
function updateAudio(){if(audio.state!=='running')return;const plan=buildAudioPlan(game),freq:Record<string,number>={exploration:92,scavenging:110,tension:128,horde:66,combat:148,defense:104,critical:54,relief:164,defeat:44};musicOsc.frequency.setTargetAtTime(freq[plan.music]??92,audio.currentTime,.3);musicGain.gain.setTargetAtTime(.018+.035*plan.intensity,audio.currentTime,.5);ambOsc.frequency.setTargetAtTime(plan.ambience.includes('rain')?38:26,audio.currentTime,.6);ambGain.gain.setTargetAtTime(.008+(plan.ambience.includes('rain')?.016:.004),audio.currentTime,.7);for(const e of game.events.slice(-14)){if(heard.has(e.id))continue;heard.add(e.id);if(e.type==='shot')tone(150,.11,.03,'square',e.x/45);else if(e.type==='barricade-hit')tone(82,.16,.024,'sawtooth',e.x/45);else if(e.type==='near-death')tone(58,.25,.026,'sine');else if(e.type==='rescue')tone(420,.3,.025,'sine');else if(e.type==='safehouse-upgrade')tone(280,.45,.024,'triangle')}if(plan.footsteps>0&&visualTime>nextStepSound){tone(72,.045,.008,'square');nextStepSound=visualTime+.28/Math.min(2,1+plan.footsteps*.08)}if(plan.zombieBed>0&&visualTime>nextGroan){tone(plan.music==='horde'?48:56,.32,.012,'sawtooth',Math.sin(visualTime*.7));nextGroan=visualTime+(plan.music==='horde'?.7:1.8)}if(heard.size>256){const keep=new Set(game.events.slice(-64).map(e=>e.id));for(const id of heard)if(!keep.has(id))heard.delete(id)}}
function frame(now:number){const dt=Math.min(.08,(now-last)/1000);last=now;visualTime+=dt;if(!paused&&game.status==='running'){acc+=dt;while(acc>=fixed){game=stepGame(game,fixed);acc-=fixed}}updateCamera(dt);render();updateAudio();requestAnimationFrame(frame)}requestAnimationFrame(frame);
