import{checksum}from '../../../../packages/replay/src/index';
import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import{chooseBasicAntAction}from '../ai/basic';
import{assertAntColonyInvariants}from '../state/invariants';
import type{AntAction,AntColonyState,AntRole,ProgressBand,Season,StepOutput,Weather}from '../state/types';
function cellOf(state:AntColonyState,x:number,y:number){return y*state.config.width+x}
function bandFor(state:AntColonyState):ProgressBand{const ratio=state.ants.length/state.config.targetPopulation;if(ratio>=1)return'ascendant';if(ratio>=.75)return'thriving';if(ratio>=.5)return'established';if(ratio>=.25)return'growing';return'founding'}
function seasonFor(state:AntColonyState):Season{const index=Math.floor(state.tick/state.config.seasonLengthTicks)%4;return(['spring','summer','autumn','winter']as const)[index]!}
function weatherFor(state:AntColonyState):Weather{const phase=Math.floor(state.tick/state.config.dayLengthTicks)%8;if(phase===2)return'rain';if(phase===5)return'heat';if(phase===6)return'drought';return'clear'}
function roleForBirth(id:number):AntRole{if(id%12===0)return'soldier';if(id%8===0)return'scout';if(id%6===0)return'nurse';if(id%4===0)return'digger';return'worker'}
function terminal(state:AntColonyState,reason:'ascension'|'extinction'|'stagnation',events:StepOutput['events']){const summary={reason,tick:state.tick,population:state.ants.length,foodStore:state.colony.foodStore,tunnelsDug:state.colony.tunnelsDug,score:state.ants.length*20+state.colony.foodDelivered*3+state.colony.tunnelsDug*8+state.colony.predatorsDefeated*50};state.result={...summary,finalChecksum:checksum(summary)};state.lifecycle='result';state.intermissionRemaining=state.config.intermissionTicks;events.push({type:'result',data:{reason,score:summary.score,population:summary.population,finalChecksum:state.result.finalChecksum}})}
function updateBrood(state:AntColonyState,events:StepOutput['events']){
  if(state.tick>0&&state.tick-state.queen.lastEggTick>=state.config.broodInterval&&state.ants.length+state.brood.length<state.config.maxAnts&&state.colony.foodStore>=2){state.colony.foodStore-=2;state.queen.lastEggTick=state.tick;state.queen.eggsLaid++;state.colony.eggsLaid++;state.brood.push({id:state.nextBroodId++,stage:'egg',ageTicks:0,health:100});events.push({type:'egg-laid',data:{brood:state.brood.length}})}
  const survivors=[];for(const brood of state.brood.sort((a,b)=>a.id-b.id)){brood.ageTicks++;if(brood.stage==='egg'&&brood.ageTicks>=state.config.eggHatchTicks){brood.stage='larva';brood.ageTicks=0;events.push({type:'brood-stage',data:{id:brood.id,stage:'larva'}});survivors.push(brood);continue}if(brood.stage==='larva'&&brood.ageTicks>=state.config.larvaTicks){if(state.colony.foodStore>0){state.colony.foodStore--;brood.stage='pupa';brood.ageTicks=0;events.push({type:'brood-stage',data:{id:brood.id,stage:'pupa'}})}survivors.push(brood);continue}if(brood.stage==='pupa'&&brood.ageTicks>=state.config.pupaTicks&&state.ants.length<state.config.maxAnts){const id=state.nextAntId++,cell=state.world.nestCenter,role=roleForBirth(id);state.ants.push({id,role,x:cell%state.config.width,y:Math.floor(cell/state.config.width),health:100,energy:90,carryingFood:0,task:role==='nurse'?'nurse':role==='digger'?'dig':role==='soldier'?'guard':role==='scout'?'explore':'forage',goalCell:null,intent:'Joining the colony workforce',confidence:70,stuckTicks:0,lastCell:cell,ageTicks:0,bias:id%4});state.colony.antsBorn++;state.colony.meaningfulEventTick=state.tick;events.push({type:'ant-born',data:{id,role,population:state.ants.length}});continue}survivors.push(brood)}state.brood=survivors;
}
function depositPheromone(state:AntColonyState,antIndex:number){const ant=state.ants[antIndex]!,cell=cellOf(state,ant.x,ant.y),amount=state.config.pheromoneDeposit;if(ant.carryingFood>0)state.world.pheromones.food[cell]=Math.min(255,state.world.pheromones.food[cell]!+amount);else state.world.pheromones.home[cell]=Math.min(255,state.world.pheromones.home[cell]!+Math.max(1,Math.floor(amount/2)))}
function applyAction(state:AntColonyState,antIndex:number,action:AntAction,occupancy:number[],reserved:Set<number>,events:StepOutput['events']){const ant=state.ants[antIndex]!,current=cellOf(state,ant.x,ant.y);ant.task=action.task;ant.intent=action.intent;ant.confidence=action.confidence;ant.ageTicks++;if(state.tick%20===0)ant.energy=Math.max(0,ant.energy-1);
  if(action.kind==='pickup'){const amount=Math.min(2,state.world.food[current]!);if(amount>0){state.world.food[current]-=amount;ant.carryingFood=amount;ant.task='return';events.push({type:'food-picked',data:{antId:ant.id,amount}})}return}
  if(action.kind==='deposit'){if(ant.carryingFood>0){const amount=ant.carryingFood;ant.carryingFood=0;state.colony.foodStore+=amount;state.colony.foodDelivered+=amount;state.colony.meaningfulEventTick=state.tick;ant.energy=Math.min(100,ant.energy+4);events.push({type:'food-delivered',data:{antId:ant.id,amount,store:state.colony.foodStore}})}return}
  if(action.kind==='rest'){ant.energy=Math.min(100,ant.energy+3);return}
  if(action.kind!=='move'&&action.kind!=='dig')return;const target=action.cell;if(target<0||target>=state.world.tiles.length)return;if(action.kind==='dig'){if(state.world.tiles[target]!==0||reserved.has(target))return;state.world.tiles[target]=1;state.world.discovered[target]=1;state.world.pheromones.excavation[target]=180;state.colony.tunnelsDug++;state.colony.meaningfulEventTick=state.tick;reserved.add(target);events.push({type:'tunnel-dug',data:{antId:ant.id,cell:target,total:state.colony.tunnelsDug}})}
  if(occupancy[target]!>=state.config.tunnelCapacity){ant.stuckTicks++;return}occupancy[current]=Math.max(0,occupancy[current]!-1);occupancy[target]++;ant.x=target%state.config.width;ant.y=Math.floor(target/state.config.width);ant.stuckTicks=target===ant.lastCell?ant.stuckTicks+1:0;ant.lastCell=target;ant.energy=Math.max(0,ant.energy-1);depositPheromone(state,antIndex);
}
function decayPheromones(state:AntColonyState){if(state.config.pheromoneDecay===0)return;for(const field of Object.values(state.world.pheromones))for(let i=0;i<field.length;i++)field[i]=Math.max(0,field[i]!-state.config.pheromoneDecay);state.world.pheromones.home[state.world.nestCenter]=255}
export function stepAntColony(state:AntColonyState,rng:NamedRng):StepOutput{void rng;const events:StepOutput['events']=[];assertAntColonyInvariants(state);if(state.queen.health<=0){terminal(state,'extinction',events);return{state,events}}state.tick++;state.day=1+Math.floor(state.tick/state.config.dayLengthTicks);state.season=seasonFor(state);state.weather=weatherFor(state);
  if(state.tick%state.config.strategyInterval===0){const foodPerAnt=state.colony.foodStore/Math.max(1,state.ants.length);const previous=state.colony.strategy;if(foodPerAnt<1.5){state.colony.strategy='recovery';state.colony.strategyReason='Food reserves are below the emergency threshold'}else if(state.colony.threat>35){state.colony.strategy='defense';state.colony.strategyReason='Alarm pressure requires defensive allocation'}else if(state.brood.length>state.ants.length/2&&foodPerAnt>5){state.colony.strategy='brood-boom';state.colony.strategyReason='Strong reserves can support rapid brood growth'}else if(state.colony.tunnelsDug<Math.ceil(state.ants.length/3)){state.colony.strategy='expansion';state.colony.strategyReason='Nest capacity is behind population growth'}else{state.colony.strategy='foraging';state.colony.strategyReason='Balanced reserves favor efficient foraging'}if(previous!==state.colony.strategy)events.push({type:'strategy-changed',data:{strategy:state.colony.strategy,reason:state.colony.strategyReason}})}
  updateBrood(state,events);const occupancy=new Array<number>(state.world.tiles.length).fill(0);for(const ant of state.ants)occupancy[cellOf(state,ant.x,ant.y)]++;const reserved=new Set<number>();const ordered=state.ants.map((_,i)=>i).sort((a,b)=>state.ants[a]!.id-state.ants[b]!.id);for(const i of ordered){const ant=state.ants[i]!,action=chooseBasicAntAction(state,ant);applyAction(state,i,action,occupancy,reserved,events)}decayPheromones(state);
  const previousBand=state.colony.progressBand,nextBand=bandFor(state);if(nextBand!==previousBand){state.colony.progressBand=nextBand;state.colony.meaningfulEventTick=state.tick;events.push({type:'milestone',data:{band:nextBand,population:state.ants.length}})}
  if(state.ants.length>=state.config.targetPopulation&&state.colony.tunnelsDug>=Math.ceil(state.config.targetPopulation/4)&&state.colony.foodStore>=state.config.targetPopulation)terminal(state,'ascension',events);else if(state.ants.length===0&&state.brood.length===0)terminal(state,'extinction',events);else if(state.tick-state.colony.meaningfulEventTick>=state.config.noProgressTicks)terminal(state,'stagnation',events);assertAntColonyInvariants(state);return{state,events}}
