import type{GameLifecycle,MazeConfig,MazeIntentMode,MazeRunResult}from '../../../../packages/game-contracts/src/index';
export interface MazeDoor{id:string;a:number;b:number;requiredKeyId:string;open:boolean;critical:boolean;temporaryUntilTick:number|null}
export interface MazeKey{id:string;cell:number;collected:boolean}
export interface MazeThreat{id:string;cell:number;route:number[];routeIndex:number;direction:1|-1;lastSeenTick:number|null;active:boolean}
export interface MazeWorld{schemaVersion:1;width:number;height:number;passages:number[];start:number;exit:number;doors:MazeDoor[];keys:MazeKey[];traps:number[];clues:number[];checkpoints:number[];threats:MazeThreat[];blockedCells:number[];profile:string}
export interface MazeFeatures{profile:string;cells:number;edges:number;loops:number;deadEnds:number;branchCells:number;shortestSolutionLength:number;chambers:number;dependencyDepth:number;trapCount:number;threatCount:number}
export interface MazeGenerationDiagnostics{attempts:number;fallbackUsed:boolean;failedReasons:string[]}
export interface GeneratedMaze{world:MazeWorld;features:MazeFeatures;diagnostics:MazeGenerationDiagnostics}
export interface MazeBeliefCell{cell:number;neighbors:number[];lastSeenTick:number;confidencePermille:number;visits:number;trap:boolean;checkpoint:boolean;clue:boolean;exit:boolean}
export interface MazeBeliefDoor{id:string;a:number;b:number;requiredKeyId:string;open:boolean;lastSeenTick:number}
export interface MazeBeliefKey{id:string;cell:number;collected:boolean;lastSeenTick:number}
export interface MazeBeliefThreat{id:string;cell:number;lastSeenTick:number}
export interface MazeBeliefState{schemaVersion:1;cells:Record<string,MazeBeliefCell>;doors:Record<string,MazeBeliefDoor>;keys:Record<string,MazeBeliefKey>;threats:Record<string,MazeBeliefThreat>;frontiers:number[];revision:number;lastUpdatedTick:number}
export interface MazeAiState{mode:MazeIntentMode;confidence:number;explanation:string;decisions:number;fallbackCount:number;replans:number;nodeExpansions:number;recentCells:number[];plannedPath:number[];targetCell:number|null}
export interface MazeStats{newCells:number;backtracks:number;threatEncounters:number;keysCollected:number;doorsOpened:number;planRevisions:number;fallbackActions:number}
export interface MazeState{schemaVersion:1;runId:string;seed:string;tick:number;lifecycle:GameLifecycle;config:MazeConfig;world:MazeWorld;features:MazeFeatures;explorer:{cell:number;health:number;inventory:string[];steps:number;route:number[]};visibleCells:number[];discoveredCells:number[];meaningfulEventTick:number;belief:MazeBeliefState;ai:MazeAiState;stats:MazeStats;result?:MazeRunResult;intermissionRemaining:number}
export interface MazeEvent{seq:number;tick:number;type:string;data?:Record<string,unknown>}
