import type{SnakeConfig}from '../../../../packages/game-contracts/src/index';import type{NamedRng}from '../../../../packages/seeded-rng/src/index';
export interface BoardFeatures{profile:string;obstacleRatio:number;hazardCount:number;portalPairs:number;playableCells:number}
export interface GeneratedBoard{profile:string;obstacles:number[];hazards:number[];portalPairs:Record<number,number>;features:BoardFeatures;repaired:boolean}
function uniqSorted(xs:number[]){return[...new Set(xs)].sort((a,b)=>a-b)}
export function startCells(c:SnakeConfig){const y=Math.floor(c.height/2),x=Math.floor(c.width/2),cells:number[]=[];for(let i=0;i<c.initialLength;i++)cells.push(y*c.width+x-i);for(const[dx,dy]of[[1,0],[0,-1],[0,1]]){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<c.width&&ny<c.height)cells.push(ny*c.width+nx)}return new Set(cells)}
function topology(c:SnakeConfig){const o:number[]=[];const w=c.width,h=c.height,p=c.profile;const safe=startCells(c);const add=(x:number,y:number)=>{const i=y*w+x;if(x>0&&y>0&&x<w-1&&y<h-1&&!safe.has(i))o.push(i)};if(p==='corridors'){for(let x=3;x<w-2;x+=4){const gap=(x*3)%Math.max(2,h-2)+1;for(let y=1;y<h-1;y++)if(y!==gap&&y!==Math.min(h-2,gap+1))add(x,y)}}else if(p==='rings'){if(w>=9&&h>=9){const l=2,r=w-3,t=2,b=h-3;for(let x=l;x<=r;x++){if(x!==Math.floor(w/2))add(x,t);if(x!==Math.floor(w/2)-1)add(x,b)}for(let y=t+1;y<b;y++){if(y!==Math.floor(h/2))add(l,y);if(y!==Math.floor(h/2)+1)add(r,y)}}}else if(p==='chambers'){const cx=Math.floor(w/2),cy=Math.floor(h/2);for(let y=1;y<h-1;y++)if(y!==cy&&y!==Math.max(1,cy-2))add(cx,y);for(let x=1;x<w-1;x++)if(x!==cx&&x!==Math.min(w-2,cx+2))add(x,cy)}return uniqSorted(o)}
function portalMap(c:SnakeConfig,obstacles:number[]){if(c.profile!=='portals')return{};const blocked=new Set(obstacles),safe=startCells(c),w=c.width,h=c.height;const candidates=[w+1,2*w-2,(h-2)*w+1,(h-1)*w-2].filter(i=>i>=0&&i<w*h&&!blocked.has(i)&&!safe.has(i));const map:Record<number,number>={};if(candidates.length>=4){map[candidates[0]]=candidates[3];map[candidates[3]]=candidates[0];map[candidates[1]]=candidates[2];map[candidates[2]]=candidates[1]}return map}
function placeHazards(c:SnakeConfig,rng:NamedRng,obstacles:number[],portals:Record<number,number>){const blocked=new Set([...obstacles,...Object.keys(portals).map(Number),...startCells(c)]),free:number[]=[];for(let i=0;i<c.width*c.height;i++)if(!blocked.has(i))free.push(i);const out:number[]=[];for(let n=0;n<c.hazardCount&&free.length;n++){const k=rng.nextInt('hazard-schedule',free.length);out.push(free.splice(k,1)[0])}return uniqSorted(out)}
export function validateBoard(c:SnakeConfig,b:Pick<GeneratedBoard,'obstacles'|'hazards'|'portalPairs'>){const total=c.width*c.height,safe=startCells(c),obs=new Set(b.obstacles);if(obs.size!==b.obstacles.length||b.obstacles.some(i=>i<0||i>=total||safe.has(i)))return{valid:false,reason:'invalid-obstacle'};if(new Set(b.hazards).size!==b.hazards.length||b.hazards.some(i=>i<0||i>=total||obs.has(i)||safe.has(i)))return{valid:false,reason:'invalid-hazard'};for(const[k,v]of Object.entries(b.portalPairs)){const a=Number(k);if(a<0||a>=total||v<0||v>=total||obs.has(a)||obs.has(v)||b.portalPairs[v]!==a)return{valid:false,reason:'invalid-portal'}}const start=[...safe][0];const q=[start],seen=new Set([start]);while(q.length){const i=q.shift()!,x=i%c.width,y=Math.floor(i/c.width);for(const[nx,ny]of[[x,y-1],[x+1,y],[x,y+1],[x-1,y]]){if(nx<0||ny<0||nx>=c.width||ny>=c.height)continue;const n=ny*c.width+nx;if(!obs.has(n)&&!seen.has(n)){seen.add(n);q.push(n)}}}return seen.size===total-obs.size?{valid:true}:{valid:false,reason:'disconnected'}}
export function generateBoard(c:SnakeConfig,rng:NamedRng):GeneratedBoard{let obstacles=topology(c),portalPairs=portalMap(c,obstacles),hazards=placeHazards(c,rng,obstacles,portalPairs),repaired=false;let probe={obstacles,hazards,portalPairs};if(!validateBoard(c,probe).valid){obstacles=[];portalPairs=c.profile==='portals'?portalMap({...c,profile:'portals'},[]):{};hazards=placeHazards(c,rng,obstacles,portalPairs);probe={obstacles,hazards,portalPairs};repaired=true}const total=c.width*c.height;return{profile:c.profile,obstacles,hazards,portalPairs,features:{profile:c.profile,obstacleRatio:obstacles.length/total,hazardCount:hazards.length,portalPairs:Object.keys(portalPairs).length/2,playableCells:total-obstacles.length},repaired}}
