'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{ZombieRuntime}=require('../../dist/games/ai-zombie-survival/src/runtime/run');
const{checksum}=require('../../dist/packages/replay/src/index');
function config(){return{width:24,height:16,dayTicks:12,nightTicks:16,resultTicks:2,maxDays:2,maxZombies:32,survivorDecisionInterval:1,zombieSpawnInterval:2,waveBaseSize:6,waveGrowthPerDay:2}}
function presentation(){return{
  ...require('../../dist/games/ai-zombie-survival/src/presentation/snapshot'),
  ...require('../../dist/games/ai-zombie-survival/src/presentation/layout'),
  ...require('../../dist/games/ai-zombie-survival/src/presentation/audio'),
  ...require('../../dist/games/ai-zombie-survival/src/presentation/controller'),
}}
test('render snapshot is immutable, deterministic, complete and privacy safe',()=>{const{buildZombieRenderSnapshot}=presentation(),runtime=ZombieRuntime.create(config(),'public-boundary'),before=checksum(runtime.state),snapshot=buildZombieRenderSnapshot(runtime.state),after=checksum(runtime.state);assert.equal(before,after);assert.equal(Object.isFrozen(snapshot),true);assert.equal(Object.isFrozen(snapshot.survivors),true);assert.equal('seed'in snapshot,false);assert.equal('runId'in snapshot,false);assert.equal('config'in snapshot,false);assert.equal('world'in snapshot,false);assert.equal('events'in snapshot,false);assert.equal(JSON.stringify(snapshot).includes(runtime.seed),false);assert.equal(snapshot.day,1);assert.equal(snapshot.phase,'preparation');assert.equal(snapshot.survivors.length,4);assert.equal(snapshot.defenses.length,4);assert.equal(snapshot.resources.materials,runtime.state.resources.materials);assert.deepEqual(snapshot,buildZombieRenderSnapshot(runtime.state));assert.throws(()=>snapshot.survivors.push({}),TypeError)});
test('layout preserves arena HUD captions and controls on desktop, phone landscape and clean feed',()=>{const{computeZombieLayout}=presentation(),desktop=computeZombieLayout(1920,1080,{cleanFeed:false}),phone=computeZombieLayout(844,390,{cleanFeed:false}),clean=computeZombieLayout(1280,720,{cleanFeed:true});assert.ok(desktop.arena.width>=1000);assert.ok(desktop.hud.width>=300);assert.ok(desktop.caption.height>=52);assert.ok(phone.arena.width>=500);assert.ok(phone.minimumCellPixels>=8);assert.ok(phone.caption.y+phone.caption.height<=390);assert.equal(clean.hud.width,0);assert.ok(clean.arena.width>phone.arena.width)});
test('semantic audio is priority bounded and captions survive mute',()=>{const{ZombieAudioDirector}=presentation(),director=new ZombieAudioDirector({maxVoices:3,muted:true}),events=[{seq:1,tick:1,type:'resource-delivered',data:{kind:'materials'}},{seq:2,tick:2,type:'phase-changed',data:{phase:'horde'}},{seq:3,tick:3,type:'defense-breached',data:{defenseId:'north'}},{seq:4,tick:4,type:'survivor-died',data:{survivorId:'survivor-1'}},{seq:5,tick:5,type:'run-result',data:{outcome:'overrun'}}],frame=director.consume(events);assert.equal(frame.voices.length,0);assert.ok(frame.captions.length>=4);assert.ok(frame.captions.some(text=>/breach/i.test(text)));assert.ok(frame.captions.some(text=>/run|overrun/i.test(text)));assert.ok(frame.captions.length<=8)});
test('presentation controller rejects stale divergence, bounds replay and recovers from the latest public snapshot',()=>{const{buildZombieRenderSnapshot,ZombiePresentationController}=presentation(),runtime=ZombieRuntime.create(config(),'controller'),controller=new ZombiePresentationController({replayCapacity:12,maxEntities:128,muted:false});let cursor=0;for(let i=0;i<30;i++){runtime.step();const events=runtime.events.slice(cursor);cursor=runtime.events.length;const accepted=controller.accept(buildZombieRenderSnapshot(runtime.state),events);assert.equal(accepted.accepted,true,accepted.reason)}assert.ok(controller.frame(1280,720).replayAvailable<=12);const current=buildZombieRenderSnapshot(runtime.state);assert.equal(controller.accept(current,[]).accepted,true);const stale=structuredClone(current);stale.revision=Math.max(0,current.revision-1);assert.equal(controller.accept(stale,[]).accepted,false);const divergent=structuredClone(current);divergent.publicChecksum='ffffffff';assert.equal(controller.accept(divergent,[]).accepted,false);controller.failOutput('synthetic renderer fault');assert.equal(controller.frame().scene,'recovery');assert.equal(controller.rebuildFromLatest().recovered,true);assert.notEqual(controller.frame().scene,'recovery')});
test('new run at tick zero clears run-scoped replay without exposing stale entities',()=>{const{buildZombieRenderSnapshot,ZombiePresentationController}=presentation(),runtime=ZombieRuntime.create({...config(),maxDays:1},'new-run'),controller=new ZombiePresentationController({replayCapacity:50});controller.accept(buildZombieRenderSnapshot(runtime.state),[]);while(runtime.state.restartIndex===0){runtime.step();controller.accept(buildZombieRenderSnapshot(runtime.state),[])}const frame=controller.frame();assert.equal(frame.snapshot.tick,0);assert.equal(frame.snapshot.runToken,buildZombieRenderSnapshot(runtime.state).runToken);assert.equal(frame.replayAvailable,1)});
test('presentation sampling cadence cannot change authoritative outcomes',()=>{const{buildZombieRenderSnapshot,ZombiePresentationController}=presentation(),frequent=ZombieRuntime.create(config(),'frame-schedule'),sparse=ZombieRuntime.create(config(),'frame-schedule'),controller=new ZombiePresentationController();for(let i=0;i<100;i++){frequent.step();sparse.step();controller.accept(buildZombieRenderSnapshot(frequent.state),[]);if(i%7===0)buildZombieRenderSnapshot(sparse.state)}assert.equal(frequent.stateChecksum(),sparse.stateChecksum())});
test('output health distinguishes healthy, degraded and unsafe recovery states',()=>{const{classifyZombieOutputHealth}=presentation();assert.equal(classifyZombieOutputHealth({frameAgeMs:100,blackRatio:.1,frozenFrames:0,audioAgeMs:100,intendedSilence:false,scene:'preparation'}).status,'healthy');assert.equal(classifyZombieOutputHealth({frameAgeMs:2200,blackRatio:.1,frozenFrames:5,audioAgeMs:100,intendedSilence:false,scene:'horde'}).status,'degraded');const unsafe=classifyZombieOutputHealth({frameAgeMs:8000,blackRatio:.99,frozenFrames:60,audioAgeMs:9000,intendedSilence:false,scene:'horde'});assert.equal(unsafe.status,'unsafe');assert.equal(unsafe.action,'safe-scene');assert.equal(classifyZombieOutputHealth({frameAgeMs:100,blackRatio:.1,frozenFrames:0,audioAgeMs:9000,intendedSilence:true,scene:'intermission'}).status,'healthy')});
