import type{Direction,DungeonAction,DungeonConfig}from '../../../../packages/game-contracts/src/index';
import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import{checksum}from '../../../../packages/replay/src/index';
import{parseDungeonConfig}from '../config/schema';
import{findPath}from '../generation/dungeon';
import{createInitialDungeonState}from '../index';
import{stepDungeonRules}from '../rules/step';
import type{DungeonEvent,DungeonState}from '../state/types';
function directionBetween(from:number,to:number,width:number):Direction{if(to===from-width)return'up';if(to===from+1)return'right';if(to===from+width)return'down';return'left'}
export function fallbackDungeonAction(state:DungeonState):DungeonAction{if(state.lifecycle!=='running')return{kind:'wait'};if(state.hero.cell===state.floor.sigil&&!state.floorProgress.sigilCollected)return{kind:'interact'};if(state.hero.cell===state.floor.gate&&state.floorProgress.gateUnlocked)return{kind:'descend'};const target=state.floorProgress.sigilCollected?state.floor.gate:state.floor.sigil;const path=findPath(state.floor,state.hero.cell,target);return path.length>1?{kind:'move',direction:directionBetween(path[0],path[1],state.floor.width)}:{kind:'wait'}}
export class DungeonRuntime{readonly config:DungeonConfig;readonly seed:string;readonly runId:string;state:DungeonState;rng:NamedRng;private nextEventSequence:number;constructor(configInput:DungeonConfig,seed:string,runId:string){this.config=parseDungeonConfig(configInput);this.seed=seed;this.runId=runId;this.rng=NamedRng.fromSeed(seed);this.state=createInitialDungeonState(this.config,seed,runId,this.rng);this.nextEventSequence=1}static restore(config:DungeonConfig,seed:string,state:DungeonState,rng:NamedRng,nextEventSequence:number){const runtime=Object.create(DungeonRuntime.prototype)as DungeonRuntime;Object.defineProperty(runtime,'config',{value:parseDungeonConfig(config),enumerable:true});Object.defineProperty(runtime,'seed',{value:seed,enumerable:true});Object.defineProperty(runtime,'runId',{value:state.runId,enumerable:true});runtime.state=state;runtime.rng=rng;runtime.nextEventSequence=nextEventSequence;return runtime}step(action?:DungeonAction):DungeonEvent[]{const pending=stepDungeonRules(this.state,action??fallbackDungeonAction(this.state),this.rng);const events=pending.map(event=>({...event,sequence:this.nextEventSequence++,tick:this.state.tick}));this.state.eventHistory.push(...events);if(this.state.eventHistory.length>this.config.maxEvents)this.state.eventHistory.splice(0,this.state.eventHistory.length-this.config.maxEvents);return events}getNextEventSequence(){return this.nextEventSequence}checksum(){return checksum({config:this.config,seed:this.seed,state:this.state,rng:this.rng.snapshot(),nextEventSequence:this.nextEventSequence})}}
