import{NamedRng}from '../../../../packages/seeded-rng/src/index';
import type{DungeonConfig}from '../../../../packages/game-contracts/src/index';
import type{DungeonFloor,DungeonRoom,DungeonTile}from '../state/types';
const WALL:DungeonTile=0,FLOOR:DungeonTile=1;const index=(x:number,y:number,width:number)=>y*width+x;const xy=(cell:number,width:number)=>({x:cell%width,y:Math.floor(cell/width)});const odd=(n:number)=>n%2===0?n-1:n;
function carveRect(tiles:DungeonTile[],width:number,room:DungeonRoom){for(let y=room.y;y<room.y+room.height;y++)for(let x=room.x;x<room.x+room.width;x++)tiles[index(x,y,width)]=FLOOR}
function carveCorridor(tiles:DungeonTile[],width:number,a:number,b:number,horizontalFirst:boolean){let{x,y}=xy(a,width);const target=xy(b,width);const carveHorizontal=()=>{while(x!==target.x){tiles[index(x,y,width)]=FLOOR;x+=x<target.x?1:-1}tiles[index(x,y,width)]=FLOOR};const carveVertical=()=>{while(y!==target.y){tiles[index(x,y,width)]=FLOOR;y+=y<target.y?1:-1}tiles[index(x,y,width)]=FLOOR};if(horizontalFirst){carveHorizontal();carveVertical()}else{carveVertical();carveHorizontal()}}
function overlaps(a:DungeonRoom,b:DungeonRoom){return!(a.x+a.width+1<b.x||b.x+b.width+1<a.x||a.y+a.height+1<b.y||b.y+b.height+1<a.y)}
function neighbours(cell:number,width:number,height:number){const{x,y}=xy(cell,width),out:number[]=[];if(y>0)out.push(cell-width);if(x+1<width)out.push(cell+1);if(y+1<height)out.push(cell+width);if(x>0)out.push(cell-1);return out}
export function findPath(floor:DungeonFloor,start:number,goal:number):number[]{if(start===goal)return[start];const previous=new Int32Array(floor.tiles.length);previous.fill(-2);previous[start]=-1;const queue=new Int32Array(floor.tiles.length);let head=0,tail=0;queue[tail++]=start;while(head<tail){const current=queue[head++];for(const next of neighbours(current,floor.width,floor.height)){if(floor.tiles[next]!==FLOOR||previous[next]!==-2)continue;previous[next]=current;if(next===goal){const path=[goal];let cursor=current;while(cursor!==-1){path.push(cursor);cursor=previous[cursor]}return path.reverse()}queue[tail++]=next}}return[]}
function distances(tiles:DungeonTile[],width:number,height:number,start:number){const result=new Int32Array(tiles.length);result.fill(-1);result[start]=0;const queue=new Int32Array(tiles.length);let head=0,tail=0;queue[tail++]=start;while(head<tail){const current=queue[head++];for(const next of neighbours(current,width,height))if(tiles[next]===FLOOR&&result[next]===-1){result[next]=result[current]+1;queue[tail++]=next}}return result}
function farthestWalkable(tiles:DungeonTile[],width:number,height:number,start:number,excluded:Set<number>=new Set()){const d=distances(tiles,width,height,start);let best=start,bestDistance=-1;for(let cell=0;cell<d.length;cell++)if(d[cell]>bestDistance&&!excluded.has(cell)){best=cell;bestDistance=d[cell]}return best}
function safeFallback(config:DungeonConfig,floorNumber:number):DungeonFloor{const tiles=Array<DungeonTile>(config.width*config.height).fill(WALL),rooms:DungeonRoom[]=[];const centers=[[5,5],[Math.floor(config.width/2),5],[config.width-6,5],[config.width-6,config.height-6],[Math.floor(config.width/2),config.height-6],[5,config.height-6]];centers.forEach(([cx,cy],id)=>{const room:DungeonRoom={id,x:cx-2,y:cy-2,width:5,height:5,center:index(cx,cy,config.width)};rooms.push(room);carveRect(tiles,config.width,room);if(id>0)carveCorridor(tiles,config.width,rooms[id-1].center,room.center,id%2===0)});const entrance=rooms[0].center,gate=rooms.at(-1)!.center,sigil=rooms[Math.floor(rooms.length/2)].center;const provisional:DungeonFloor={version:1,width:config.width,height:config.height,floorNumber,tiles,rooms,entrance,sigil,gate,shrine:rooms[1].center,chest:rooms[2].center,bossCell:gate,repairCount:1,fallbackUsed:true,features:{walkable:tiles.filter(v=>v===FLOOR).length,mandatoryRouteLength:0,branchRooms:rooms.length-2,loopCount:0}};provisional.features.mandatoryRouteLength=findPath(provisional,entrance,sigil).length+findPath(provisional,sigil,gate).length-1;return provisional}
export function validateDungeonFloor(floor:DungeonFloor):{ok:boolean;errors:string[]}{const errors:string[]=[];const cells=[floor.entrance,floor.sigil,floor.gate,floor.shrine,floor.chest,floor.bossCell];if(floor.tiles.length!==floor.width*floor.height)errors.push('tile-count');if(new Set(cells).size<4)errors.push('objective-overlap');for(const cell of cells)if(cell<0||cell>=floor.tiles.length||floor.tiles[cell]!==FLOOR)errors.push(`objective-not-walkable:${cell}`);if(findPath(floor,floor.entrance,floor.sigil).length===0)errors.push('sigil-unreachable');if(findPath(floor,floor.sigil,floor.gate).length===0)errors.push('gate-unreachable');if(floor.rooms.length<3)errors.push('insufficient-rooms');return{ok:errors.length===0,errors}}
export function generateDungeonFloor(config:DungeonConfig,floorNumber:number,rng:NamedRng):DungeonFloor{const tiles=Array<DungeonTile>(config.width*config.height).fill(WALL),rooms:DungeonRoom[]=[];for(let attempt=0;attempt<config.roomAttempts;attempt++){const span=Math.max(1,Math.floor((config.roomMaxSize-config.roomMinSize)/2)+1);const width=Math.min(config.roomMaxSize,config.roomMinSize+2*rng.nextInt('topology-v1:room-width',span));const height=Math.min(config.roomMaxSize,config.roomMinSize+2*rng.nextInt('topology-v1:room-height',span));const maxX=Math.max(1,Math.floor((config.width-width-2)/2)),maxY=Math.max(1,Math.floor((config.height-height-2)/2));const x=1+2*rng.nextInt('topology-v1:room-x',maxX),y=1+2*rng.nextInt('topology-v1:room-y',maxY);const room:DungeonRoom={id:rooms.length,x,y,width:odd(width),height:odd(height),center:index(x+Math.floor(width/2),y+Math.floor(height/2),config.width)};if(rooms.some(existing=>overlaps(room,existing)))continue;rooms.push(room);carveRect(tiles,config.width,room);if(rooms.length>1)carveCorridor(tiles,config.width,rooms[rooms.length-2].center,room.center,rng.nextInt('topology-v1:corridor-orientation',2)===0)}if(rooms.length<3)return safeFallback(config,floorNumber);let loopCount=0;for(let i=0;i<rooms.length-2;i++)if(rng.nextInt('topology-v1:loops',1000)<config.loopChancePermille){carveCorridor(tiles,config.width,rooms[i].center,rooms[i+2].center,rng.nextInt('topology-v1:loop-orientation',2)===0);loopCount++}const entrance=rooms[0].center;const gate=farthestWalkable(tiles,config.width,config.height,entrance,new Set([entrance]));const sigil=farthestWalkable(tiles,config.width,config.height,gate,new Set([entrance,gate]));const walkable=tiles.map((value,cell)=>value===FLOOR?cell:-1).filter(cell=>cell>=0&&cell!==entrance&&cell!==gate&&cell!==sigil);const pick=(stream:string,fallback:number)=>walkable.length?walkable[rng.nextInt(stream,walkable.length)]:fallback;let shrine=pick('objectives-v1:shrine',rooms[1].center);let chest=pick('objectives-v1:chest',rooms[2].center);if(chest===shrine)chest=walkable.find(cell=>cell!==shrine)??rooms[2].center;const floor:DungeonFloor={version:1,width:config.width,height:config.height,floorNumber,tiles,rooms,entrance,sigil,gate,shrine,chest,bossCell:gate,repairCount:0,fallbackUsed:false,features:{walkable:walkable.length+3,mandatoryRouteLength:0,branchRooms:Math.max(0,rooms.length-2),loopCount}};floor.features.mandatoryRouteLength=findPath(floor,entrance,sigil).length+findPath(floor,sigil,gate).length-1;const validation=validateDungeonFloor(floor);return validation.ok?floor:safeFallback(config,floorNumber)}
