'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const battle=require('../../dist/games/ai-battle-royale/src/index.js');

function config(overrides={}){return battle.createBattleConfig({width:24,height:18,combatantCount:12,lootCount:24,maxTicks:360,intermissionTicks:8,startingHealth:500,startingShield:250,zoneFirstShrinkTick:140,zoneShrinkInterval:70,supplyDropEvery:80,noProgressTicks:180,voteWindowEvery:80,voteWindowTicks:20,maxProcessedInfluence:64,maxAuditEntries:64,maxScheduledEffects:8,...overrides})}
function runtime(seed='phase5-runtime'){return new battle.BattleRoyaleRuntime(config(),seed,`run-${seed}`)}
function healthySample(overrides={}){return{nowMs:10_000,tick:120,lastTickProgressMs:9_900,lastRenderChangeMs:9_920,lastAudioMs:9_850,audioExpected:true,lastPersistenceMs:9_800,providerStatus:'online',queueUtilization:0.2,memorySlopeMbPerHour:1,resourcePressure:0.2,...overrides}}

test('versioned battle snapshot envelopes restore to the exact deterministic continuation',()=>{const live=runtime('restore-equality');for(let index=0;index<72;index+=1)live.step();const envelope=battle.createBattleSnapshotEnvelope(live);assert.equal(envelope.schemaVersion,1);assert.equal(envelope.gameId,'ai-battle-royale');assert.equal(envelope.deterministicVersion,live.state.deterministicVersion);assert.equal(envelope.stateChecksum,live.checksum());assert.match(envelope.envelopeChecksum,/^[a-f0-9]{8}$/);const restored=battle.restoreBattleSnapshotEnvelope(envelope);assert.equal(restored.status,'restored');assert.equal(restored.runtime.checksum(),live.checksum());for(let index=0;index<48;index+=1){live.step();restored.runtime.step()}assert.equal(restored.runtime.checksum(),live.checksum());assert.deepEqual(restored.runtime.state.rng,live.state.rng)});

test('corrupt or incompatible snapshots quarantine instead of silently continuing',()=>{const game=runtime('quarantine');for(let index=0;index<30;index+=1)game.step();const envelope=battle.createBattleSnapshotEnvelope(game);const corrupted=structuredClone(envelope);corrupted.runtimeSnapshot.state.combatants[0].health-=7;const corruptResult=battle.restoreBattleSnapshotEnvelope(corrupted);assert.deepEqual({status:corruptResult.status,reason:corruptResult.reason},{status:'quarantined',reason:'envelope-checksum'});const incompatible=structuredClone(envelope);incompatible.deterministicVersion='battle-future-v99';const incompatibleResult=battle.restoreBattleSnapshotEnvelope(incompatible);assert.deepEqual({status:incompatibleResult.status,reason:incompatibleResult.reason},{status:'quarantined',reason:'snapshot-version'});assert.equal(game.state.lifecycle,'running')});

test('replay journal rejects duplicate inputs and remains bounded with a candidate-bound manifest',()=>{const game=runtime('journal'),envelope=battle.createBattleSnapshotEnvelope(game),journal=new battle.BattleReplayJournal(4);assert.equal(journal.record({id:'youtube:evt-1',tick:10,kind:'audience-input',digest:'checksum:11111111'}).status,'recorded');assert.deepEqual(journal.record({id:'youtube:evt-1',tick:10,kind:'audience-input',digest:'checksum:11111111'}),{status:'duplicate',reason:'duplicate-id'});for(let index=2;index<=8;index+=1)assert.equal(journal.record({id:`youtube:evt-${index}`,tick:10+index,kind:'audience-input',digest:`checksum:${String(index).padStart(8,'0')}`}).status,'recorded');const manifest=journal.manifest(envelope);assert.equal(manifest.gameId,'ai-battle-royale');assert.equal(manifest.stateChecksum,envelope.stateChecksum);assert.equal(manifest.entries.length,4);assert.equal(journal.snapshot().entries.length,4);assert.match(manifest.manifestChecksum,/^[a-f0-9]{8}$/)});

test('operations supervisor probes tick, render, audio, persistence and provider health independently',()=>{const supervisor=new battle.BattleOperationsSupervisor();const healthy=supervisor.observe(healthySample());assert.equal(healthy.status,'healthy');assert.equal(healthy.publicScene,'battle');const provider=supervisor.observe(healthySample({providerStatus:'disabled'}));assert.equal(provider.status,'degraded');assert.ok(provider.reasons.includes('provider-unavailable'));assert.ok(provider.actions.some(action=>action.type==='disable-interactions'));const audio=supervisor.observe(healthySample({nowMs:20_000,lastAudioMs:10_000}));assert.equal(audio.status,'degraded');assert.ok(audio.reasons.includes('audio-stale'));assert.ok(audio.actions.some(action=>action.type==='mute-audio'));const render=supervisor.observe(healthySample({nowMs:20_000,lastRenderChangeMs:10_000}));assert.equal(render.status,'unsafe');assert.ok(render.reasons.includes('render-stale'));assert.ok(render.actions.some(action=>action.type==='safe-scene'));const persistence=supervisor.observe(healthySample({nowMs:20_000,lastPersistenceMs:10_000}));assert.equal(persistence.status,'unsafe');assert.ok(persistence.reasons.includes('persistence-stale'));assert.ok(persistence.actions.some(action=>action.type==='verified-recovery'));const tick=supervisor.observe(healthySample({nowMs:20_000,lastTickProgressMs:10_000}));assert.equal(tick.status,'unsafe');assert.ok(tick.reasons.includes('simulation-no-progress'));assert.equal(tick.publicScene,'recovery')});

test('recovery workflow resumes only after verified restore and halts after a finite breaker budget',()=>{const supervisor=new battle.BattleOperationsSupervisor(),unsafe=supervisor.observe(healthySample({nowMs:20_000,lastTickProgressMs:10_000}));const success=new battle.BattleOutputRecoveryWorkflow(2);assert.equal(success.begin(unsafe).state,'safe-scene');assert.equal(success.advance({componentRestarted:true}).state,'restoring');assert.equal(success.advance({snapshotVerified:true}).state,'verifying');assert.equal(success.advance({snapshotVerified:true,outputHealthy:true}).state,'resumed');const halted=new battle.BattleOutputRecoveryWorkflow(2);halted.begin(unsafe);halted.advance({componentRestarted:true});assert.equal(halted.advance({snapshotVerified:false}).state,'restoring');assert.equal(halted.advance({snapshotVerified:false}).state,'halted');assert.equal(halted.advance({snapshotVerified:true,outputHealthy:true}).state,'halted');assert.equal(halted.snapshot().attempts,2)});

test('Phase 5 chaos campaign proves verified recovery, quarantine, dedupe and bounded operations state',()=>{const report=battle.runBattleRoyalePhase5Chaos('battle-phase5-test');assert.equal(report.status,'pass');assert.equal(report.restoreVerified,true);assert.equal(report.corruptionQuarantined,true);assert.equal(report.incompatibleQuarantined,true);assert.equal(report.duplicateReplayRejected,true);assert.equal(report.breakerBounded,true);assert.equal(report.interactionsDegradedSafely,true);assert.equal(report.integrityFailures,0);assert.ok(report.journalEntries<=32);assert.match(report.checksum,/^[a-f0-9]{8}$/)});

test('Battle Royale operations runbook, rollback matrix and handoff are present and actionable',()=>{for(const relative of['../../docs/operations/ai-battle-royale-runbook.md','../../docs/operations/ai-battle-royale-rollback-matrix.md','../../docs/operations/ai-battle-royale-handoff.md']){const file=path.resolve(__dirname,relative);assert.equal(fs.existsSync(file),true,file);const content=fs.readFileSync(file,'utf8');assert.ok(content.length>500,file);assert.match(content,/safe scene|rollback|owner|verified restore/i,file)}});
