'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{DungeonRuntime}=require('../../dist/games/ai-dungeon-endless-adventure/src/runtime/run.js');
const{encodeDungeonSnapshot}=require('../../dist/games/ai-dungeon-endless-adventure/src/persistence/snapshot.js');
const{DungeonAuthorityJournal,DungeonOperationsError,recoverDungeonAuthority,DungeonOperationsMonitor,DungeonSupervisor,DungeonOperatorControl,runDungeonPhase5Chaos}=require('../../dist/games/ai-dungeon-endless-adventure/src/operations/index.js');
const base={schemaVersion:1,width:31,height:21,roomAttempts:24,roomMinSize:3,roomMaxSize:7,loopChancePermille:180,chapterLength:5,maxTicksPerFloor:1800,intermissionTicks:2,maxEnemies:18,maxRelics:6,maxEvents:96,noProgressTicks:600};

test('authority lease fencing rejects stale writers after takeover',()=>{const journal=new DungeonAuthorityJournal({maxEntries:32,maxSnapshots:3});const first=journal.acquireLease('worker-a');journal.reserve(first.epoch,'cmd-1','aaa');const second=journal.acquireLease('worker-b');assert.ok(second.epoch>first.epoch);assert.throws(()=>journal.reserve(first.epoch,'cmd-stale','bbb'),error=>error instanceof DungeonOperationsError&&error.code==='FENCED');assert.equal(journal.reserve(second.epoch,'cmd-2','ccc').status,'reserved')});

test('reservation commit is exactly once and live journal resources remain bounded',()=>{const journal=new DungeonAuthorityJournal({maxEntries:8,maxSnapshots:2});const lease=journal.acquireLease('worker');const reservation=journal.reserve(lease.epoch,'cmd-1','input-a');assert.equal(journal.reserve(lease.epoch,'cmd-1','input-a').sequence,reservation.sequence);assert.equal(journal.commit(lease.epoch,reservation.sequence,'result-a').status,'committed');assert.equal(journal.commit(lease.epoch,reservation.sequence,'result-a').status,'committed');for(let i=2;i<30;i++){const r=journal.reserve(lease.epoch,`cmd-${i}`,`input-${i}`);journal.commit(lease.epoch,r.sequence,`result-${i}`)}assert.ok(journal.entries().length<=8);assert.ok(journal.dedupeSize()<=32)});

test('verified recovery matches uninterrupted authority and corrupted newest snapshot quarantines',()=>{const runtime=new DungeonRuntime(base,'recover-seed','recover-run');for(let i=0;i<80;i++)runtime.step();const journal=new DungeonAuthorityJournal({maxEntries:64,maxSnapshots:3});const lease=journal.acquireLease('worker');journal.appendSnapshot(lease.epoch,encodeDungeonSnapshot(runtime));const expected=runtime.checksum();const recovered=recoverDungeonAuthority(journal);assert.equal(recovered.status,'recovered');assert.equal(recovered.runtime.checksum(),expected);const corrupt=JSON.parse(JSON.stringify(encodeDungeonSnapshot(runtime)));corrupt.state.hero.hp+=1;journal.appendSnapshot(lease.epoch,corrupt);const fallback=recoverDungeonAuthority(journal);assert.equal(fallback.status,'recovered');assert.equal(fallback.usedOlderSnapshot,true);const onlyBad=new DungeonAuthorityJournal({maxEntries:8,maxSnapshots:2});const badLease=onlyBad.acquireLease('worker');onlyBad.appendSnapshot(badLease.epoch,corrupt);assert.equal(recoverDungeonAuthority(onlyBad).status,'quarantined')});

test('operations monitor distinguishes output degradation and supervisor breaks crash loops',()=>{const monitor=new DungeonOperationsMonitor();const healthy=monitor.observe({nowMs:10000,lastTickMs:9950,lastFrameMs:9950,lastAudioMs:9900,intendedSilence:false,lastSnapshotMs:9800,queueUtilization:.2,memorySlopeMbPerHour:1,luma:.4});assert.equal(healthy.status,'healthy');const unsafe=monitor.observe({nowMs:20000,lastTickMs:1000,lastFrameMs:1000,lastAudioMs:1000,intendedSilence:false,lastSnapshotMs:1000,queueUtilization:.95,memorySlopeMbPerHour:60,luma:0});assert.equal(unsafe.status,'unsafe');assert.ok(unsafe.actions.includes('safe-scene'));assert.ok(unsafe.actions.includes('verified-recovery'));const supervisor=new DungeonSupervisor({maxCrashes:3,windowMs:10000,breakerMs:30000});supervisor.recordCrash(1000);supervisor.recordCrash(2000);supervisor.recordCrash(3000);assert.equal(supervisor.canRestart(3500),false);assert.equal(supervisor.canRestart(40000),true)});

test('typed operator controls enforce role and never arbitrarily edit authority',()=>{const runtime=new DungeonRuntime(base,'ops-control','ops-control-run');const control=new DungeonOperatorControl();assert.equal(control.execute('viewer',{type:'disable-audience'},runtime).accepted,false);assert.equal(control.execute('operator',{type:'disable-audience'},runtime).accepted,true);assert.equal(runtime.state.influence.enabled,false);assert.equal(control.execute('operator',{type:'snapshot-now'},runtime).accepted,true);assert.equal(control.execute('operator',{type:'set-health',value:999},runtime).accepted,false)});

test('compressed chaos is deterministic bounded and verifies recovery/fencing',()=>{const a=runDungeonPhase5Chaos('dungeon-chaos'),b=runDungeonPhase5Chaos('dungeon-chaos');assert.deepEqual(a,b);assert.equal(a.status,'pass',JSON.stringify(a));assert.equal(a.oldWriterFenced,true);assert.equal(a.recoveryVerified,true);assert.equal(a.integrityFailures,0);assert.equal(a.duplicateApplications,0);assert.ok(a.liveEntries<=64);assert.ok(a.snapshots<=4);assert.match(a.checksum,/^[0-9a-f]{8}$/)});
