'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{InMemoryDurableStore}=require('../../dist/packages/durable-store/src/index.js');
const{RunLeaseStore}=require('../../dist/packages/operations-core/src/lease.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
const{MazeChannelService}=require('../../dist/services/maze-channel/src/index.js');
const{buildMazeInfluenceCandidates}=require('../../dist/games/ai-maze-escape/src/influence/candidates.js');
const{createMazeInfluenceCommand}=require('../../dist/games/ai-maze-escape/src/influence/apply.js');
function options(store,leases,workerId='worker-a',extra={}){return{channelId:'maze-channel',workerId,seed:'maze-channel-seed',config:{width:13,height:11,profile:'loops',visibilityRadius:2,keyCount:1,trapCount:2,maxTicks:20000,noProgressTicks:5000},store,leases,leaseTtlMs:1000,snapshotEveryCommands:5,compatibility:{gameVersion:'maze-0.5.0',deterministicVersion:'maze-rules-1',configHash:'config0001',contentHash:'content001'},...extra}}
test('service persists commands, snapshots and reconstructs exact authority',()=>{const store=new InMemoryDurableStore({snapshotCapacity:4}),leases=new RunLeaseStore(),service=new MazeChannelService(options(store,leases));service.start(0);for(let i=1;i<=15;i++)service.tick(`tick-${i}`,i*10);const expected=service.status(),events=store.events('maze-channel');assert.ok(events.some(event=>event.type==='runtime-command'));assert.ok(store.snapshots('maze-channel').length>=3);leases.fence('maze-channel','replacement');const replacement=new MazeChannelService(options(store,leases,'worker-b'));const status=replacement.start(5000);assert.equal(status.commandSeq,15);assert.equal(status.lastChecksum,expected.lastChecksum);assert.equal(status.tick,expected.tick);const before=checksum(replacement.runtime.state),duplicate=replacement.tick('tick-15',5010);assert.equal(duplicate.status,'duplicate');assert.equal(checksum(replacement.runtime.state),before)});
test('post-snapshot commands replay exactly and corrupt newest snapshot falls back',()=>{const store=new InMemoryDurableStore({snapshotCapacity:5}),leases=new RunLeaseStore(),service=new MazeChannelService(options(store,leases,'worker-a',{snapshotEveryCommands:100}));service.start(0);for(let i=1;i<=4;i++)service.tick(`pre-${i}`,i*10);const older=service.captureSnapshot(100);for(let i=5;i<=10;i++)service.tick(`post-${i}`,i*10+100);const expected=service.status().lastChecksum,newer=service.captureSnapshot(400),corrupt=structuredClone(newer);corrupt.envelope.state.tick++;store.putSnapshot(corrupt);assert.notEqual(older.id,newer.id);leases.fence('maze-channel','replacement');const replacement=new MazeChannelService(options(store,leases,'worker-b',{snapshotEveryCommands:100}));const status=replacement.start(5000);assert.equal(status.lastChecksum,expected);assert.equal(status.commandSeq,10);assert.ok(store.audits().some(entry=>entry.action==='startup-recovery'))});
test('lease conflict, stale writer fencing and replay divergence fail closed',()=>{const store=new InMemoryDurableStore(),leases=new RunLeaseStore(),first=new MazeChannelService(options(store,leases,'worker-a'));first.start(0);first.tick('one',10);first.captureSnapshot(20);const conflict=new MazeChannelService(options(store,leases,'worker-b'));assert.throws(()=>conflict.start(30),error=>error.code==='LEASE_CONFLICT');leases.fence('maze-channel','manual');const replacement=new MazeChannelService(options(store,leases,'worker-b'));replacement.start(2000);assert.throws(()=>first.tick('old-writer',2010),error=>error.code==='LEASE_FENCED');const result=replacement.recover({nowMs:3000,newOwnerId:'worker-c',expectedChecksum:'ffffffff'});assert.equal(result.status,'quarantined');assert.equal(result.reason,'replay-divergence');assert.ok(store.audits().some(entry=>entry.action==='quarantine'))});
test('influence reservation survives duplicate delivery and applies exactly once',()=>{const store=new InMemoryDurableStore(),leases=new RunLeaseStore(),service=new MazeChannelService(options(store,leases));service.start(0);for(let i=1;i<=6;i++)service.tick(`warm-${i}`,i*10);const candidate=buildMazeInfluenceCandidates(service.runtime.state).find(item=>item.effectId==='fog-pulse');assert.ok(candidate);const command=createMazeInfluenceCommand(service.runtime.state,{id:'effect-1',candidate,scheduledTick:service.runtime.state.tick+1,expiresAtTick:service.runtime.state.tick+20,source:'support'});assert.equal(service.enqueueInfluence('reserve-effect',command,100).status,'applied');assert.equal(service.enqueueInfluence('reserve-effect',command,101).status,'duplicate');service.tick('advance-effect',110);service.tick('apply-effect',120);assert.equal(service.runtime.state.influence.applied['effect-1'].applicationCount,1);assert.equal(service.runtime.state.stats.audienceEffectsApplied,1)});
test('optional dependency outages degrade interactions but persistence fails before mutation',()=>{const store=new InMemoryDurableStore(),leases=new RunLeaseStore(),service=new MazeChannelService(options(store,leases));service.start(0);service.setDependencyHealth({gateway:false,moderation:false});assert.equal(service.status().interactionsEnabled,false);assert.equal(service.status().simulationEnabled,true);const beforeTick=service.runtime.state.tick;service.tick('autonomous-continuity',10);assert.ok(service.runtime.state.tick>beforeTick);service.setDependencyHealth({persistence:false});const before=checksum(service.runtime.state);assert.throws(()=>service.tick('blocked',20),error=>error.code==='PERSISTENCE_UNAVAILABLE');assert.equal(checksum(service.runtime.state),before)});
test('dedupe, snapshots and operator audit remain bounded and role gated',()=>{const store=new InMemoryDurableStore({snapshotCapacity:2,auditCapacity:4}),leases=new RunLeaseStore(),service=new MazeChannelService(options(store,leases,'worker-a',{commandDedupeCapacity:3,snapshotEveryCommands:1}));service.start(0);for(let i=1;i<=10;i++)service.tick(`bounded-${i}`,i*10);assert.ok(service.status().commandDedupeEntries<=3);assert.ok(store.snapshots('maze-channel').length<=2);const denied=service.executeControl({id:'control-1',actor:'viewer',role:'viewer',environment:'production',action:'emergency-halt',reason:'test'},200);assert.equal(denied.status,'denied');const accepted=service.executeControl({id:'control-2',actor:'admin',role:'admin',environment:'production',action:'emergency-halt',reason:'test'},210);assert.equal(accepted.status,'accepted');assert.equal(service.status().simulationEnabled,false);assert.equal(service.status().publicOutputProtected,true);assert.ok(store.audits().length<=4);assert.equal(service.executeControl({id:'control-2',actor:'admin',role:'admin',environment:'production',action:'emergency-halt',reason:'retry'},220).status,'duplicate')});
