'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{MazeOperationsMonitor,MazeOutputRecoveryWorkflow}=require('../../dist/games/ai-maze-escape/src/operations/health.js');
const{runPhase5MazeDrills,phase5MazeDrillIds}=require('../../dist/games/ai-maze-escape/src/operations/drills.js');
const{runMazePhase5Chaos}=require('../../dist/games/ai-maze-escape/src/operations/chaos.js');
function sample(overrides={}){return{nowMs:10000,simulationProgressSeq:20,lastMeaningfulEventMs:9000,lastSnapshotMs:9900,lastFrameChangeMs:9900,lastAudioMs:9900,intendedSilence:false,luma:.4,expectedScene:'normal',actualScene:'normal',queueUtilization:.1,memorySlopeMbPerHour:1,resourcePressure:.1,...overrides}}
test('operational monitor distinguishes healthy, degraded and unsafe output',()=>{const healthy=new MazeOperationsMonitor().observe(sample());assert.equal(healthy.status,'healthy');const silent=new MazeOperationsMonitor().observe(sample({lastAudioMs:1000}));assert.equal(silent.status,'degraded');assert.ok(silent.actions.some(action=>action.type==='mute-audio'));const unsafe=new MazeOperationsMonitor().observe(sample({nowMs:20000,lastSnapshotMs:1000,lastFrameChangeMs:1000,luma:0,actualScene:'error'}));assert.equal(unsafe.status,'unsafe');assert.ok(unsafe.actions.some(action=>action.type==='safe-scene'));assert.ok(unsafe.actions.some(action=>action.type==='verified-recovery'));const intended=new MazeOperationsMonitor().observe(sample({lastAudioMs:1000,intendedSilence:true}));assert.equal(intended.reasons.includes('silent-output'),false)});
test('queue and memory pressure reduce quality while crash loop opens a safe halt breaker',()=>{const pressure=new MazeOperationsMonitor().observe(sample({queueUtilization:.9,memorySlopeMbPerHour:45}));assert.ok(pressure.actions.some(action=>action.type==='reduce-quality'));const monitor=new MazeOperationsMonitor();monitor.recordCrash('simulation',1000);monitor.recordCrash('simulation',2000);monitor.recordCrash('simulation',3000);const loop=monitor.observe(sample({nowMs:3500}));assert.equal(loop.status,'unsafe');assert.ok(loop.actions.some(action=>action.type==='safe-halt'));assert.equal(monitor.canRestart('simulation',4000),false);assert.equal(monitor.canRestart('simulation',40000),true)});
test('unsafe output cannot resume until component, snapshot and output verification succeed',()=>{const unsafe=new MazeOperationsMonitor().observe(sample({nowMs:20000,lastSnapshotMs:1000,lastFrameChangeMs:1000,luma:0})),workflow=new MazeOutputRecoveryWorkflow(2);assert.equal(workflow.begin(unsafe).state,'safe-scene');assert.equal(workflow.advance({componentRestarted:true}).state,'restoring');assert.equal(workflow.advance({snapshotVerified:true}).state,'verifying');assert.equal(workflow.advance({snapshotVerified:true,outputHealthy:true}).state,'resumed');const failing=new MazeOutputRecoveryWorkflow(2);failing.begin(unsafe);failing.advance({componentRestarted:true});assert.equal(failing.advance({snapshotVerified:false}).state,'restoring');assert.equal(failing.advance({snapshotVerified:false}).state,'halted')});
test('all Phase 5 operational drills pass deterministically',()=>{const a=runPhase5MazeDrills(),b=runPhase5MazeDrills();assert.deepEqual(a,b);assert.equal(a.status,'pass');assert.equal(a.completed,phase5MazeDrillIds.length);assert.equal(a.results.length,phase5MazeDrillIds.length);assert.ok(a.results.every(result=>result.status==='pass'))});
test('compressed Phase 5 chaos is deterministic, restores authority and remains bounded',()=>{const a=runMazePhase5Chaos('maze-phase5-chaos'),b=runMazePhase5Chaos('maze-phase5-chaos');assert.deepEqual(a,b);assert.equal(a.status,'pass',JSON.stringify(a));assert.equal(a.integrityFailures,0);assert.equal(a.duplicateApplications,0);assert.equal(a.recoveryVerified,true);assert.equal(a.oldWriterFenced,true);assert.ok(a.events<=2500);assert.ok(a.snapshots<=4);assert.ok(a.dedupeEntries<=32);assert.match(a.checksum,/^[0-9a-f]{8}$/)});
