const test=require('node:test');const assert=require('node:assert/strict');
const {SnakeRuntime}=require('../../dist/games/autonomous-snake/src/runtime/run.js');const {checksum}=require('../../dist/packages/replay/src/index.js');
const {InMemoryEventStore,RunLeaseStore,BoundedQueue,CircuitBreaker,OperatorControlService,recoverSnakeRun}=require('../../dist/packages/operations-core/src/index.js');

test('append-only store is idempotent, sequence-safe and projections rebuild deterministically',()=>{const s=new InMemoryEventStore();assert.equal(s.append('r',{id:'e1',seq:0,type:'started',payload:{}}).status,'appended');assert.equal(s.append('r',{id:'e1',seq:0,type:'started',payload:{}}).status,'duplicate');assert.throws(()=>s.append('r',{id:'e2',seq:2,type:'bad-gap',payload:{}}));s.append('r',{id:'e2',seq:1,type:'result',payload:{kind:'game',reason:'victory',score:3}});assert.deepEqual(s.rebuild('r'),{eventCount:2,lastSeq:1,result:{kind:'game',reason:'victory',score:3}})});

test('run leases fence old writers and only current token can renew or release',()=>{const l=new RunLeaseStore();const a=l.acquire('channel','worker-a',1000,0);assert.equal(l.acquire('channel','worker-b',1000,1).status,'conflict');const b=l.acquire('channel','worker-b',1000,1001);assert.equal(b.status,'acquired');assert.equal(l.renew('channel',a.token,2000,1002).status,'fenced');assert.equal(l.renew('channel',b.token,2000,1002).status,'renewed')});

test('verified recovery restores newest compatible snapshot and preserves authoritative checksum',()=>{const r=SnakeRuntime.create({width:14,height:12,targetLength:25,profile:'portals'},'restore');for(let i=0;i<25&&!r.state.result;i++)r.step();const snap={version:1,createdAt:10,state:structuredClone(r.state),rng:r.rng.snapshot(),config:r.config,seed:r.seed,nextEventSeq:r.getNextEventSequence(),checksum:checksum(r.state)};const out=recoverSnakeRun([snap]);assert.equal(out.status,'restored');assert.equal(checksum(out.runtime.state),checksum(r.state));});

test('recovery skips corrupt newest snapshot and quarantines when no compatible evidence remains',()=>{const r=SnakeRuntime.create({width:10,height:10,targetLength:20},'recover');const good={version:1,createdAt:1,state:structuredClone(r.state),rng:r.rng.snapshot(),config:r.config,seed:r.seed,nextEventSeq:r.getNextEventSequence(),checksum:checksum(r.state)};const bad={...good,createdAt:2,checksum:'bad'};assert.equal(recoverSnakeRun([good,bad]).status,'restored');assert.equal(recoverSnakeRun([bad]).status,'quarantined')});

test('bounded queue rejects overflow without losing existing work and drains FIFO',()=>{const q=new BoundedQueue(2);assert.equal(q.push('a'),'accepted');assert.equal(q.push('b'),'accepted');assert.equal(q.push('c'),'overflow');assert.deepEqual([q.shift(),q.shift(),q.shift()],['a','b',undefined])});

test('circuit breaker opens after bounded failures and half-opens after cooldown',()=>{const b=new CircuitBreaker({failureThreshold:3,cooldownMs:100});assert.equal(b.allow(0),true);b.failure(1);b.failure(2);b.failure(3);assert.equal(b.allow(50),false);assert.equal(b.allow(104),true);b.success();assert.equal(b.state(),'closed')});

test('operator controls are typed, role-gated and append immutable audit records',()=>{const svc=new OperatorControlService();assert.equal(svc.execute({actor:'viewer',role:'viewer',action:'safe-scene',reason:'x'},1).status,'denied');assert.equal(svc.execute({actor:'oncall',role:'operator',action:'safe-scene',reason:'incident'},2).status,'accepted');assert.equal(svc.execute({actor:'oncall',role:'operator',action:'disable-interactions',reason:'provider'},3).status,'accepted');const audit=svc.audit();assert.equal(audit.length,3);assert.equal(audit[1].action,'safe-scene');assert.equal(audit[2].action,'disable-interactions')});
