'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{InMemoryDurableStore}=require('../../dist/packages/durable-store/src/index.js');
const{RunLeaseStore}=require('../../dist/packages/operations-core/src/lease.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
const{TowerChannelService}=require('../../dist/services/tower-channel/src/index.js');
function create(options={}){const store=options.store??new InMemoryDurableStore({eventCapacity:2000,snapshotCapacity:6,auditCapacity:200}),leases=options.leases??new RunLeaseStore(),service=new TowerChannelService({channelId:options.channelId??'tower-live',workerId:options.workerId??'worker-a',seed:'tower-channel-seed',config:{maxTicks:2000,noProgressTicks:1200},store,leases,leaseTtlMs:100,snapshotEveryCommands:100,compatibility:{gameVersion:'tower-1',deterministicVersion:'tower-r1',configHash:'cfg-1',contentHash:'content-1'},commandDedupeCapacity:options.commandDedupeCapacity??64});return{store,leases,service}}
test('tower channel persists commands exactly once and renews its writer lease',()=>{const{service,leases}=create();service.start(0);const before=checksum(service.runtime.state),first=service.tick('tick-1',10),after=checksum(service.runtime.state);assert.equal(first.status,'applied');assert.notEqual(after,before);const duplicate=service.tick('tick-1',11);assert.equal(duplicate.status,'duplicate');assert.equal(checksum(service.runtime.state),after);assert.equal(service.status().commandSeq,1);assert.ok((leases.current('tower-live')?.expiresAtMs??0)>10)});
test('verified recovery replays post-snapshot commands and fences the old writer',()=>{const{service,leases}=create();service.start(0);service.tick('tick-1',10);const checkpoint=service.captureSnapshot(12);service.tick('tick-2',20);service.tick('tick-3',30);const expected=checksum(service.runtime.state),result=service.recover({nowMs:200,newOwnerId:'worker-b',expectedChecksum:expected});assert.equal(result.status,'restored');if(result.status!=='restored')return;assert.equal(result.snapshotId,checkpoint.id);assert.equal(result.appliedCommands,2);assert.equal(checksum(result.runtime.state),expected);assert.equal(leases.current('tower-live')?.ownerId,'worker-b');assert.equal(service.status().leaseGeneration,2)});
test('durable command evidence preserves exactly-once retries after hot-cache eviction and restart',()=>{const store=new InMemoryDurableStore({eventCapacity:2000,snapshotCapacity:6,auditCapacity:200}),first=create({store,leases:new RunLeaseStore(),workerId:'worker-a',commandDedupeCapacity:2}).service;first.start(0);const original=first.tick('tick-1',10);first.tick('tick-2',20);first.tick('tick-3',30);assert.equal(first.status().commandDedupeEntries,2);const restarted=create({store,leases:new RunLeaseStore(),workerId:'worker-b',commandDedupeCapacity:2}).service;restarted.start(1000);const before=checksum(restarted.runtime.state),duplicate=restarted.tick('tick-1',1010);assert.equal(duplicate.status,'duplicate');assert.equal(duplicate.commandSeq,original.commandSeq);assert.equal(duplicate.checksum,original.checksum);assert.equal(checksum(restarted.runtime.state),before);assert.equal(restarted.status().commandSeq,3)});
test('persistence outage disables advertised authority and protects public output',()=>{const{service}=create();service.start(0);service.setDependencyHealth({persistence:false});const status=service.status();assert.equal(status.interactionsEnabled,false);assert.equal(status.simulationEnabled,false);assert.equal(status.publicOutputProtected,true)});
