'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{InMemoryDurableStore}=require('../../dist/packages/durable-store/src/index.js');
const{RunLeaseStore}=require('../../dist/packages/operations-core/src/lease.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
const{buildTowerInfluenceCandidates}=require('../../dist/games/infinite-tower-climb/src/influence/candidates.js');
const{createTowerInfluenceCommand}=require('../../dist/games/infinite-tower-climb/src/influence/apply.js');
const{TowerChannelService}=require('../../dist/services/tower-channel/src/index.js');
function service(){const store=new InMemoryDurableStore({eventCapacity:2000,snapshotCapacity:4,auditCapacity:100}),leases=new RunLeaseStore(),channel=new TowerChannelService({channelId:'tower-boundary',workerId:'worker-a',seed:'tower-boundary-seed',config:{maxTicks:2000,noProgressTicks:1200},store,leases,leaseTtlMs:200,snapshotEveryCommands:3,compatibility:{gameVersion:'tower-1',deterministicVersion:'tower-r1',configHash:'cfg',contentHash:'content'}});channel.start(0);return{store,channel}}
test('interaction outage rejects before command reservation or authority mutation',()=>{const{store,channel}=service(),candidate=buildTowerInfluenceCandidates(channel.runtime.state).find(item=>item.effectId==='shield');assert.ok(candidate);const command=createTowerInfluenceCommand(channel.runtime.state,{id:'audience-shield-1',candidate,scheduledTick:channel.runtime.state.tick+1,expiresAtTick:channel.runtime.state.tick+30,source:'fixture'}),beforeState=checksum(channel.runtime.state),beforeEvents=store.stats().events;channel.setDependencyHealth({gateway:false});assert.throws(()=>channel.enqueueInfluence('influence-1',command,10),error=>error?.code==='INTERACTION_UNAVAILABLE');assert.equal(checksum(channel.runtime.state),beforeState);assert.equal(store.stats().events,beforeEvents)});
test('persistence outage fails before a simulation mutation',()=>{const{store,channel}=service(),beforeState=checksum(channel.runtime.state),beforeEvents=store.stats().events;channel.setDependencyHealth({persistence:false});assert.throws(()=>channel.tick('tick-persistence-down',10),error=>error?.code==='PERSISTENCE_UNAVAILABLE');assert.equal(checksum(channel.runtime.state),beforeState);assert.equal(store.stats().events,beforeEvents)});
test('operator control requires durable audit before control-plane mutation',()=>{const{store,channel}=service(),before=channel.controls.state(),beforeAudit=store.stats().auditEntries;channel.setDependencyHealth({audit:false});assert.throws(()=>channel.executeControl({id:'control-1',actor:'operator-a',role:'operator',environment:'production',action:'safe-scene',reason:'drill'},20),error=>error?.code==='AUDIT_UNAVAILABLE');assert.deepEqual(channel.controls.state(),before);assert.equal(store.stats().auditEntries,beforeAudit)});
