'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{InMemoryDurableStore}=require('../../dist/packages/durable-store/src/index.js');
const{RunLeaseStore}=require('../../dist/packages/operations-core/src/lease.js');
const{checksum}=require('../../dist/packages/replay/src/index.js');
const{TowerChannelService}=require('../../dist/services/tower-channel/src/index.js');
function create(){const store=new InMemoryDurableStore({eventCapacity:2000,snapshotCapacity:6,auditCapacity:200}),leases=new RunLeaseStore(),service=new TowerChannelService({channelId:'tower-live',workerId:'worker-a',seed:'tower-channel-seed',config:{maxTicks:2000,noProgressTicks:1200},store,leases,leaseTtlMs:100,snapshotEveryCommands:100,compatibility:{gameVersion:'tower-1',deterministicVersion:'tower-r1',configHash:'cfg-1',contentHash:'content-1'},commandDedupeCapacity:64});return{store,leases,service}}
test('tower channel persists commands exactly once and renews its writer lease',()=>{const{service,leases}=create();service.start(0);const before=checksum(service.runtime.state),first=service.tick('tick-1',10),after=checksum(service.runtime.state);assert.equal(first.status,'applied');assert.notEqual(after,before);const duplicate=service.tick('tick-1',11);assert.equal(duplicate.status,'duplicate');assert.equal(checksum(service.runtime.state),after);assert.equal(service.status().commandSeq,1);assert.ok((leases.current('tower-live')?.expiresAtMs??0)>10)});
test('verified recovery replays post-snapshot commands and fences the old writer',()=>{const{service,leases}=create();service.start(0);service.tick('tick-1',10);const checkpoint=service.captureSnapshot(12);service.tick('tick-2',20);service.tick('tick-3',30);const expected=checksum(service.runtime.state),result=service.recover({nowMs:200,newOwnerId:'worker-b',expectedChecksum:expected});assert.equal(result.status,'restored');if(result.status!=='restored')return;assert.equal(result.snapshotId,checkpoint.id);assert.equal(result.appliedCommands,2);assert.equal(checksum(result.runtime.state),expected);assert.equal(leases.current('tower-live')?.ownerId,'worker-b');assert.equal(service.status().leaseGeneration,2)});
