'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const traffic=require('../../dist/games/ai-city-traffic/src/index.js');
function config(overrides={}){return{width:5,height:4,runTicks:5000,intermissionTicks:3,spawnEveryTicks:1,maxVehicles:220,maxGridlockTicks:500,incidentEveryTicks:100,incidentDurationTicks:35,...overrides}}
function influence(tick=0){return{schemaVersion:1,id:`snapshot-theme-${tick}`,effectId:'night-theme',viewerRef:`viewer_snapshot_${tick}`,source:'operator-test',authenticated:true,moderation:'approved',receivedTick:tick,scheduledTick:tick+1,expiresAtTick:tick+100,payload:{}}}
function health(overrides={}){return{nowMs:100_000,lastStepAtMs:99_900,lastSnapshotAtMs:98_000,lastRendererFrameAtMs:99_850,providerStatus:'healthy',moderationStatus:'healthy',queueDepth:2,queueCapacity:64,vehicleCount:80,vehicleCapacity:220,eventCount:500,eventCapacity:8192,progress:{startTick:100,endTick:120,elapsedMs:2000},memorySlopeBytesPerMinute:1_000_000,quarantined:false,...overrides}}
test('Phase 5 exports verified persistence, health, chaos, and soak APIs',()=>{for(const name of ['TrafficQuarantineError','sealTrafficSnapshot','verifyTrafficSnapshot','assessTrafficHealth','runTrafficChaosSuite','runTrafficAcceleratedSoak'])assert.ok(traffic[name],name);assert.equal(typeof traffic.TrafficRuntime.restore,'function')});
test('snapshot round-trip is JSON-safe and restores every authoritative component',()=>{const runtime=traffic.TrafficRuntime.create(config(),'snapshot-roundtrip');for(let i=0;i<90;i++)runtime.step();runtime.queueInfluence(influence(runtime.state.tick));for(let i=0;i<40;i++)runtime.step();const envelope=runtime.snapshot(),serialized=JSON.stringify(envelope),parsed=JSON.parse(serialized),restored=traffic.TrafficRuntime.restore(parsed);assert.equal(traffic.verifyTrafficSnapshot(parsed).payload.state.tick,runtime.state.tick);assert.equal(restored.checksum(),runtime.checksum());assert.deepEqual(restored.rngSnapshot(),runtime.rngSnapshot());assert.deepEqual(restored.events,runtime.events);assert.deepEqual(restored.snapshot(),envelope);assert.ok(serialized.length<5_000_000)});
test('restored execution matches uninterrupted execution with queued and applied influence',()=>{const uninterrupted=traffic.TrafficRuntime.create(config(),'resume-equivalence');for(let i=0;i<180;i++)uninterrupted.step();uninterrupted.queueInfluence(influence(uninterrupted.state.tick));for(let i=0;i<25;i++)uninterrupted.step();const restored=traffic.TrafficRuntime.restore(uninterrupted.snapshot());for(let i=0;i<360;i++){uninterrupted.step();restored.step()}assert.equal(restored.checksum(),uninterrupted.checksum());assert.deepEqual(restored.state,uninterrupted.state);assert.deepEqual(restored.events,uninterrupted.events)});
test('corruption, incompatible versions, and invalid invariants quarantine instead of silently restarting',()=>{const runtime=traffic.TrafficRuntime.create(config(),'quarantine-cases');for(let i=0;i<80;i++)runtime.step();const good=runtime.snapshot(),badChecksum=structuredClone(good);badChecksum.checksum='00000000';assert.throws(()=>traffic.TrafficRuntime.restore(badChecksum),error=>error instanceof traffic.TrafficQuarantineError&&error.code==='CHECKSUM_MISMATCH');const badVersion=structuredClone(good);badVersion.payload.snapshotVersion=99;const sealedVersion=traffic.sealTrafficSnapshot(badVersion.payload);assert.throws(()=>traffic.verifyTrafficSnapshot(sealedVersion),error=>error instanceof traffic.TrafficQuarantineError&&error.code==='VERSION_UNSUPPORTED');const badState=structuredClone(good.payload);badState.state.vehicles[0].cell=9999;const sealedState=traffic.sealTrafficSnapshot(badState);assert.throws(()=>traffic.TrafficRuntime.restore(sealedState),error=>error instanceof traffic.TrafficQuarantineError&&error.code==='INVARIANT_FAILURE');assert.equal(runtime.state.tick,80)});
test('health assessment distinguishes dependency degradation, renderer degradation, and authority quarantine',()=>{const healthy=traffic.assessTrafficHealth(health());assert.equal(healthy.status,'healthy');const provider=traffic.assessTrafficHealth(health({providerStatus:'offline'}));assert.equal(provider.status,'degraded');assert.ok(provider.actions.includes('disable-audience-input'));const renderer=traffic.assessTrafficHealth(health({lastRendererFrameAtMs:90_000}));assert.equal(renderer.status,'degraded');assert.ok(renderer.actions.includes('restart-renderer'));const stalled=traffic.assessTrafficHealth(health({lastStepAtMs:70_000,progress:{startTick:120,endTick:120,elapsedMs:20_000}}));assert.equal(stalled.status,'quarantined');assert.ok(stalled.actions.includes('restore-verified-snapshot'));const reportText=JSON.stringify(stalled);for(const forbidden of ['seed','viewerRef','runId'])assert.equal(reportText.includes(forbidden),false)});
test('accelerated soak keeps authoritative resources bounded and is reproducible',()=>{const options={seed:'phase5-soak',ticks:8000,sampleEveryTicks:500,config:config({runTicks:1200,intermissionTicks:2,maxVehicles:260})},a=traffic.runTrafficAcceleratedSoak(options),b=traffic.runTrafficAcceleratedSoak(options);assert.deepEqual(a,b);assert.equal(a.invariantFailures,0);assert.ok(a.restarts>=4);assert.ok(a.maxVehicles<=260);assert.ok(a.maxPendingDemand<=64);assert.ok(a.maxEventCount<=8192);assert.ok(a.maxSnapshotChars<5_000_000);assert.ok(a.samples.length>=10);assert.equal(a.ok,true)});
test('chaos suite verifies duplicate, outage, corruption, renderer, pressure, restore, and long-run paths',()=>{const report=traffic.runTrafficChaosSuite('phase5-chaos',{ticks:3200});assert.equal(report.ok,true,JSON.stringify(report));for(const name of ['duplicate-interaction','provider-outage','snapshot-corruption','snapshot-restore','renderer-recovery','queue-pressure','stalled-progress','bounded-long-run'])assert.equal(report.scenarios.find(item=>item.name===name)?.passed,true,name);assert.equal(report.failed,0);assert.ok(report.reportChecksum.length>=8)});
test('stream host uses verified restore and health assessment rather than a blind restart',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../../scripts/serve-city-traffic-stream.cjs'),'utf8');assert.match(source,/\.snapshot\(\)/);assert.match(source,/TrafficRuntime\.restore/);assert.match(source,/assessTrafficHealth/);assert.match(source,/restore-verified-snapshot|lastGoodSnapshot/)});
