import type{TrafficConfig}from '../../../../packages/game-contracts/src/index';import{checksum,stableSerialize}from '../../../../packages/replay/src/index';import type{RngSnapshot}from '../../../../packages/seeded-rng/src/index';import{trafficManifest}from '../manifest';import{assertTrafficInvariants}from '../rules/invariants';import type{TrafficEvent,TrafficState}from '../state/types';
export type TrafficQuarantineCode='MALFORMED_ENVELOPE'|'CHECKSUM_MISMATCH'|'VERSION_UNSUPPORTED'|'MANIFEST_MISMATCH'|'SIZE_LIMIT'|'RNG_MISMATCH'|'EVENT_SEQUENCE_INVALID'|'CONFIG_MISMATCH'|'INVARIANT_FAILURE';
export class TrafficQuarantineError extends Error{readonly code:TrafficQuarantineCode;readonly detail:string;constructor(code:TrafficQuarantineCode,detail:string){super(`Traffic snapshot quarantined: ${code}: ${detail}`);this.name='TrafficQuarantineError';this.code=code;this.detail=detail;Object.setPrototypeOf(this,new.target.prototype)}}
export interface TrafficSnapshotPayload{schemaVersion:1;gameId:'ai-city-traffic';snapshotVersion:number;rulesVersion:string;generatorVersion:string;createdAtTick:number;rootSeed:string;runIndex:number;config:TrafficConfig;state:TrafficState;rng:RngSnapshot;nextEventSeq:number;events:TrafficEvent[]}
export interface TrafficSnapshotEnvelope{schemaVersion:1;checksum:string;payload:TrafficSnapshotPayload}
function quarantine(code:TrafficQuarantineCode,detail:string):never{throw new TrafficQuarantineError(code,detail)}
function clone<T>(value:T):T{return structuredClone(value)}
export function sealTrafficSnapshot(payload:TrafficSnapshotPayload):TrafficSnapshotEnvelope{const safe=clone(payload);return{schemaVersion:1,checksum:checksum(safe),payload:safe}}
export function verifyTrafficSnapshot(value:unknown):TrafficSnapshotEnvelope{if(!value||typeof value!=='object')quarantine('MALFORMED_ENVELOPE','envelope must be an object');const envelope=clone(value as TrafficSnapshotEnvelope);if(envelope.schemaVersion!==1||typeof envelope.checksum!=='string'||!envelope.payload||typeof envelope.payload!=='object')quarantine('MALFORMED_ENVELOPE','required envelope fields are missing');const serialized=stableSerialize(envelope.payload);if(serialized.length>5_000_000)quarantine('SIZE_LIMIT','snapshot exceeds five million serialized characters');if(checksum(envelope.payload)!==envelope.checksum)quarantine('CHECKSUM_MISMATCH','payload checksum does not match');const payload=envelope.payload;if(payload.schemaVersion!==1||payload.gameId!=='ai-city-traffic')quarantine('VERSION_UNSUPPORTED','snapshot schema or game id is unsupported');if(payload.snapshotVersion!==trafficManifest.snapshotVersion)quarantine('VERSION_UNSUPPORTED',`snapshot version ${payload.snapshotVersion} is unsupported`);if(payload.rulesVersion!==trafficManifest.rulesVersion||payload.generatorVersion!==trafficManifest.generatorVersion)quarantine('MANIFEST_MISMATCH','rules or generator version differs from the current manifest');if(typeof payload.rootSeed!=='string'||payload.rootSeed.length<1||payload.rootSeed.length>256||!Number.isInteger(payload.runIndex)||payload.runIndex<0)quarantine('MALFORMED_ENVELOPE','root seed or run index is invalid');if(!Number.isInteger(payload.createdAtTick)||payload.createdAtTick!==payload.state?.tick)quarantine('MALFORMED_ENVELOPE','logical snapshot tick is invalid');if(payload.state?.runIndex!==payload.runIndex||payload.state?.seed!==`${payload.rootSeed}:run:${payload.runIndex}`||payload.rng?.seed!==payload.state.seed)quarantine('RNG_MISMATCH','run seed, state seed, and RNG seed must agree');if(checksum(payload.config)!==checksum(payload.state.config))quarantine('CONFIG_MISMATCH','runtime and state configuration differ');if(!Array.isArray(payload.events)||payload.events.length>8192||!Number.isInteger(payload.nextEventSeq)||payload.nextEventSeq<1)quarantine('EVENT_SEQUENCE_INVALID','event buffer or next sequence is invalid');let previous=0;for(const event of payload.events){if(!event||!Number.isInteger(event.seq)||event.seq<=previous||!Number.isInteger(event.tick)||event.tick<0)quarantine('EVENT_SEQUENCE_INVALID','events must have strictly increasing sequence ids and non-negative logical ticks');previous=event.seq}if(payload.nextEventSeq<=previous)quarantine('EVENT_SEQUENCE_INVALID','next event sequence must exceed the retained event tail');try{assertTrafficInvariants(payload.state)}catch(error){quarantine('INVARIANT_FAILURE',error instanceof Error?error.message:'unknown invariant failure')}return envelope}
