import{deepFreeze,isDigest}from '../../release-governance/src/index';
export interface CanaryPolicy{candidateChecksum:string;requiredDurationMs:number;maxSampleGapMs:number;maxErrorRate:number;minUptimeRatio:number;maxBadOutputSeconds:number;maxMemorySlopeMbPerHour:number;minSamples:number}
export interface CanaryStart{startedAtMs:number;environment:'ci'|'staging'|'production';source:'synthetic'|'ci'|'external-signed';realElapsed:boolean;attestationDigest:string}
export interface CanarySample{candidateChecksum:string;atMs:number;errorRate:number;uptimeRatio:number;badOutputSeconds:number;memorySlopeMbPerHour:number;replayDivergences:number;duplicateEffects:number;privateExposures:number;unauthorizedControls:number;unsafeModerationFailures:number;crashLoops:number;restoreFailures:number;recordCorruptions:number;platformPolicyBreaches:number;evidenceDigest:string}
export interface CanaryIncident{type:'rollback'|'clock-reset';atMs:number;reason:string;sampleDigest:string|null}
export interface CanaryEvaluation{status:'not-started'|'running'|'blocked'|'eligible'|'rollback';elapsedMs:number;sampleCount:number;blockers:string[]}
function error(code:string,message:string){const value=new Error(message);Object.assign(value,{code});return value}
function cloneFreeze<T>(value:T):Readonly<T>{return deepFreeze(structuredClone(value))}
export class CanaryController{
  private readonly frozenPolicy:Readonly<CanaryPolicy>;private startRecord:CanaryStart|undefined;private sampleRecords:CanarySample[]=[];private incidentRecords:CanaryIncident[]=[];private rollbackRequired=false;
  constructor(policy:CanaryPolicy){if(!policy.candidateChecksum||!Number.isFinite(policy.requiredDurationMs)||policy.requiredDurationMs<=0||!Number.isFinite(policy.maxSampleGapMs)||policy.maxSampleGapMs<=0||!Number.isFinite(policy.maxErrorRate)||policy.maxErrorRate<0||!Number.isFinite(policy.minUptimeRatio)||policy.minUptimeRatio<0||policy.minUptimeRatio>1||!Number.isFinite(policy.maxBadOutputSeconds)||policy.maxBadOutputSeconds<0||!Number.isFinite(policy.maxMemorySlopeMbPerHour)||policy.maxMemorySlopeMbPerHour<0||!Number.isInteger(policy.minSamples)||policy.minSamples<1)throw error('INVALID_POLICY','invalid canary policy');this.frozenPolicy=cloneFreeze(policy)}
  policy():Readonly<CanaryPolicy>{return this.frozenPolicy}
  start(input:CanaryStart):CanaryEvaluation{if(!Number.isFinite(input.startedAtMs)||!isDigest(input.attestationDigest))throw error('INVALID_START','invalid canary start evidence');if(this.startRecord)throw error('CANARY_ALREADY_STARTED','canary already started');this.startRecord=structuredClone(input);this.sampleRecords=[];this.rollbackRequired=false;return this.evaluate(input.startedAtMs)}
  ingest(sample:CanarySample):CanaryEvaluation{
    if(!this.startRecord)throw error('CANARY_NOT_STARTED','canary is not started');if(sample.candidateChecksum!==this.frozenPolicy.candidateChecksum)throw error('CANDIDATE_MISMATCH','sample candidate does not match frozen policy');if(!isDigest(sample.evidenceDigest))throw error('INVALID_EVIDENCE','invalid sample digest');for(const value of Object.values(sample))if(typeof value==='number'&&!Number.isFinite(value))throw error('INVALID_SAMPLE','sample contains non-finite value');
    const previous=this.sampleRecords[this.sampleRecords.length-1];if(previous&&sample.atMs<=previous.atMs)throw error('NON_MONOTONIC_SAMPLE','sample time must increase');if(previous&&sample.atMs-previous.atMs>this.frozenPolicy.maxSampleGapMs)throw error('SAMPLE_GAP','canary sample gap exceeds frozen policy');if(sample.atMs<this.startRecord.startedAtMs)throw error('NON_MONOTONIC_SAMPLE','sample predates canary start');this.sampleRecords.push(structuredClone(sample));
    const critical:string[]=[];if(sample.replayDivergences>0)critical.push('replay-divergence');if(sample.duplicateEffects>0)critical.push('duplicate-effects');if(sample.privateExposures>0)critical.push('private-exposure');if(sample.unauthorizedControls>0)critical.push('unauthorized-control');if(sample.unsafeModerationFailures>0)critical.push('unsafe-moderation');if(sample.crashLoops>0)critical.push('crash-loop');if(sample.restoreFailures>0)critical.push('restore-failure');if(sample.recordCorruptions>0)critical.push('record-corruption');if(sample.platformPolicyBreaches>0)critical.push('platform-policy-breach');if(sample.errorRate>this.frozenPolicy.maxErrorRate)critical.push('error-rate');if(sample.uptimeRatio<this.frozenPolicy.minUptimeRatio)critical.push('uptime');if(sample.badOutputSeconds>this.frozenPolicy.maxBadOutputSeconds)critical.push('bad-output');if(sample.memorySlopeMbPerHour>this.frozenPolicy.maxMemorySlopeMbPerHour)critical.push('memory-slope');
    if(critical.length){this.rollbackRequired=true;this.incidentRecords.push(structuredClone({type:'rollback',atMs:sample.atMs,reason:[...new Set(critical)].sort().join(','),sampleDigest:sample.evidenceDigest})as CanaryIncident)}return this.evaluate(sample.atMs);
  }
  evaluate(nowMs:number):CanaryEvaluation{
    if(!Number.isFinite(nowMs))throw new RangeError('nowMs');if(!this.startRecord)return{status:'not-started',elapsedMs:0,sampleCount:0,blockers:['canary-not-started']};const elapsedMs=Math.max(0,nowMs-this.startRecord.startedAtMs);if(this.rollbackRequired)return{status:'rollback',elapsedMs,sampleCount:this.sampleRecords.length,blockers:['rollback-triggered']};const blockers:string[]=[];const real=this.startRecord.environment==='production'&&this.startRecord.source==='external-signed'&&this.startRecord.realElapsed&&isDigest(this.startRecord.attestationDigest);if(!real)blockers.push('real-production-evidence');if(elapsedMs<this.frozenPolicy.requiredDurationMs)blockers.push('minimum-duration');if(this.sampleRecords.length<this.frozenPolicy.minSamples)blockers.push('minimum-samples');const last=this.sampleRecords[this.sampleRecords.length-1];if(last&&nowMs-last.atMs>this.frozenPolicy.maxSampleGapMs)blockers.push('sample-freshness');if(!last)blockers.push('missing-samples');const onlyProgress=blockers.every(item=>['minimum-duration','minimum-samples','missing-samples','sample-freshness'].includes(item));return{status:blockers.length?(onlyProgress?'running':'blocked'):'eligible',elapsedMs,sampleCount:this.sampleRecords.length,blockers:[...new Set(blockers)].sort()};
  }
  invalidateForMaterialChange(category:string,atMs:number):void{if(!category||!Number.isFinite(atMs))throw new RangeError('material change');this.incidentRecords.push(structuredClone({type:'clock-reset',atMs,reason:`material-change:${category}`,sampleDigest:null})as CanaryIncident);this.startRecord=undefined;this.sampleRecords=[];this.rollbackRequired=false}
  samples():CanarySample[]{return structuredClone(this.sampleRecords)}
  incidents():Readonly<CanaryIncident>[]{return this.incidentRecords.map(record=>cloneFreeze(record))}
}
